### ISSUE TITLE
Fix  formatted I/O

### ISSUE THREAD

**Issue by HuKeping** [docker/notary#1014]
https://github.com/docker/notary/blob/master/trustpinning/certs.go#L143

```
logrus.Debugf("checking root against trust_pinning config", gun)
```

We can either use `logrus.Debug` or add the `%s` to it.

**Comment by riyazdf** [comment]
@ecordell @HuKeping - that's definitely a great fix.  Happy to have that in a separate PR as well if we want to fast-track it.

**Comment by HuKeping** [comment]
Thanks @ecordell !
