### ISSUE TITLE
notary signer not able to connect to mariadb.

### ISSUE THREAD

**Issue by clemenko** [docker/notary#1026]
When deploying with `docker-compose up -d` we see all the container start. However we are seeing the notary_server error with `waiting for mysql://server@tcp(mysql:3306)/notaryserver to come up.` We started an alpine image with `docker run --rm -it --network notary_mdb alpine sh` and successfully resolved "mysql" and were even able to curl port 3306.

Here is a `docker network inspect notary_mdb`

```
[
    {
        "Name": "notary_mdb",
        "Id": "386c02f4b06ed8d9b3897c34208aa69bc17bc53e72fdd46bf01a294db129fc80",
        "Scope": "global",
        "Driver": "overlay",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "10.0.0.0/24",
                    "Gateway": "10.0.0.1/24"
                }
            ]
        },
        "Internal": false,
        "Containers": {
            "19b90d2f24c02861ba6c824a90bd942aa0dfae7e31576e6dee2ae68125efe613": {
                "Name": "notary_signer_1",
                "EndpointID": "4e21bfb2688e0be92255d5855a2c3435cc03a477d31a6cb203fc537c25f103fd",
                "MacAddress": "02:42:0a:00:00:03",
                "IPv4Address": "10.0.0.3/24",
                "IPv6Address": ""
            },
            "e14ab11523617e47a273458885b2071a9a6651fcafc25ab51425e1bb8eda62e9": {
                "Name": "notary_server_1",
                "EndpointID": "f7524cb1e7bacdec89890b7ce759c5c6ef5eb171b88bd47600d51dc51786334e",
                "MacAddress": "02:42:0a:00:00:04",
                "IPv4Address": "10.0.0.4/24",
                "IPv6Address": ""
            },
            "ebdf9c76237bf1218d0e69e1a988814df8049f4273f4856e644822947bafae34": {
                "Name": "notary_mysql_1",
                "EndpointID": "fa219f9154ef3ded23e1dff94488a3f482d0b16a5089bbfebb6df8ac0accb1ff",
                "MacAddress": "02:42:0a:00:00:02",
                "IPv4Address": "10.0.0.2/24",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {}
    }
]
```

What is a good next step for troubleshooting?

**Comment by riyazdf** [comment]
@clemenko: thanks for the report.
It'd be useful to view the logs on the `docker compose up` command (just run without `-d`) so we can view the logs and further debug. 
It might also be worth taking a peek at the docker compose yaml file if possible, though logs would be more helpful to pinpoint the cause of the error.

**Comment by endophage** [comment]
Also, how long are you waiting? That message `waiting ...` isn't an error. It's a loop we build in to manage some docker timing that essentially says the MySQL/MariaDB container is up before the database server is actually ready to accept connections.

If it's truly an error, it should eventually echo `notaryserver database failed to come up within 30 seconds`

**Comment by cyli** [comment]
@clemenko Also, is this being deployed locally via `docker-compose`, or to a remote docker host?  If being deployed to a remote host, `docker-compose up` fails with the behavior you're seeing because the compose file attempts to mount local sql data which sets up the databases and users that the server and signer need, and these files don't exist on the remote host (compose doesn't copy over that data, unfortunately).

**Comment by clemenko** [comment]
This was caused by a "search domain.com" in the hosts /etc/resolv.conf.
