### ISSUE TITLE
Discuss not checking in the vendor directory

### ISSUE THREAD

**Issue by cyli** [docker/notary#1040]
@ecordell brought up the possibility of not checking in the vendor directories into the git repository.  https://github.com/docker/notary/pull/1027#issuecomment-260033080

We might want to discuss this as a possibility, look at general practices, etc. since we'll have the `vendor.conf` that can be used to pull in all the vendored code when building.

**Comment by endophage** [comment]
Given [this](http://www.theregister.co.uk/2016/03/23/npm_left_pad_chaos/) I strongly believe it's prudent to vendor all our dependencies. We don't want to be caught out by something becoming unavailable and having to suddenly, possibly under pressure, migrate to an alternative.

The JS example may be silly, but should serve as a warning about relying on strangers for your product stability.

**Comment by endophage** [comment]
No ongoing discussion so I'm closing this. We can re-open if necessary.

**Comment by endophage** [comment]
Also had input from the DTR team they had the problem of a Go dependency becoming unavailable earlier this year.
