### ISSUE TITLE
Operations leading to YubiKey signing and related touch policy

### ISSUE THREAD

**Issue by ruimarinho** [docker/notary#1050]
I would like to understand which operations trigger the usage of the root key. I was under the impression that regular signing operations, even those implicit such as `docker push`, would require a PIN and/or touch on the YubiKey.

**Comment by cyli** [comment]
The only times the root key is needed are:

1. When creating the repository (and hence all the metadata) for the first time
2. Rotating the timestamp, snapshot, or target keys.

You do not need the root key when doing `docker push` except for the first time you ever push to that repository.  For regular signing operations, the targets key or a delegation key is used.

**Comment by ruimarinho** [comment]
Ok, thank you for clarifying this. In my case, since the CI system is the one doing the push, it makes sense not to require physical interaction, but wanted to make sure it's working as intended or not.
