### ISSUE TITLE
Snapshot key generation on notary init

### ISSUE THREAD

**Issue by ruimarinho** [docker/notary#1053]
Is there a reason for `notary init` to generate a snapshot key, even on Docker 1.10+, while "init on push" does not?

**Comment by riyazdf** [comment]
Notary and Docker with DCT always generate a snapshot key for new repositories, but newer versions of Docker automatically rotate the snapshot key to be managed by the Notary server.  This is meant to be more user-friendly for delegations setup, though users can always rotate the snapshot key back to their local machine if they wish, using `notary key rotate`.

The Notary CLI is meant to be less opinionated and provide users with full control of their keys, though users can still rotate snapshot keys to the server using the `-r` flag for `notary key rotate`

**Comment by ruimarinho** [comment]
Perfect. Thanks for the explanation :)
