### ISSUE TITLE
Importing ECC private key fails

### ISSUE THREAD

**Issue by ruimarinho** [docker/notary#1057]
When importing a ECC private key for delegation, the `key import` command fails with the following error:

```
failed to import key to store: Invalid key generated, key may be encrypted and does not contain path header
```

`~/.docker/trust/private/tuf_keys/<id>.key` is there, but my guess is that it's invalid.

Steps to reproduce:

```sh
openssl ecparam -name prime256v1 -genkey -out delegation.key
openssl req -new -sha256 -key delegation.key -out delegation.csr
openssl x509 -req -days 365 -in delegation.csr -signkey delegation.key -out delegation.crt
notary key import delegation.key --role user --gun
```

**Comment by endophage** [comment]
Can you try adding the `-noout` flag to your `openssl ecparam ...` command? Without that flag the produced pem file includes 2 blocks, the first of which is not a valid key (it's a pem block containing the EC parameters in isolation). I wrote it a few months back now but I believe the warning you're seeing is about that first block, and the import code continues and attempts to import all keys it finds, hence why you're seeing the `<id>.key` file still being created (that file should be valid).

**Comment by ruimarinho** [comment]
Yep, that was it, thanks. Should notary be ignoring/skipping the block instead?

**Comment by endophage** [comment]
I think the behaviour is correct, we just need to clarify the messaging. It is skipping the block and continuing, hence you say the `.key` file created even when the message was output. The message we print should make this clearer as I can absolutely see why you thought the import had failed based on the message that was output.

I'll open an issue for improving the messaging during an import.
