### ISSUE TITLE
Mapping role to arbitrary certificate common name on Yubikey

### ISSUE THREAD

**Issue by ruimarinho** [docker/notary#1061]
Currently, notary expects the Common Name (CN) on a certificate loaded on the Yubikey to match that of a role. 

Considering I want to manage the lifecycle of the `root` key used for notary, I have generated it using the `yubico-piv-tool`. I also want it to be signed by an internal CA, which makes the `root` common name quite problematic across collaborators. 

It would be interesting to be able to map a certain role to an arbitrary Common Name on the Yubikey.

**Comment by endophage** [comment]
I'm not sure I understand the problem. The role `root` indicates what the key is used for, not who is using it. Could you explain how that logic would change when collaborators are introduced? None of the collaborators should be using a `root` key for anything other than signing the `root` role.

**Comment by ruimarinho** [comment]
Hm, I'm not suggesting changing the role, but instead being able to say that the certificate stored on the Yubikey with CN (`ruimarinho-dct-root`) maps to key id `bf98cc4…` with role `root`.

Right now, if I create a CN with this name, notary won't find the key on the Yubikey.

**Comment by cyli** [comment]
@ruimarinho So the goal would be that the CA issues CNs that are based on your user identity?

**Comment by ruimarinho** [comment]
Yes, identities which are known to the org but still actable as `root` on Notary's term.

**Comment by endophage** [comment]
So as far as signing goes, I think this request rolls up into #306 (which we should re-title to more generally be "support all keys on yubikey"). For signing purposes we would ideally only care about the canonical key IDs (generated from the public key bytes only, not the whole cert) and not the CN, etc.. in the x509 cert.

This should probably be closed as a duplicate (really a subpart) of #306. I'll leave it open for a little bit in case there's something I'm missing.

**Comment by cyli** [comment]
Maybe a slightly different issue - I think one of the reasons for CNs on the cert was so we'd know whether or not we should list or delete a key from the Yubikey (as in did we create it, and thus have control over it).

If we supported any key ID, should we then just list all possible PIV keys in the Yubikey?  Should we be able to delete any key?

Is there some other extended attribute field we should add to our certs that indicate that this key was created by notary, and hence it can be deleted by us?

**Comment by endophage** [comment]
For root keys I don't know that we can ever make an intelligent decision about deleting them. It's always going to be up to the user to determine when they want to deprecate a specific root key. The same goes for delegation keys.

For targets/snapshot keys, I think we could only somewhat sensibly delete, with some interactivity, when a rotation is performed, but only if the yubikey containing the key being obsoleted is present, which isn't a necessary requirement (root key might be on a different yubikey etc...). Even that's only true assuming we never explicitly support target/snapshot key sharing across repos.

**Comment by cyli** [comment]
Hmm... in that case, I'm wondering if it ever makes sense to delete any keys, even on disk.  I'll update #306 with some notes from this issue then - it does seem like a subproblem of #306.

**Comment by endophage** [comment]
Closing this as a a subset of #306's functionality.
