### ISSUE TITLE
Use GUN instead of ImageName to show that notary is not only for docker image

### ISSUE THREAD

**Issue by HuKeping** [docker/notary#1069]
Since Notary is not only used for signing Docker image, it can be used to allows anyone to have trust over arbitrary collections of data . So we should probably not use `imageName` as the  GUN ( Globally Unique Names ) to identify trust collections.

We should also add some other demo/document for the non-signing-docker-image use cases, although it is not the priority task.

See https://github.com/docker/notary/blob/master/server/server.go#L152  
and maybe some other place.

**Comment by endophage** [comment]
I don't disagree with anything you've stated, but it's internal and most users will never see the URL templating. I'd accept a PR changing it to `gun` but I'm kind of indifferent.

If we mix it up in the docs anywhere, we'd definitely want to change it there.

**Comment by HuKeping** [comment]
Aha, I'm not feeling very strong about it also, it's just when I reading some code and find that we are using the `imageName` where it seems should be better to use `gun`. Of course most user will not see that though.

**Comment by ecordell** [comment]
This was done in #1081
