### ISSUE TITLE
delegation breaks targets signing

### ISSUE THREAD

**Issue by lewiada** [docker/notary#1077]
My understanding is that even if we enable delegation, the 'primary' targets key should still be able to sign metadata.  However, when I initialize a new repo and enable delegation, it appears to break the ability to use the primary targets key.  

```
notary init $GUN
notary key rotate $GUN snapshot -r
notary publish $GUN

docker push $GUN:1
<Successfully signed $GUN:1>

notary delegation add $GUN targets/releases delegation1.crt --all-paths
notary publish $GUN

docker push $GUN:1
<Failed to sign $GUN:1 - no valid signing keys for delegation roles
no valid signing keys for delegation roles>
```

Notice that pushing works prior to adding a delegated key, then breaks.

**Comment by ecordell** [comment]
Hi @lewiada 

You'll need to import the private key portion of the delegation key in order to sign with it. Do you still have a problem if you run:

```
notary key import delegation1.key --role targets/releases
```

(where delegation1.key is the private key corresponding to delegation1.crt)?

**Comment by riyazdf** [comment]
@lewiada once you've set up delegations for use with DCT, you are correct that the Targets key cannot be directly used to sign image tags.

The rationale is because the Targets key administrates the delegation roles, as holder of the Targets key you can simply add your own key to the delegation role you wish to sign with - and then you can `notary key import` as @ecordell mentions above

**Comment by endophage** [comment]
This was an opinionated decision specific to DCT that we decided would prevent users from accidentally shadowing targets in delegations with targets in the `targets` role, and getting confused about which target was being used at any given time.

**Comment by lewiada** [comment]
so if a delegated key is used to sign a second delegated key, the does the first delegated key stop working in a similar way?

e.g. if targets->delegated-1 ca
