### ISSUE TITLE
Link broken in documentation

### ISSUE THREAD

**Issue by rhonnava** [docker/notary#1106]
In this page: http://docs.master.dockerproject.org/notary/notary-signer/, the link to "this script" under Authentication section is broken.

It is supposed to lead to https://github.com/docker/notary/blob/master/docs/opensslCertGen.sh which does not exist.

**Comment by riyazdf** [comment]
@rhonnava - sorry, I think you ran into a really outdated docs page :(  Our docs team will be taking down that website soon.

Our latest docs are hosted here: https://docs.docker.com/notary/  Please let us know if you run into any issues there!
