### ISSUE TITLE
tokenAuth pingClient should not assume the "v2" url is at the root.

### ISSUE THREAD

**Issue by reasonerjt** [docker/notary#1107]
If I host my notary-server under a sub path:
**x.x.x.x/notary**
I can use the command:
```
notary -s https://x.x.x.x/notary list ......
```
to list the targets, however when the "auth" is configured at the notary-server, the command will not challenge me for credentials.

Checked the code:
https://github.com/docker/notary/blob/master/cmd/notary/tuf.go#L892

the "/v2/" url is hard coded to the root, but in my case the notary client should "ping" the url **x.x.x.x/notary/v2** instead of **x.x.x.x/v2**

a quick fix:
```
var p string
if strings.HasSuffix(endpoint.Path, "/") {
     p = endpoint.Path + "v2/"
} else {
     p = endpoint.Path + "/v2/"
}
subPath, err := url.Parse(p)
```
can work around the problem.

**Comment by ecordell** [comment]
:+1: This is important for potential non-container registry Notary users.

IMO, we should just have a separately configurable auth URL which is perhaps by default `tuf_url`+ `/v2`

**Comment by reasonerjt** [comment]
@ecordell 
so that's what my fix in OP is doing, I'll open a PR if you think it looks OK.
