### ISSUE TITLE
"docker push"  to private docker registry error using Notary

### ISSUE THREAD

**Issue by chunglam1999** [docker/notary#1111]
When I push the docker image 'hello-world' to my own private registry (same PC loaclhost:5000) with content trust using Notary, there is error message:
>docker --debug push localhost:5000/hello-world:latest
DEBU[0004] Loading snapshot...
DEBU[0004] snapshot role has key IDs: a0cc2b04bc52a294ffb0a238d7cad55ed8c5b3d01b94114f7f30cd852b82b85d
DEBU[0004] verifying signature for key ID: a0cc2b04bc52a294ffb0a238d7cad55ed8c5b3d01b94114f7f30cd852b82b85d
DEBU[0004] successfully verified cached snapshot
DEBU[0004] Loading targets...
DEBU[0004] targets role has key IDs: 6d30763e398c0794de4df1b5289a6861c5c41c67b9aa7a511717f610ede51bc8
DEBU[0004] verifying signature for key ID: 6d30763e398c0794de4df1b5289a6861c5c41c67b9aa7a511717f610ede51bc8
DEBU[0004] successfully verified cached targets
Failed to sign "localhost:5000/hello-world":latest - no hashes specified for target ""
no hashes specified for target ""

Thanks for help.
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
details setup:
[docker-push-notary-log.txt](https://github.com/docker/notary/files/816031/docker-push-notary-log.txt)

1. I installed the docker-engine  1.13.1 and docker-registry 0.6.8 on the same PC running Centos 7:
>docker run hello-world
[root@lenovo-2 ~]# docker images
REPOSITORY                                           TAG                           IMAGE ID            CREATED             SIZE
hello-world                                          latest                        48b5124b2768        6 weeks ago         1.84 kB

2. Install notary server (version 0.5) notary client (version 0.3)
>git clone https://github.com/docker/notary.git
>cd notary
>$ docker-compose up 
>mkdir -p ~/.notary && cp cmd/notary/config.json cmd/notary/root-ca.crt ~/.notary
>notary init example.com/collections
>docker run hello-world
>export DOCKER_CONTENT_TRUST_SERVER=https://127.0.0.1:4443
>export DOCKER_CONTENT_TRUST=1
>./notary -d ~/.docker/trust key rotate localhost:5000/hello-world timestamp -r //fix timestamp issue
>docker tag hello-world localhost:5000/hello-world:latest
>docker --debug push localhost:5000/hello-world:latest

**Comment by endophage** [comment]
Thanks for the report, sorry we took a while to respond. Let's track this where you just reposted on docker/docker (https://github.com/docker/docker/issues/31670#issuecomment-285222109). This is almost certainly a problem with the integration there rather than a core notary issue so that's the right place to track it.
