### ISSUE TITLE
notary:signer SQL error, failed RNG?!?

### ISSUE THREAD

**Issue by etotheipi** [docker/notary#1115]
Using `notary:server` and `notary:signer` which are 0.5.0.  Using docker v 1.13.0.  

My code is in a private repo.  I can find a way to make it public if necessary, but this looks more like an issue with signer docker image.

I created two mysql db containers, one each for notary:signer/server containers and their migrations.  I have an script of openssl statements to create CA, server, signer keys & certs which get mounted into the appropriate containers.  I manage it all with docker-compose for hostname resolution.  

Below is the set of commands I run based on my Makefile and various scripts/modifications, which is not included here, but I can add if necessary.  I think this a problem on the signer side:
 
```
$ rm -rf ~/.docker/trust  # START FROM SCRATCH ON THE HOST

$ docker-compose up -d mysql-serv  # no persistence
$ docker-compose up -d mysql-sign  # no persistence
$ sleep 60
$ docker-compose up migrations-server  # Successful 5 migrations
$ docker-compose up migrations-signer  # Successful 2 migrations
$ docker-compose up -d notary-signer  # no persistence
$ sleep 5
$ docker-compose up -d notary-server  # no persistence, exposed on localhost:4443

$ notary -s https://localhost:4443 -d ~/.docker/trust --tlscacert=ca/ca.crt init localhost:5000/my-image -p
```

On the `notary ... init` command, I get the following.  
```
No root keys found. Generating a new root key...
You are about to create a new root signing key passphrase. This passphrase
will be used to protect the most sensitive key in your signing system. Please
choose a long, complex passphrase and be careful to keep the password and the
key file itself secure and backed up. It is highly recommended that you use a
password manager to generate the passphrase and keep it safe. There will be no
way to recover this key. You can find the key in your config directory.
Enter passphrase for new root key with ID be891a5:
Repeat passphrase for new root key with ID be891a5:
Enter passphrase for new targets key with ID fe95f71 (localhost:5000/my-image):
Repeat passphrase for new targets key with ID fe95f71 (localhost:5000/my-image):
Enter passphrase for new snapshot key with ID 9083e30 (localhost:5000/my-image):
Repeat passphrase for new snapshot key with ID 9083e30 (localhost:5000/my-image):
Auto-publishing changes to localhost:5000/my-image

* fatal: An error occurred during validation: rpc error: code = 5 desc = key ee3b8956cf5c4a7ad24516ebf675687eb533d8ba92fa65f84d037cf7fbc88202 not found
```

The signer logs show this
```
{"level":"info","msg":"Version: 0.5.0, Git commit: 3657629","time":"2017-03-13T19:59:28Z"}
{"go.version":"go1.7.1","level":"info","msg":"CreateKey: Created KeyID 2315c1d6bae1a99988ef19e0b13801f543fe81b6b5f442b675ab7e7bef23a9b6","time":"2017-03-13T20:16:57Z"}

(Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'role = ? AND gun = ? AND algorithm = ? AND last_used IS NULL)) ORDER BY key_id,`' at line 1)
[2017-03-13 20:16:57]
{"go.version":"go1.7.1","level":"error","msg":"GetKeyInfo: key ee3b8956cf5c4a7ad24516ebf675687eb533d8ba92fa65f84d037cf7fbc88202 not found","time":"2017-03-13T20:16:57Z"}
```

**Crticial Observation:  I am not persisting any data whatsoever yet EVERY TIME it's tell me  #something about key ID: ee3b8956cf5c4a7ad24...**  I did a google search for that and someone else has the same key ID in their error output.  Is there a major RNG snafu going on here?  Or is there some kind of null-key getting hashed leading to multiple instances of the same error referencing the same key ID?

Regardless, the SQL error is referencing:
https://github.com/docker/notary/blob/master/signer/keydbstore/sql_keydbstore.go#L205

My signer-config is:

```
$ cat signer/signer-config.json
{
	"server": {
		"http_addr": ":4444",
		"grpc_addr": ":7899",
		"tls_cert_file": "/certs/signer.crt",
		"tls_key_file": "/certs/signer.key",
		"client_ca_file": "/certs/ca.crt"
	},
	"logging": {
		"level": "info"
	},
	"storage": {
		"backend": "mysql",
		"db_url": "root@tcp(mysql-sign:3306)/notarysigner?parseTime=True",
		"default_alias": "passwordalias1"
	}
}
```

**Comment by etotheipi** [comment]
RE persistence:  I was simply pointing out that key ee3b8956 couldn't have persisted between sessions because I wasn't using any volume mounts for mysql or anything else.  If that's a null key, then it doesn't matter.  I obviously plan to persist the DBs to disk in a real deployment.

Here's what the `mysql-sign` DB looks like:
```
mysql> SHOW DATABASES;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| mysql              |
| notarysigner       |
| performance_schema |
| sys                |
+--------------------+
5 rows in set (0.00 sec)

mysql> USE notarysigner
Database changed
mysql> SHOW TABLES;
+------------------------+
| Tables_in_notarysigner |
+------------------------+
| private_keys           |
| schema_migrations      |
+------------------------+
2 rows in set (0.00 sec)

mysql> DESCRIBE private_keys;
+------------------+--------------+------+-----+---------+----------------+
| Field            | Type         | Null | Key | Default | Extra          |
+------------------+--------------+------+-----+---------+----------------+
| id               | int(11)      | NO   | PRI | NULL    | auto_increment |
| created_at       | timestamp    | YES  |     | NULL    |                |
| updated_at       | timestamp    | YES  |     | NULL    |                |
| deleted_at       | timestamp    | YES  |     | NULL    |                |
| key_id           | varchar(255) | NO   | UNI | NULL    |                |
| encryption_alg   | varchar(255) | NO   |     | NULL    |                |
| keywrap_alg      | varchar(255) | NO   |     | NULL    |                |
| algorithm        | varchar(50)  | NO   |     | NULL    |                |
| passphrase_alias | varchar(50)  | NO   |     | NULL    |                |
| public           | blob         | NO   |     | NULL    |                |
| private          | blob         | NO   |     | NULL    |                |
| gun              | varchar(255) | NO   |     | NULL    |                |
| role             | varchar(255) | NO   |     | NULL    |                |
| last_used        | datetime     | YES  |     | NULL    |                |
+------------------+--------------+------+-----+---------+----------------+
14 rows in set (0.00 sec)
```

My guess is that somehow the SQL statement in sql_keydbstore.go has null/bad values in it, leading it to fail.  However, I have no experience with Go to be able to help debug that.  Any other useful information I can provide?

**Comment by etotheipi** [comment]
One last comment: the original signer output error *also* has a constant key fingerprint:

```
{"go.version":"go1.7.1","level":"info","msg":"CreateKey: Created KeyID 2315c1d6bae1a99988ef19e0b13801f543fe81b6b5f442b675ab7e7bef23a9b6","time":"2017-03-13T17:11:47Z"}
```

That 2315c1d6 key is the same every time I run this, as well.  So everytime I run this from scratch with no persistence, it says:
```
# Created KeyID 2315c1d6bae1a99988ef19e0b13...
# SQL syntax error
# GetKeyInfo: key ee3b8956cf5c4a7ad24516ebf67... not found
```

**Comment by ecordell** [comment]
What mysql container, specifically, are you using? Notary is tested against mariadb.

If you can add `db.LogMode(true)` in `NewSQLKeyDBStore`, every full SQL statement will be logged in the signer, which may help debug the sql issue. It may also help to turn logging up to `debug` from `info`.

Once you have those, you can try running them against your DB directly to see what the sql error is. It's possible something is persisting even if you haven't explicitly set up a mount (e.g. the mariadb container mounts in `/var/lib/mysql` for you)

I would like to get to the bottom of the keyID issue as well so that it can be better messaged.

**Comment by etotheipi** [comment]
I'm using my own docker-compose file which has explicitly excluded host mount points.  I didn't think that a `VOLUME "/var/lib/mysql"` in a Dockerfile allows for persistence after containers have been stopped and removed.  

I'm using `mysql:8.0.0` as the image for the DB.  Should I try something MariaDB?  I honestly don't know much about SQL databases, I'm just shooting in the dark here.

I was able to create a new signer with your recommend LogMode change.  I got the following output from the signer (yay for Docker -- rebuilding it with the modification was trivial even though I know nothing about Go):

```
{"level":"info","msg":"Version: 0.5.0, Git commit: a76c377","time":"2017-03-14T18:04:57Z"}
{"level":"debug","msg":"Trusting 1 certs","time":"2017-03-14T18:04:57Z"}
{"level":"debug","msg":"Default Alias: passwordalias1","time":"2017-03-14T18:04:57Z"}

(/go/src/github.com/docker/notary/signer/keydbstore/sql_keydbstore.go:207)
[2017-03-14 18:05:41]  Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'role = ? AND gun = ? AND algorithm = ? AND last_used IS NULL)) ORDER BY key_id,`' at line 1

(/go/src/github.com/docker/notary/signer/keydbstore/sql_keydbstore.go:207)
[2017-03-14 18:05:41]  [25.97ms]  SELECT  * FROM `private_keys`  WHERE (`private_keys`.deleted_at IS NULL OR `private_keys`.deleted_at <= '0001-01-02') AND ((role = 'timestamp' AND gun = 'localhost:5000/ironnet-base' AND algorithm = 'ecdsa' AND last_used IS NULL)) ORDER BY key_id,`private_keys`.`id` ASC LIMIT 1
{"go.version":"go1.7.3","level":"info","msg":"CreateKey: Created KeyID 2315c1d6bae1a99988ef19e0b13801f543fe81b6b5f442b675ab7e7bef23a9b6","time":"2017-03-14T18:05:41Z"}

(/go/src/github.com/docker/notary/signer/keydbstore/sql_keydbstore.go:113)
[2017-03-14 18:05:41]  [0.82ms]  SELECT  * FROM `private_keys`  WHERE (`private_keys`.deleted_at IS NULL OR `private_keys`.deleted_at <= '0001-01-02') AND ((`key_id` = 'ee3b8956cf5c4a7ad24516ebf675687eb533d8ba92fa65f84d037cf7fbc88202')) ORDER BY `private_keys`.`id` ASC LIMIT 1

(/go/src/github.com/docker/notary/signer/keydbstore/sql_keydbstore.go:113)
[2017-03-14 18:05:41]  [0.58ms]  SELECT  * FROM `private_keys`  WHERE (`private_keys`.deleted_at IS NULL OR `private_keys`.deleted_at <= '0001-01-02') AND ((`key_id` = 'ee3b8956cf5c4a7ad24516ebf675687eb533d8ba92fa65f84d037cf7fbc88202')) ORDER BY `private_keys`.`id` ASC LIMIT 1
{"go.version":"go1.7.3","level":"error","msg":"GetKeyInfo: key ee3b8956cf5c4a7ad24516ebf675687eb533d8ba92fa65f84d037cf7fbc88202 not found","time":"2017-03-14T18:05:41Z"}
```

**Comment by ecordell** [comment]
> I'm using my own docker-compose file which has explicitly excluded host mount points. I didn't think that a VOLUME "/var/lib/mysql" in a Dockerfile allows for persistence after containers have been stopped and removed.

That's what the [VOLUME command](https://docs.docker.com/engine/reference/builder/#volume) will do - it will mount in that path from the host, and writes inside the container will be persisted to that folder in the host. In a docker-compose yaml, you can *add* additional volume mounts but AFAIK you can not affect the volumes mounted by the Dockerfile itself.

If you're not running any other important mysql things in containers or on your host, you could try `rm -rf /var/lib/mysql` to see if that works.

I ran the db tests against `mysql:8.0.0` and they fail - you may be able to get this to work by switching to `mariadb:10.1.10`. I think you've run into a bug with the sql compatibility.

**Comment by etotheipi** [comment]
I have only tested up to this one command that was failing before, and it is succeeding now using `mariadb:10.1.10` as you recommended.  I have not tried any other steps yet.  If it's not clear (and I wasn't just being a flake), it should be made clear in the documentation that _literally_ `mysql` is not compatible with signer & server.  I picked it only because I saw `mysql` in one of the docs and ran with it thinking there shouldn't be a real difference.

```
$ notary -s https://localhost:4443 -d ~/.docker/trust --tlscacert=ca/ca.crt init localhost:5000/my-image -p
No root keys found. Generating a new root key...
...
Auto-publishing changes to localhost:5000/my-image
Successfully published changes for repository localhost:5000/my-image
```

**RE persistence:**  As for the persistence, I did a quick test to confirm my previous understanding that `VOLUME` directives in Dockerfiles do not persist beyond the lifetime of the container.   They only allow that volume to escape the copy-on-write filesystem and not be tracked as part of the top working layer.  You can build and run multiple times the following Dockerfile to confirm:

```
FROM centos:7
VOLUME /home
CMD ls -la /home && echo hello > /home/abc.txt && ls -la /home
```

This makes sense to me because containers should be truly contained unless the user running the container explicitly says otherwise.

Thanks for the help, and hopefully this will help improve the documentation.  I'll close this and reopen a new ticket if I run into other issues.
