### ISSUE TITLE
Documentation: unclear how verification is happening

### ISSUE THREAD

**Issue by artsf** [docker/notary#1132]
There is a lack of documentation (section) which describes in details how signature verification is happening and where.

It, probably, should mention:

1. Metadata containing signature and public key of signing file;
2. Initial verification happening in Notary;
3. If verification in notary doesn't succeed then image is NOT loaded;
4. If initial verification succeeds then the image is loaded and verified against SHA. 

It is also unclear if there is a second-time verification of target machine to verify signature again in addition to SHA on the image.

**Comment by endophage** [comment]
Hi and thanks for the feedback. As this is specifically related to the integration of Notary in to Docker as "Docker Content Trust", could you please re-file this issue on the [docker documentation ](https://github.com/docker/docker.github.io) and close this issue. This is not actionable within this repository.

**Comment by artsf** [comment]
Moved.
