### ISSUE TITLE
Using cached metadata should not be a silent error

### ISSUE THREAD

**Issue by ecordell** [docker/notary#1162]
The notary client being unable to update and re-using cached local metadata instead should not be a silent warning that's only visible with debug logging:

```
WARN[0002] Error while downloading remote metadata, using cached timestamp - this might not be the latest version available remotely
```

Depending on what you're doing it may be okay to use the cached metadata, but it probably shouldn't be silent.

**Comment by riyazdf** [comment]
Agreed - I think the default logging level is [fatal](https://github.com/docker/notary/blob/master/cmd/notary/main.go#L253).

Generally I'm of the opinion that maybe we should lower notary's default log level to warning or error and adjust the verbose/debug flags appropriately?  It could also be a print, which would be a simpler fix though there could be other cases like this one that we want to bubble up.
