### ISSUE TITLE
Clarification regarding encoding of hashes in snapshot.json

### ISSUE THREAD

**Issue by dingwilson** [docker/notary#1165]
What is the encoding of the hashes in `snapshot.json`? Is it base64?

Below is part of a `snapshot.json` file I found in my `~/.docker/trust/tuf/<repository name>/metadata` folder. There are both `sha256` and `sha512` hashes, but both of them seem to be encoded weirdly. (I'm not sure why there are symbols in the hash) Thanks for your time!

```json
"root":{  
    "hashes":{  
        "sha256":"Sbf9VeehQnoD/f3t93iZKcPjtqJmX/+mlyaKKCVhe5U=",
        "sha512":"8BKcGteJMbt8waxu60croRDQw+Pd8yEeokDfjT53nHXHe+aeX7iznhv4+/WsbAEkYS/EHjf0mCw6NGTacesaWA=="
    },
    "length":2417
},
```

**Comment by riyazdf** [comment]
@dingwilson the hashes are represented by `[]byte` arrays in the go code.  We use the standard [`json.Marshal`](https://golang.org/pkg/encoding/json/#Marshal) which encodes `[]byte` as a base64-encoded string

I'll close this issue but please re-open or file a new issue if you have followup issues :)

**Comment by dingwilson** [comment]
Hey @riyazdf , I attempted to verify some of the SHAs manually, and was unable to do so. I tried converting them from `base64` -> `[]byte` -> `string`, but it seems that my string is gibberish. Am I doing something wrong?

```golang
  data, err := base64.StdEncoding.DecodeString(value) // decoding the sha

  if err != nil {
    	log.Fatal(err)
  }

  fmt.Println(data) // looks to be a []byte
  fmt.Println(string(data)) // should be a string, but is gibberish
```

**Comment by riyazdf** [comment]
@dingwilson: you'll need to hex encode the byte array to get the string you expect, see example: https://play.golang.org/p/nh_YsZjhEJ
