### ISSUE TITLE
Error establishing connection to trust repository

### ISSUE THREAD

**Issue by hridyeshpant** [docker/notary#1182]
followed following steps to setup notary : 
1) git clone https://github.com/docker/notary.git
2) cd notary
3) echo "127.0.0.1 notaryserver" >> /etc/hosts
4) cp fixtures/root-ca.crt  ~/.docker/tls/notaryserver:4443
5) cp fixtures/root-ca.crt /etc/pki/ca-trust/source/anchors/.
6) update-ca-trust extract
7) docker-compose up
8) export DOCKER_CONTENT_TRUST_SERVER=https://notaryserver:4443
9) export DOCKER_CONTENT_TRUST=1
10)  openssl s_client -connect notaryserver:4443 -CAfile fixtures/root-ca.crt -no_ssl3 -no_ssl2
giving correct output with "Verify return code: 0 (ok)"

but when i run docker build command, i am getting below error
```
Error establishing connection to trust repository: readdirent: not a directory
Sending build context to Docker daemon

An error occurred trying to connect: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.24/build?buildargs=%7B%7D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&rm=1&shmsize=0&ulimits=null: readdirent: not a directory
```
I have no idea which directory it is looking, Can someone please let me know what i am missing here?

**Comment by riyazdf** [comment]
hi @hridyeshpant: I've never seen this error before but it looks similar to this issue: https://github.com/moby/moby/issues/22592

Are you using a kernel version < 4.7?

**Comment by hridyeshpant** [comment]
no i am using Amazon linux and the version is 4.9. 
>>4.9.20-11.31.amzn1.x86_64

Also if i disable DOCKER_CONTENT_TRUST, i am able to build using same command.It seems i am missing some notary configuration but dont abel to understand below error and why this is happening 
```
Error establishing connection to trust repository: readdirent: not a directory
```

**Comment by hridyeshpant** [comment]
able to connect notaryserver
```curl  https://notaryserver:4443/v2/
{}
```
any help on solving below issue
```
Error establishing connection to trust repository: readdirent: not a directory
```

**Comment by riyazdf** [comment]
@hridyeshpant: could you please specify more information about the docker client version you're using along with the build command?

Also, are you using the default `--config` and if so, is `~/.docker/trust` a directory?

**Comment by hridyeshpant** [comment]
@riyazdf i am using below command to start notary under notary directory, so assuming this picking all default values
```
docker-compose up 
```
docker --version
Docker version 1.12.6, build 7392c3b/1.12.6

```
ls -ltr ~/.docker/
total 8
-rw------- 1 root root  113 Apr 26 08:03 config.json
drwxr-xr-x 2 root root 4096 Jun 12 05:58 tls
```

**Comment by judavi** [comment]
@hridyeshpant  what happen if you manually try to initialize a collection? same error? 
`$ notary init -p test.com`

**Comment by hridyeshpant** [comment]
@judavi i am running notary as docker containers (notary_server,notary_signer and mariadb:10.1.10  )  mentioned in https://docs.docker.com/notary/running_a_service/
```
docker ps
CONTAINER ID        IMAGE                                                                             COMMAND                  CREATED             STATUS              PORTS                                             NAMES
e239be273d85        notary_server                                                                     "/usr/bin/env sh -c '"   29 hours ago        Up 28 hours         0.0.0.0:4443->4443/tcp, 0.0.0.0:32793->8080/tcp   notary_server_1
623ff1fcb3d1        notary_signer                                                                     "/usr/bin/env sh -c '"   29 hours ago        Up 28 hours                                                           notary_signer_1
cd337f97d9cc        mariadb:10.1.10                                                                   "/docker-entrypoint.s"   4 days ago          Up 28 hours         3306/tcp                                          notary_mysql_1
```
You mean i need to compile the notary code and run notary init -p test.com command?

**Comment by judavi** [comment]
Well I just ask to check if the problem is with your Docker client or with the notary service itself. You don't need to compile just download the binary [https://github.com/docker/notary/releases](url) and use it 
`notary -s https://notaryserver:4443 -d ~/.docker/trust init -p test.com`

**Comment by hridyeshpant** [comment]
Thanks @judavi i will try with binary and let you know.

**Comment by hridyeshpant** [comment]
@judavi below is the output 
```
./notary-linux -s https://notaryserver:4443 -d ~/.docker/trust init -p test.com
No root keys found. Generating a new root key...
You are about to create a new root signing key passphrase. This passphrase
will be used to protect the most sensitive key in your signing system. Please
choose a long, complex passphrase and be careful to keep the password and the
key file itself secure and backed up. It is highly recommended that you use a
password manager to generate the passphrase and keep it safe. There will be no
way to recover this key. You can find the key in your config directory.
Enter passphrase for new root key with ID f8489f5:
Passphrase is too short. Please use a password manager to generate and store a good random passphrase.
Enter passphrase for new root key with ID f8489f5:
Repeat passphrase for new root key with ID f8489f5:
Enter passphrase for new targets key with ID b6c3abf (test.com):
Repeat passphrase for new targets key with ID b6c3abf (test.com):
Enter passphrase for new snapshot key with ID d46c810 (test.com):
Repeat passphrase for new snapshot key with ID d46c810 (test.com):

* fatal: timestamp key trust data unavailable.  Has a notary repository been initialized?
```

**Comment by judavi** [comment]
@hridyeshpant sorry I miss something
`notary -s https://notaryserver:4443 -d ~/.docker/trust init -p test.com/collection`

**Comment by hridyeshpant** [comment]
@judavi Thanks. one more quest 
test.com/collection will be my Trusted registry path ?
We are using our own docker trusted registry, so test.com/collection will be my Trusted registry path ? or i can use test.com/collection URL for testing.

**Comment by judavi** [comment]
no is just a test for initialize a collection use wherever you want. (https://github.com/docker/notary/blob/master/docs/advanced_usage.md)

**Comment by judavi** [comment]
In this case we don't want to hit a registry, just create a collection (to see if something with your notary service or if is your notary client)

**Comment by hridyeshpant** [comment]
@judavi  same issue 
```
./notary-linux -s https://notaryserver:4443 -d ~/.docker/trust init -p test.com/collection
Root key found, using: e5555d511b846b4256ca18a6d4cb162228b8c86f8a26a7c376857d60966eab43
Enter passphrase for root key with ID e5555d5:
Enter passphrase for new targets key with ID a6697fa (test.com/collection):
Repeat passphrase for new targets key with ID a6697fa (test.com/collection):
Enter passphrase for new snapshot key with ID 99488de (test.com/collection):
Repeat passphrase for new snapshot key with ID 99488de (test.com/collection):

* fatal: timestamp key trust data unavailable.  Has a notary repository been initialized?
```

**Comment by judavi** [comment]
@hridyeshpant one more try but with:
`notary init test.com/collection`
and then 
`$ notary publish  test.com/collection`

**Comment by hridyeshpant** [comment]
same
1.
```
./notary-linux init test.com/collection
Root key found, using: 7ab41ef1fed3d4882b115d875667e9100ae68286c8fd264d2e90d51a401d46ad
Enter passphrase for root key with ID 7ab41ef:
Enter passphrase for new targets key with ID 9576cab (test.com/collection):
Repeat passphrase for new targets key with ID 9576cab (test.com/collection):
Enter passphrase for new snapshot key with ID 4f67883 (test.com/collection):
Repeat passphrase for new snapshot key with ID 4f67883 (test.com/collection):

* fatal: timestamp key trust data unavailable.  Has a notary repository been initialized?
```
2. 
```
/notary-linux publish test.com/collection
Pushing changes to test.com/collection

* fatal: repository has not been initialized
```

**Comment by judavi** [comment]
Use the complete command 
`notary -s https://notaryserver:4443 -d ~/.docker/trust init test.com/collection `
`notary -s https://notaryserver:4443 -d ~/.docker/trust publish test.com/collection`

**Comment by riyazdf** [comment]
@hridyeshpant: if you suspect you have unwanted data locally and on your server, you can delete the data with this command.  I would recommend doing this before trying @judavi's commands:

`notary -s https://notaryserver:4443 -d ~/.docker/trust delete test.com/collection --remote`

**Comment by endophage** [comment]
I think this `cp fixtures/root-ca.crt ~/.docker/tls/notaryserver:4443` might also be an issue (especially given the error). If my memory serves, `notaryserver:4443` need to be a directory, so that command should really be:

```
$> mkdir ~/.docker/tls/notaryserver:4443
$> cp fixtures/root-ca.crt ~/.docker/tls/notaryserver:4443/ca.crt
```

**Comment by endophage** [comment]
Assuming this was resolved. Please re-open if not.
