### ISSUE TITLE
Notary should fail when being run in a script and no credentials provided

### ISSUE THREAD

**Issue by dave-tucker** [docker/notary#1184]
I'd like to use `notary` in a `Makefile` to check that an specific org/image:tag is signed.
There are cases where the image may not have yet been pushed and in these cases I would expect `notary` to `exit 1` so I can push/sign the image in question.

For example, in LinuxKit, if a contributor where to add a new package called "foo", our `Makefile` would check:
```
notary -s https://notary.docker.io lookup docker.io/linuxkit/foo $(HASH)
```
but `linuxkit/foo` would not yet exist.

This appeared to hang forever, but when I ran the command manually I saw that `notary` was prompting for a `Username:` and `Password:`. My expection would be that if no credentials were provided then this command should fail.

/cc @riyazdf

**Comment by riyazdf** [comment]
closed by #1200
