### ISSUE TITLE
What is the best location for setup the ENV variable CONTENT_TRUST

### ISSUE THREAD

**Issue by judavi** [docker/notary#1188]
Hello! I'm wondering what is the best location for setup for all users/services the environment variable CONTENT_TRUST. I have some candidates but I would appreciate your suggestions:

- On sysconfig/docker
- On /etc/systemd/system/docker.service.d/
- On /etc/enviroment 

Thanks!

**Comment by riyazdf** [comment]
@judavi: admittedly I mostly use OSX to develop so I don't have a preference between those three - from my understanding, they all should work fine :)

**Comment by judavi** [comment]
Great thanks @riyazdf
