### ISSUE TITLE
minVersion in verifyVersion()

### ISSUE THREAD

**Issue by DanBarychev** [docker/notary#1193]
In [verifyVersion()](https://github.com/docker/notary/blob/master/tuf/signed/verify.go#L37-L42), `minVersion` is used to make sure that the version of the metadata being verified is larger. I noticed that when loading a particular piece of metadata (timestamp, snapshot, etc.), [tryLoadCacheThenRemote()](https://github.com/docker/notary/blob/bdf934353d4dc5117d1d800d71ded2a34ebdfd6e/client/tufclient.go#L287-L301) will pass in 1 for `minVersion` if it is able to load that piece of metadata locally. However, in [tryLoadRemote()](https://github.com/docker/notary/blob/bdf934353d4dc5117d1d800d71ded2a34ebdfd6e/client/tufclient.go#L303-L325), to my understanding, we get the `minVersion` from `oldBuilder.getLoadedVersion()` when trying to "load the old data into the old builder" and then pass that `minVersion` into `newBuilder.Load()`. I was just wondering if I can get some clarification of the way the builders work here. Is the above process simply checking that the version we get for metadata remotely isn't less than the version we had for that piece of metadata the last time we loaded it or is there something else going on?

**Comment by endophage** [comment]
> Is the above process simply checking that the version we get for metadata remotely isn't less than the version we had for that piece of metadata the last time we loaded it or is there something else going on?

Nothing else going on. It's part of the TUF spec that version numbers must increase. I believe we're slightly behind in implementing some spec updates though. I think the versions numbers are meant to reset for a given role when there is any change in its signing keys.

**Comment by DanBarychev** [comment]
@endophage Ok, thank you!

**Comment by endophage** [comment]
No worries. We have a plan for removing the builder code and greatly simplifying all the repository verification coded, we just have to find time to do it.
