### ISSUE TITLE
'docker-compose build' failed: ERROR: Service 'signer' failed to build: error creating overlay mount to /var/lib/docker/overlay2

### ISSUE THREAD

**Issue by chunglam1999** [docker/notary#1208]
NOTARY_VERSION: 0.5.0
[root@dell-desktop notary]# docker-compose version
docker-compose version 1.13.0, build 1719ceb
docker-py version: 2.2.1
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
root@dell-desktop notary]# docker-compose build
mysql uses an image, skipping
Building signer
Step 1/14 : FROM golang:1.8.3-alpine
1.8.3-alpine: Pulling from library/golang
019300c8a437: Pull complete
ba570f08729a: Pull complete
65f959ba8ec2: Pull complete
43126a124ea6: Pull complete
70c83f72e91e: Pull complete
edfbbcd5d91d: Pull complete
Digest: sha256:4a2e35d9f8259a33a2c7574ab2be062d793f2526ff65391b7e7b6f4677901b3f
Status: Downloaded newer image for golang:1.8.3-alpine
 ---> 310e63753884
Step 2/14 : MAINTAINER David Lawrence "david.lawrence@docker.com"
ERROR: Service 'signer' failed to build: error creating overlay mount to /var/lib/docker/overlay2/755d4153a948c10b287b59cbc4c2d443e6cb9db29a5075d65ca4ff52298518ba-init/merged: invalid argument

**Comment by riyazdf** [comment]
@chunglam1999: thanks for the report, though I'm unable to reproduce this issue.

I'm using:
```
🐳 $ docker-compose version
docker-compose version 1.14.0, build c7bdf9e
docker-py version: 2.3.0
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
```

Which version of Docker are you using?  And what OS?

**Comment by chunglam1999** [comment]
I reinstalled the centos 7 and the docker-engine 17.05 on the laptop and it was working fine. Thanks for reply.
