### ISSUE TITLE
notaryserver and signer cant connect to mysql (3306)

### ISSUE THREAD

**Issue by chunglam1999** [docker/notary#1209]
when I start the notary 'docker-compose up', the notaryserver and signer cant connect to the mysql port 3306.
signer_1  | error: Error 1045: Access denied for user 'signer'@'172.18.0.3' (using password: NO)
signer_1  | waiting for mysql://signer@tcp(mysql:3306)/notarysigner to come up.
server_1  | error: Error 1045: Access denied for user 'server'@'172.18.0.4' (using password: NO)
server_1  | waiting for mysql://server@tcp(mysql:3306)/notaryserver to come up.
signer_1  | error: Error 1045: Access denied for user 'signer'@'172.18.0.3' (using password: NO)
signer_1  | notarysigner database failed to come up within 30 seconds
notary_signer_1 exited with code 1
server_1  | error: Error 1045: Access denied for user 'server'@'172.18.0.4' (using password: NO)
server_1  | notaryserver database failed to come up within 30 seconds
notary_server_1 exited with code 1

The mysql is running:
root@localhost ~]# docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
4c48bc79254f        mariadb:10.1.10     "/docker-entrypoin..."   32 minutes ago      Up 14 minutes       3306/tcp            notary_mysql_1

**Comment by chunglam1999** [comment]
the notaryserver and notarysigner database are not created:
[root@localhost notary]# docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                                             NAMES
21d62f3d71ec        notary_server       "/usr/bin/env sh -..."   27 minutes ago      Up 2 minutes        0.0.0.0:4443->4443/tcp, 0.0.0.0:32795->8080/tcp   notary_server_1
636843d85a17        notary_signer       "/usr/bin/env sh -..."   27 minutes ago      Up 2 minutes                                                          notary_signer_1
cd2256141fed        mariadb:10.1.10     "/docker-entrypoin..."   27 minutes ago      Up 2 minutes        3306/tcp                                          notary_mysql_1
[root@localhost notary]# docker exec -it cd2256141fed sh
# mysql -u root notaryserver
ERROR 1049 (42000): Unknown database 'notaryserver'
# mysql -u root notarysigner
ERROR 1049 (42000): Unknown database 'notarysigner'
#

**Comment by cyli** [comment]
@chunglam1999 It looks like the grants for the server and signer users had some issue?  The server and signer can't seem to connect with their respective users:

```
signer_1 | error: Error 1045: Access denied for user 'signer'@'172.18.0.3' (using password: NO)
```

Are there logs from further back that indicate an error setting up the grants?

**Comment by chunglam1999** [comment]
I added the parameter (--skip-grant-tables) on  the docker-compose.yml:
command: mysqld --innodb_file_per_table --skip-grant-tables
 #command: mysqld --innodb_file_per_table
The error log of Notary became:
signer_1  | waiting for tlam2 mysql://signer@tcp(mysql:3306)/notarysigner to come up.
server_1  | error: Error 1049: Unknown database 'notaryserver'
server_1  | waiting tlam1 for mysql://server@tcp(mysql:3306)/notaryserver to come up.
signer_1  | error: Error 1049: Unknown database 'notarysigner'

So I think the issue is the notaryserver and notarysigner did not come up and the there were no error log why the database cant come up

**Comment by cyli** [comment]
@chunglam1999 Just for sanity, did you `docker-compose down -v` and then `docker-compose up` again?  If not, it's possible the volume was preserved from your last `docker-compose up` and the script wouldn't have set up the databases.

**Comment by chunglam1999** [comment]
it works after after  'docker-compose down -v' and then 'docker-compose up'. Thanks  a lots.

**Comment by symgryph** [comment]
I did these things, and still get the same error.

**Comment by naman** [comment]
Just to bump on the issue since it has been more than 3 months since the last comment. Just like @symgryph mentioned, I'm facing the issue too. Any pointers on how to debug will be greatly appreciated. Thanks 👍

**Comment by radu-matei** [comment]
This could also happen when the Docker host cannot correctly mount the volumes defined in `docker-compose.yml`.

**Comment by vamsidvk09** [comment]
Even I'm facing the same issue . Any help is appreciated
