### ISSUE TITLE
Update TOML library dependency

### ISSUE THREAD

**Issue by caniszczyk** [docker/notary#1210]
Can you update your TOML dependency to use an update one with a proper OSI approved license?

https://github.com/chanezon/toml#about-this-fork

This will be a requirement to join CNCF. The containerd project had to do this also.

**Comment by endophage** [comment]
@caniszczyk it looks like BurntSushi/toml relicensed under MIT in June. Does MIT allow us to continue to maintain a fork with a different license? We're going to have a bad time in the long term if we can't update dependencies due to licensing issues.

**Comment by caniszczyk** [comment]
@endophage just move to the updated version of BurntSushi/toml that's under MIT now and you'll be good to go, no need to depend on Patrick's fork.

**Comment by endophage** [comment]
Awesome!
