### ISSUE TITLE
"docker push" error 

### ISSUE THREAD

**Issue by chunglam1999** [docker/notary#1235]
I have the following setup:
1. docker registry: 192.168.1.7:5000
2. notary: 192.168.1..6:4443
3. On Notary client:
export DOCKER_CONTENT_TRUST=1
export DOCKER_CONTENT_TRUST_SERVER=https://192.168.1.6:4443

"notary -D init -s https://192.168.1.6:4443 192.168.1.7:5000/tlam-f2", "docker push" failed:
DEBU[0000] Client Update (Root):root trust data unavailable. Has a notary repository been initialized?
Error: trust data missing for remote repository 192.168.1.7:5000/tlam-f2 or remote repository not found: root trust data unavailable. Has a notary repository been initialized?
while "notary -D init -s https://192.168.1.6:4443 192.168.1.7:5000/tlam-f2:v1" "docker push" is working.

Detail Debug trace:
I .Error case:
>notary -D init -s https://192.168.1.6:4443 192.168.1.7:5000/tlam-f2
>docker tag hello-world 192.168.1.7:5000/tlam-f2:v1
>docker -D push 192.168.1.7:5000.tlam-f2:v1
The push refers to a repository [192.168.1.7:5000/tlam-f2]
98c944e98de8: Layer already exists
v1: digest: sha256:2075ac87b043415d35bb6351b4a59df19b8ad154e578f7048335feeb02d0f759 size: 524
Signing and pushing trust metadata
DEBU[0000] reading certificate directory: /root/.docker/tls/192.168.1.6:4443
DEBU[0000] crt: /root/.docker/tls/192.168.1.6:4443/root-ca.crt
DEBU[0000] No yubikey found, using alternative key storage: no library found
DEBU[0000] entered ValidateRoot with dns: 192.168.1.7:5000/tlam-f2
DEBU[0000] found the following root keys: [06feb02813e4c6a64da1608b86b90363b29b64f64eb3d3f4cc88388df73330cc]
DEBU[0000] found 1 valid leaf certificates for 192.168.1.7:5000/tlam-f2: 06feb02813e4c6a64da1608b86b90363b29b64f64eb3d3f4cc88388df73330cc
DEBU[0000] found 1 leaf certs, of which 1 are valid leaf certs for 192.168.1.7:5000/tlam-f2
DEBU[0000] checking root against trust_pinning config%!(EXTRA string=192.168.1.7:5000/tlam-f2)
DEBU[0000] checking trust-pinning for cert: 06feb02813e4c6a64da1608b86b90363b29b64f64eb3d3f4cc88388df73330cc
DEBU[0000]  role has key IDs: 06feb02813e4c6a64da1608b86b90363b29b64f64eb3d3f4cc88388df73330cc
DEBU[0000] verifying signature for key ID: 06feb02813e4c6a64da1608b86b90363b29b64f64eb3d3f4cc88388df73330cc
DEBU[0000] root validation succeeded for 192.168.1.7:5000/tlam-f2
DEBU[0000] entered ValidateRoot with dns: 192.168.1.7:5000/tlam-f2
DEBU[0000] found the following root keys: [06feb02813e4c6a64da1608b86b90363b29b64f64eb3d3f4cc88388df73330cc]
DEBU[0000] found 1 valid leaf certificates for 192.168.1.7:5000/tlam-f2: 06feb02813e4c6a64da1608b86b90363b29b64f64eb3d3f4cc88388df73330cc
DEBU[0000] found 1 leaf certs, of which 1 are valid leaf certs for 192.168.1.7:5000/tlam-f2
DEBU[0000] checking root against trust_pinning config%!(EXTRA string=192.168.1.7:5000/tlam-f2)
DEBU[0000] checking trust-pinning for cert: 06feb02813e4c6a64da1608b86b90363b29b64f64eb3d3f4cc88388df73330cc
DEBU[0000]  role has key IDs: 06feb02813e4c6a64da1608b86b90363b29b64f64eb3d3f4cc88388df73330cc
DEBU[0000] verifying signature for key ID: 06feb02813e4c6a64da1608b86b90363b29b64f64eb3d3f4cc88388df73330cc
DEBU[0000] root validation succeeded for 192.168.1.7:5000/tlam-f2
DEBU[0000] updating TUF client
DEBU[0000] Loading timestamp...
DEBU[0000] received HTTP status 404 when requesting timestamp.
DEBU[0000] error downloading timestamp: timestamp trust data unavailable.  Has a notary repository been initialized?
DEBU[0000] no cached or remote timestamp available
DEBU[0000] Client Update (Timestamp): timestamp trust data unavailable.  Has a notary repository been initialized?
DEBU[0000] Error occurred. Root will be downloaded and another update attempted
DEBU[0000] Resetting the TUF builder...
DEBU[0000] Loading root with no expected checksum
DEBU[0000] received HTTP status 404 when requesting root.
DEBU[0000] error downloading root: root trust data unavailable.  Has a notary repository been initialized?
DEBU[0000] Client Update (Root):root trust data unavailable.  Has a notary repository been initialized?
Error: trust data missing for remote repository 192.168.1.7:5000/tlam-f2 or remote repository not found: root trust data unavailable.  Has a notary repository been initialized?

II Working case
>notary -D init -s https://192.168.1.6:4443 192.168.1.7:5000/tlam-f3:v1
>docker tag hello-world 192.168.1.7:5000/tlam-f3:v1
>docker -D push 192.168.1.7:5000.tlam-f3:v1
[root@cn-ovm3 ~]# docker -D push  192.168.1.7:5000/tlam-f3:v1
The push refers to a repository [192.168.1.7:5000/tlam-f3]
98c944e98de8: Mounted from tlam-f2
v1: digest: sha256:2075ac87b043415d35bb6351b4a59df19b8ad154e578f7048335feeb02d0f759 size: 524
Signing and pushing trust metadata
DEBU[0000] reading certificate directory: /root/.docker/tls/192.168.1.6:4443
DEBU[0000] crt: /root/.docker/tls/192.168.1.6:4443/root-ca.crt
DEBU[0001] No yubikey found, using alternative key storage: no library found
DEBU[0001] received HTTP status 404 when requesting root.
DEBU[0001] No yubikey found, using alternative key storage: no library found
DEBU[0001] No yubikey found, using alternative key storage: no library found
Enter passphrase for root key with ID 2e5a16d:
DEBU[0006] generated ECDSA key with keyID: fee8f2dbc82fd10116ea9ef1fc4e6813beed600d6781039af7a9ebea3150c9e2
DEBU[0006] generated new ecdsa key for role: targets and keyID: fee8f2dbc82fd10116ea9ef1fc4e6813beed600d6781039af7a9ebea3150c9e2
Enter passphrase for new repository key with ID fee8f2d (192.168.1.7:5000/tlam-f3):
Repeat passphrase for new repository key with ID fee8f2d (192.168.1.7:5000/tlam-f3):
DEBU[0013] got remote timestamp ecdsa key with keyID: a6cc1a7c65f9cd414b068bfdfe55084f845ddab6687490d154805ac86942fae1
DEBU[0013] got remote snapshot ecdsa key with keyID: c9db7433887e350d465a597cd1ce355c8ba12a6913bd48cf37b3c952e386b4ed
DEBU[0013] generating new snapshot...
DEBU[0013] Saving changes to Trusted Collection.
DEBU[0013] signing root...
DEBU[0013] sign called with 1/1 required keys
DEBU[0013] No yubikey found, using alternative key storage: no library found
DEBU[0013] sign called with 0/0 required keys
DEBU[0013] sign targets called for role targets
DEBU[0013] sign called with 1/1 required keys
DEBU[0013] No yubikey found, using alternative key storage: no library found
DEBU[0013] sign called with 0/0 required keys
Finished initializing "192.168.1.7:5000/tlam-f3"
DEBU[0013] Making dir path: /root/.docker/trust/tuf/192.168.1.7:5000/tlam-f3/changelist
DEBU[0013] Adding target "v1" with sha256 "2075ac87b043415d35bb6351b4a59df19b8ad154e578f7048335feeb02d0f759" and size 524 bytes.

DEBU[0013] Making dir path: /root/.docker/trust/tuf/192.168.1.7:5000/tlam-f3/changelist
DEBU[0013] entered ValidateRoot with dns: 192.168.1.7:5000/tlam-f3
DEBU[0013] found the following root keys: [3580f08d9003a4c5a30152e812f192223fd98e9b07c1f025aca3003ea9450f05]
DEBU[0013] found 1 valid leaf certificates for 192.168.1.7:5000/tlam-f3: 3580f08d9003a4c5a30152e812f192223fd98e9b07c1f025aca3003ea9450f05
DEBU[0013] found 1 leaf certs, of which 1 are valid leaf certs for 192.168.1.7:5000/tlam-f3
DEBU[0013] checking root against trust_pinning config%!(EXTRA string=192.168.1.7:5000/tlam-f3)
DEBU[0013] checking trust-pinning for cert: 3580f08d9003a4c5a30152e812f192223fd98e9b07c1f025aca3003ea9450f05
DEBU[0013]  role has key IDs: 3580f08d9003a4c5a30152e812f192223fd98e9b07c1f025aca3003ea9450f05
DEBU[0013] verifying signature for key ID: 3580f08d9003a4c5a30152e812f192223fd98e9b07c1f025aca3003ea9450f05
DEBU[0013] root validation succeeded for 192.168.1.7:5000/tlam-f3
DEBU[0013] entered ValidateRoot with dns: 192.168.1.7:5000/tlam-f3
DEBU[0013] found the following root keys: [3580f08d9003a4c5a30152e812f192223fd98e9b07c1f025aca3003ea9450f05]
DEBU[0013] found 1 valid leaf certificates for 192.168.1.7:5000/tlam-f3: 3580f08d9003a4c5a30152e812f192223fd98e9b07c1f025aca3003ea9450f05
DEBU[0013] found 1 leaf certs, of which 1 are valid leaf certs for 192.168.1.7:5000/tlam-f3
DEBU[0013] checking root against trust_pinning config%!(EXTRA string=192.168.1.7:5000/tlam-f3)
DEBU[0013] checking trust-pinning for cert: 3580f08d9003a4c5a30152e812f192223fd98e9b07c1f025aca3003ea9450f05
DEBU[0013]  role has key IDs: 3580f08d9003a4c5a30152e812f192223fd98e9b07c1f025aca3003ea9450f05
DEBU[0013] verifying signature for key ID: 3580f08d9003a4c5a30152e812f192223fd98e9b07c1f025aca3003ea9450f05
DEBU[0013] root validation succeeded for 192.168.1.7:5000/tlam-f3
DEBU[0013] received HTTP status 404 when requesting root.
DEBU[0013] Loading trusted collection.
DEBU[0013] entered ValidateRoot with dns: 192.168.1.7:5000/tlam-f3
DEBU[0013] found the following root keys: [3580f08d9003a4c5a30152e812f192223fd98e9b07c1f025aca3003ea9450f05]
DEBU[0013] found 1 valid leaf certificates for 192.168.1.7:5000/tlam-f3: 3580f08d9003a4c5a30152e812f192223fd98e9b07c1f025aca3003ea9450f05
DEBU[0013] found 1 leaf certs, of which 1 are valid leaf certs for 192.168.1.7:5000/tlam-f3
DEBU[0013] checking root against trust_pinning config%!(EXTRA string=192.168.1.7:5000/tlam-f3)
DEBU[0013] checking trust-pinning for cert: 3580f08d9003a4c5a30152e812f192223fd98e9b07c1f025aca3003ea9450f05
DEBU[0013]  role has key IDs: 3580f08d9003a4c5a30152e812f192223fd98e9b07c1f025aca3003ea9450f05
DEBU[0013] verifying signature for key ID: 3580f08d9003a4c5a30152e812f192223fd98e9b07c1f025aca3003ea9450f05
DEBU[0013] root validation succeeded for 192.168.1.7:5000/tlam-f3
DEBU[0013] targets role has key IDs: fee8f2dbc82fd10116ea9ef1fc4e6813beed600d6781039af7a9ebea3150c9e2
DEBU[0013] verifying signature for key ID: fee8f2dbc82fd10116ea9ef1fc4e6813beed600d6781039af7a9ebea3150c9e2
DEBU[0013] changelist add: v1
DEBU[0013] No yubikey found, using alternative key storage: no library found
DEBU[0013] applied 1 change(s)
DEBU[0013] sign targets called for role targets
DEBU[0013] sign called with 1/1 required keys
DEBU[0013] No yubikey found, using alternative key storage: no library found
DEBU[0013] sign called with 0/0 required keys
DEBU[0013] generating new snapshot...
DEBU[0013] signing snapshot...
DEBU[0013] sign called with 1/1 required keys
DEBU[0013] No yubikey found, using alternative key storage: no library found
DEBU[0013] Client does not have the key to sign snapshot. Assuming that server should sign the snapshot.
Successfully signed "192.168.1.7:5000/tlam-f3":v1

**Comment by riyazdf** [comment]
@chunglam1999: can you try inserting a `notary publish` after your `init` command or running it with a `-p` flag?  `notary init` does not publish the repo initialization to the server by default.

**Comment by chunglam1999** [comment]
It work. Thx
