### ISSUE TITLE
Notary server documentation

### ISSUE THREAD

**Issue by dmp42** [docker/notary#140]

**Comment by jesseendahl** [comment]
@diogomonica is this coming soon?

**Comment by diogomonica** [comment]
@jesseendahl still working on blogposts/docs for Docker Content Trust. We will give the 1.0 notary release/docs a lot more love after linuxcon.

**Comment by jesstm** [comment]
@diogomonica awesome

**Comment by jesseendahl** [comment]
@diogomonica awesome

**Comment by jesseendahl** [comment]
Is this still in the works? Do you guys have an updated ETA on when docs will be ready?

**Comment by jesseendahl** [comment]
Ping

**Comment by diogomonica** [comment]
@jesseendahl the README is better now. You can start playing with it (we just added support for targets and snapshots key rotation).

**Comment by jesseendahl** [comment]
Awesome news. I'll check out the updated README. Thanks!
