### ISSUE TITLE
Error when using docker-compose server

### ISSUE THREAD

**Issue by progrium** [docker/notary#19]
I did the `docker-compose build` and `docker-compose up`, then I pointed `notary` name to my boot2docker IP, then I tried publishing a collection I made with the notary client. The client seems to be ok, but the server spit this out:
```
notary_1      | time="2015-06-23T18:17:59Z" level=error msg="[Notary Server] 9999: Error 1054: Unknown column 'gun' in 'where clause'" 
notary_1      | time="2015-06-23T18:17:59Z" level=error msg="[Notary Server] 9999: Error 1054: Unknown column 'gun' in 'where clause'" 
notary_1      | time="2015-06-23T18:17:59Z" level=error msg="[Notary Server] 9999: Error 1054: Unknown column 'gun' in 'where clause'" 
notary_1      | time="2015-06-23T18:17:59Z" level=error msg="[Notary Server] 9999: Error 1054: Unknown column 'gun' in 'where clause'" 
```
Notary client says it published, but then `notary list progrium.com/test` returns nothing.

**Comment by endophage** [comment]
Apologies, that was my error. We've been slowly updating some of the names. I updated the code that interacts with mysql and completely forgot to update the database bootstrap compose uses. It should be fixed now but I won't be able to confirm for certain until I get back to my work laptop in the morning.

**Comment by endophage** [comment]
It was bugging me so I set up docker and compose on the computer I was on. Confirmed fixed. Hopefully having opened up the repo, additional eyes on PRs will help us avoid these types of bugs.

**Comment by progrium** [comment]
Thanks!
