### ISSUE TITLE
Add health check to notary server

### ISSUE THREAD

**Issue by endophage** [docker/notary#190]
Use the distribution health check package to add health checks to notary server

**Comment by avinson** [comment]
when implementing this, we also need a way to do health checks against the main port and not the debug port. there was recently a distribution PR that got merged for this: https://github.com/docker/distribution/pull/874

**Comment by endophage** [comment]
Not the best place for this but a few things I'd love to see changed in the distribution health check package:

1. Always return all the service names with "OK" if there was no error. It's currently annoying to tell if all the service health checks have been registered correctly.
2. Periodic checks do not do an immediate check. You have to wait until the end of the first period until a check is done for the first time. With a periodic check it should immediately do the first check on registration.
