### ISSUE TITLE
docker-compose up fails with link error on docker-swarm (virtualbox) 

### ISSUE THREAD

**Issue by phiroict** [docker/notary#197]
From a fresh git clone --recursive 
running:
docker-compose up -d 

---

the docker-compose up fails with: 
Unable to find a node fulfilling all dependencies: --link=notary_notarymysql_1:notary_notarymysql_1 --link=notary_notarymysql_1:notarymysql --link=notary_notarymysql_1:notarymysql_1

---

Expected to see : Running notary docker stack on the docker-swarm

docker version
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.5.1
 Git commit:   0a8c2e3-dirty
 Built:        Mon Sep 14 12:09:36 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      swarm/0.4.0
 API version:  1.16
 Go version:   go1.4.2
 Git commit:   d647d82
 Built:  
 OS/Arch:      linux/amd64

---

docker-compose version
docker-compose version: 1.4.0
docker-py version: 1.3.1
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1e 11 Feb 2013

---

OS: Archlinux 
uname -a 

Linux **\* 4.1.6-1-ARCH #1 SMP PREEMPT Mon Aug 17 08:52:28 CEST 2015 x86_64 GNU/Linux

---

go version
go version go1.5.1 linux/amd64

**Comment by cyli** [comment]
Hi @phiroict!  Apologies we never managed to get to this.  There have been a lot of updates since and we use networks now instead of links in the compose file, so hopefully that may fix the issue?  Closing this for now, but please re-open if it's still a problem!

**Comment by solnet-phiro** [comment]
Current version works as required. Thanks!

**Comment by cyli** [comment]
@solnet-phiro Thank you so much for checking again!
