### ISSUE TITLE
Error establishing connection to trust repository

### ISSUE THREAD

**Issue by xiekeyang** [docker/notary#199]
I run notary server and use it for images signature, according to steps of [https://docs.docker.com/security/trust/trust_sandbox/](https://docs.docker.com/security/trust/trust_sandbox/)

But i meet some problem, as the below,

```bash
# docker pull sandboxregistry:5000/test/trusttest
Using default tag: latest
Error establishing connection to trust repository: Get https://notaryserver:4443/v2/: tls: oversized record received with length 20527
Get https://notaryserver:4443/v2/: tls: oversized record received with length 20527
```

Anyone meet the same problem? If cert of notaryserver is wrong?

thanks a lot!

**Comment by mtrmac** [comment]
I have seen something like this; you have a HTTP, not HTTPS, server running on notaryserver:4443.

I can’t try this out now, but IIRC the server’s config.json should include server.tls_{key,cert}_file; see dev-config.json for an example.

**Comment by xiekeyang** [comment]
@mtrmac  I'd try it. Thanks a lot!

**Comment by endophage** [comment]
@mtrmac has the correct advice, that error is seen when one attempts to connect to an HTTP notary server as the client enforces HTTPS (it's the only way to provide any semblance of safety when distributing TUF root files).
