### ISSUE TITLE
make fails with “Makefile:52: *** target pattern contains no '%'.  Stop.”

### ISSUE THREAD

**Issue by mtrmac** [docker/notary#213]
PR #207 adds rules like
```${GOPATH}/bin/notary-server: NOTARY_VERSION $(shell find . -type f -name '*.go')```
which break when GOPATH contains multiple :-separated entries with
```Makefile:52: *** target pattern contains no '%'.  Stop.```
(regardless of which target is used.)

I’m not entirely sure what a proper fix is at the moment, this is a tangle of several issues.

* https://golang.org/pkg/go/build/ suggests that $gopath_entry/bin should be only used for commands built from the corresponding $gopath_entry/src, which is not generally the case for a checkout of notary.
* This can be worked around by something like ```(unset GOPATH; make binaries)```, only using the Godeps-managed dependencies
* OTOH ```(make build)``` is still available, requires running setting GOPATH manually to point at Godeps, and the standard way to do that, ```GOPATH=`godep path`:$GOPATH```, causes a multi-entry GOPATH to be set.
* (make build) could arguably be dropped or reworked as (make binaries) has been, but this also breaks (go test), for the same reason.

AFAICT either all or none of the make rules should call ```godep```; and using ```${GOPATH}``` is wrong in any case.

(Filing at least a bug without a PR for now to hopefully save others the time figuring out the cause of the breakage.)

**Comment by vikstrous** [comment]
Sorry about that. I'll revert it for now until we have a better solution https://github.com/docker/notary/pull/214

**Comment by cyli** [comment]
Looks like this issue was resolved; closing.  Should we re-open #202? (putting the compiled binaries into `$GOPATH/bin`)
