### ISSUE TITLE
Allow notary-server and notary-signer to take a DEBUG environment variable

### ISSUE THREAD

**Issue by cyli** [docker/notary#227]
Since as per https://github.com/docker/notary/pull/219#discussion_r42290277, we are removing the `-debug` flag from the Dockerfiles

**Comment by endophage** [comment]
@cyli did this get done in your configuration cleanup?

**Comment by cyli** [comment]
@endophage Oops, sorry, not yet.  Sorry, I forgot about this one.  Will add now.

**Comment by cyli** [comment]
Added documentation for overriding the cmd here:  https://github.com/docker/notary/pull/291/files#diff-fe07e14e687d642a33501de7941c3074R116, so I think we can close this.
