### ISSUE TITLE
update jose2go dependency to prevent go build errors

### ISSUE THREAD

**Issue by Govinda-Fichtner** [docker/notary#239]
When building the Dockerfile from the https://github.com/docker/docker/blob/release/v1.9/Dockerfile#L143 on an ARM server, notary fails to build as described here: https://github.com/dvsekhvalnov/jose2go/issues/8

That's due to an issue in jose2go which has been fixed in the meantime.

Could you please update jose2go to the latest version?

Thanks.

PS: Do you have any clue why the notary version that is included in the Dockerfile https://github.com/docker/docker/blob/release/v1.9/Dockerfile#L143 is fixed to such an old commit?

**Comment by diogomonica** [comment]
should be done.
