### ISSUE TITLE
install mysql on ubuntu without password prompt

### ISSUE THREAD

**Issue by HuKeping** [docker/notary#266]
Hi there,

How did we achieve that install mysql-server on ubuntu:14.04 without password prompt.

I don't see any other operations but only `apt-get install -y mysql-server` in `./notarymysql/Dockerfile`.

When I use ubuntu:15.04 instead of 14.04 to be the base image, it ask me to init the password. Wonder how 14.04 not.

**Comment by diogomonica** [comment]
@HuKeping I'm confused about exactly what the issue is. Can you provide some more details?
