### ISSUE TITLE
Change error on 5XX to not be "no trust data available"

### ISSUE THREAD

**Issue by diogomonica** [docker/notary#277]
DEBU[0000] received HTTP status 503 when requesting root. 
* fatal: no trust data available

**Comment by cyli** [comment]
I tried running against a server that returns 503 for everything, I'm so far only getting:

```
ERRO[0000] Client Update (Timestamp): unexpected end of JSON input 
DEBU[0000] Error occurred. Root will be downloaded and another update attempted 
DEBU[0000] didn't find a cached root, must download     
DEBU[0000] received HTTP status 503 when requesting root. 
ERRO[0000] client Update (Root):Unable to reach trust server at this time: 503. 
* fatal: Unable to reach trust server at this time: 503.
```

With binaries built against master?

**Comment by cyli** [comment]
Oops, sorry, `init repo` and `publish repo` return the "Unable to reach trust server...".  `list repo` gives the no trust data available.
