### ISSUE TITLE
Look into adding a different mysql users for server/signer

### ISSUE THREAD

**Issue by cyli** [docker/notary#330]
So that they have different grants - server should not be able to access the private key table.

**Comment by endophage** [comment]
For the record: This has already been done for our production deployment. Before we every deployed I created separate users with restricted permissions and separate databases for the server and signer. It would certainly be good to mimic that setup in our compose environment to provide people with more accurate guidance in deploying their own instances.

**Comment by cyli** [comment]
Yep, sorry, I meant this as more of a documentation/recommendation thing.  E.g. our dockerfiles should probably just do the right thing off the bat.  :)
