### ISSUE TITLE
An obscure error omit

### ISSUE THREAD

**Issue by HuKeping** [docker/notary#336]
It seems the `err` will always `nil`

https://github.com/docker/notary/blob/master/cmd/notary-signer/main.go#L103-L107

since we ignore error message here

https://github.com/docker/notary/blob/master/signer/keydbstore/keydbstore.go#L53

**Comment by HuKeping** [comment]
Maybe one of them needs update

**Comment by cyli** [comment]
@HuKeping Good point, thank you!
