### ISSUE TITLE
Calculate coverage for untested/unused packages

### ISSUE THREAD

**Issue by cyli** [docker/notary#337]
If there is a file containing code that is not exercised at all, it seems like our coverage generation is just not producing any numbers for the file.  https://github.com/docker/notary/pull/332 introduced a new package with a single file (`server/snapshot/snapshot.go`) and it looks like [there was no code coverage for it](https://circleci.com/gh/docker/notary/989)  (see the `gvm use stable && make covmerge` section of circleci results).

**Comment by riyazdf** [comment]
Closing with the addition of https://github.com/docker/notary/blob/master/buildscripts/covertest.py
