### ISSUE TITLE
Provide endpoint to rotate server-managed keys

### ISSUE THREAD

**Issue by cyli** [docker/notary#347]
Such as snapshot and timestamp.  Not doing this means that if the user gives the command to rotate a key (particularly snapshot) and the key is already remotely stored, then no key rotation occurs.

This requires the user to sign the new `root.json`, so the server cannot just do this.

Proposal:

1. Remove unique gun/role constraint from server public keys table
1. Add column that specifies whether it's current or new
1. When user requests to rotate a timestamp for example, a new timestamp key is generated for the gun, but with `current=false`
1. Whenever a user requests to rotate the timestamp again, that same non-current timestamp key is returned.
1. Whenever a root.json is pushed, check whether we have the key in the DB for all keys.  If we do, and it's not current, promote it to current.  I think we can just then delete any key in the DB for the gun that is not in the root.json, so long as we are sure of all our server validations.

**Comment by riyazdf** [comment]
Closed with #889
