### ISSUE TITLE
Maybe TUF metadata filestore should ensure the directories of the file

### ISSUE THREAD

**Issue by cyli** [docker/notary#355]
E.g. it automatically creates all the parent directories it needs.

See https://github.com/docker/notary/pull/335#discussion_r47295933.

**Comment by cyli** [comment]
This causes delegations to behave badly, since we can't cache delegation metadata files.  I think it might be ok for reading/signing, just suboptimal.

**Comment by diogomonica** [comment]
@cyli maybe something like #377 ?

**Comment by cyli** [comment]
@diogomonica +1!
