### ISSUE TITLE
docker-compose build error

### ISSUE THREAD

**Issue by peconi** [docker/notary#364]
This must be something ridiculously simple, alas, it is not working for me.
Any suggestions greatly appreciated.

- OSX Yosemite: 10.10.5
- Docker version 1.9.1, build a34a1d5
- docker-compose version 1.5.2, build 7240ff3
- docker-machine version 0.5.2 ( 0456b9f )

`cd ~/.go/src/github.com/docker/notary`
`[-bash3.2-] -=> godep restore`

`[-bash3.2-] -=> make binaries`
pkcs11 import was not found anywhere without a build tag, yay

+ /Users/peconi/.go/src/github.com/docker/notary/bin/notary-server
+ /Users/peconi/.go/src/github.com/docker/notary/bin/notary
+ /Users/peconi/.go/src/github.com/docker/notary/bin/notary-signer
+ binaries

`[-bash3.2-] -=> docker-compose build`
**WARNING: The DOCKER_CLIENT_TIMEOUT environment variable is deprecated. Please use COMPOSE_HTTP_TIMEOUT instead.
Building notarymysql
ERROR: (NotImplemented) build is not implemented (5f885430-a2d2-11e5-b6cd-0dc5c3b3d9ed)**

`[-bash3.2-] -=> docker info`
Containers: 0
Images: 64
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 64
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.13-boot2docker
Operating System: Boot2Docker 1.9.1 (TCL 6.4.1); master : cef800b - Fri Nov 20 19:33:59 UTC 2015
CPUs: 1
Total Memory: 996.2 MiB
Name: dev
ID: GACQ....
Debug mode (server): true
 File Descriptors: 12
 Goroutines: 18
 System Time: 2015-12-15T02:22:20.439849875Z
 EventsListeners: 0
 Init SHA1: 
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Username: psmilajkov
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox

**Comment by cyli** [comment]
Hi @peconi!  Could you run `env` and see if you have a `DOCKER_CLIENT_TIMEOUT` set?  Maybe it's in a `.bashrc` somewhere?  It looks like you're hitting [this check](https://github.com/docker/compose/blob/master/compose/cli/docker_client.py#L20).  Thanks!

**Comment by cyli** [comment]
Oops, sorry, misread.  :)

**Comment by cyli** [comment]
@peconi does docker-compose build work on any other compose file?  Maybe one of the examples here:  https://github.com/b00giZm/docker-compose-nodejs-examples?

**Comment by peconi** [comment]
Apologies, it seems that going to Joyent was the problem. Going to another host worked fine. Closing.
