### ISSUE TITLE
Create a new TufDelegationsChange object with a different Scope implementation

### ISSUE THREAD

**Issue by cyli** [docker/notary#365]
Scope instead returns the parent of the role, because when you change a delegations role (e.g. it's keys, threshold, etc.), it's the parent that changes, not the actual role itself.

**Comment by endophage** [comment]
@cyli still required?

**Comment by cyli** [comment]
I think change objects for delegations are currently scoped to that particular delegation, instead of the parent, so I don't think the issue as per the description has been satisfied.  However, I think I opened this during a meeting in regards to something we discussed as a possible cleanup to our changelists, but I don't quite remember why.  Happy to close for now.
