### ISSUE TITLE
Remove role name translation

### ISSUE THREAD

**Issue by cyli** [docker/notary#372]
https://github.com/docker/notary/blob/master/tuf/data/roles.go#L20 has a mapping of canonical role names to custom role names, the intent originally being users could set their own role name mappings.

However, this is not currently used consistently across the codebase, and it would add a lot of extra complexity to fully support (a ton of extra tests, etc.)

However, the map itself serves a useful function as a set of all the valid canonical roles that we can easily match another role against and iterate over.  Possibly instead of removing the map, we can:

1. convert it to a `map[string]interface{}` or something, so we can key into it and iterate over it
1. convert it to a list that can be iterated over, and add a helper function `IsPrimaryRole` or `IsCanonicalRole` or something (e.g. not a delegation)

We should probably just remove `SetValidRoles` either way.

It's a small fix but a big change to update all the usages of `ValidRoles` all over the codebase.

**Comment by endophage** [comment]
Closed by #416
