### ISSUE TITLE
publish change notifications from notary server

### ISSUE THREAD

**Issue by vikstrous** [docker/notary#381]
For now it makes sense to publish notifications the same way that docker registry does it.

Eventually it would be nice to have a more robust system, but reliable message delivery in distributed systems is a hard problem with many solutions, so I don't think it makes sense to commit to a specific solution yet. Eventually notary should support various message queues.

**Comment by diogomonica** [comment]
@vikstrous is this required for the 1.5 milestone?

**Comment by vikstrous** [comment]
Yes.

**Comment by NathanMcCauley** [comment]
This may be superseded by #436

**Comment by endophage** [comment]
Closing. Changefeed serves this purpose in a more robust way.
