### ISSUE TITLE
Using the notary client with Docker configuration should be easier

### ISSUE THREAD

**Issue by mtrmac** [docker/notary#400]
At the moment, the Docker CLI client stores its Notary client state in `~/.docker/trust`, but the stand-alone `notary` client uses `~/.notary`. This makes using `notary` to manage Docker trust state awkward:
> notary -d /.docker/trust …

It would be far more convenient to provide a simple command without those two arguments copy&pasted (and sometimes forgotten or mis-pasted) all over the place.

While the default trust_dir location can be changed by setting up a `~/.notary/config.json` with a `"trust_dir"` option, that needs to be manually for every user. (An OS distribution might be configured to create such a `~/.notary/config.json` for all new accounts, but that is not that much different from, or better than, just patching the default location within the executable.)

While I’m fairly certain that this should be improved, I am not entirely sure what is the best way:
* It would probably be simplest by far to patch either Docker or Notary so that both use the same default directory.
* Alternatively, perhaps we could have the Docker CLI wrap `cmd/notary/*.go` within a `docker notary` command which uses corresponding defaults.
* Even a `notary -D` == `notary --docker` would be an improvement over the current state, but worse than any of the alternatives I think.

So far I am leaning towards changing the default `configDir` in `cmd/notary.main.go` to `~/.docker/trust` (+ adding appropriate backward compatibility fallback), but whether that is the best option depends on whether the Notary project has strong ambitions to be used beyond Docker.

**Comment by endophage** [comment]
Wouldn't be an appropriate place to use terminal aliases? I don't add my user to the docker group so I have `docker` aliased to `sudo docker`. Seems like somebody that solely uses notary with docker would alias `notary` to `notary -d ~/.docker/trust`. If they wanted to use it independently, they could come up with some other command name to alias to the docker configured context.

**Comment by diogomonica** [comment]
@mtrmac those are all points that we've considered before. Our feeling is that notary should always attempt to be useful on its own. In fact, we know of companies that are currently using notary to provide trust on their infrastructure, without using Docker.

We started off by having these things being split, because we should always support a Docker independent notary setup, but I wouldn't be opposed to recognizing that Docker is currently the main usecase, and pointing the default directory to ~/.docker/trust

**Comment by mtrmac** [comment]
> Wouldn't be an appropriate place to use terminal aliases?

This is fine as an implementation mechanism, but has the same issue as the existing `~/.notary/config.json` mechanism: If it is not set up by default then most users don't benefit, if it is set up by default by an individual site administrator, or a single distributor, the documentation, recommendations and best practices become fragmented. Having an official mechanism implemented upstream would be better.

> Our feeling is that notary should always attempt to be useful on its own.

OK. As I said I am not sure what is the best thing to do here, I am just unsatisfied with the status quo.

**Comment by diogomonica** [comment]
I believe that for now, changing `trust_dir` inside of `~/.notary/config.json` is a decent solution to prevent people from having to either use `-d` or `-c` on every command.
