### ISSUE TITLE
Support root key rotation/replacement

### ISSUE THREAD

**Issue by mtrmac** [docker/notary#404]
… to allow migrating away from known compromised keys, or from suspected-weak algorithms.

(Related: `notary key rotate` currently rotates non-root keys, and #267 is in progress to rotate root certificates. This issue is filed for the underlying root private key pair.)

**Comment by endophage** [comment]
In what way is this issue tracking different work to #396? Seems like a (maybe more specifically worded) duplicate?

**Comment by mtrmac** [comment]
#396 and #267 deal with certificates, which expire so they *have* to be rotated; but it is often reasonable to create a fresh certificate without replacing the private key (and that is what #267 is doing). (Of these, #267 is the core implementation and #396 is more of an “make sure the whole use case is covered and documented” high-level item.)

This issue is filed for the public/private key pair.

**Comment by cyli** [comment]
For lack of a better place to put it, I'm going to dump a list of tests we probably should have if we support root rotation:

#### Publishing root rotations
- [ ] first time publishing - before publishing, rotate root key; should be 1 changefile; publish 
        should succeed; and the root signed once by new key
- [ ] download repo; rotate root key; should be 1 changefile; publish should succeed;
	and the root signed once by new key and once by old key
- [ ] either first or second time publishing - rotate all the keys
	should be 4 changefiles; publish; 0 changefiles; publish should succeed and the root, target, 
        snapshot, and delegation all sent and re-signed

#### Client updating and getting a root.json with rotated keys
- [ ] updated repo has root key rotated and signed with both old and
	new key; update succeeds
- [ ] previously, root should have keys A and B (threshold 1), and was signed
	with key A only; updated repo root has threshold 1, key C, which
	is signed with B and C; update should succeed
- [ ] prev repo, root signed by A; updated repo with root rotated to key B, and
        signed by A and B (update succeeds); updated repo with root rotated to key 
        C and signed  by B and C (update succeeds - tests that client only verifies 
        against the last root and does not need the entire history of root - since it may 
        not know the entire history)
- [ ] prev repo; root signed by A; updated repo with root rotated to key B and only
        signed with A - update fails (tests root needs to be signed with old and new key)
- [ ] prev repo; root signed by A; updated repo with root rotated to key B and only
        signed with B - update fails (tests root needs to be signed with old and new key)
