### ISSUE TITLE
Add SHA-384/512

### ISSUE THREAD

**Issue by endophage** [docker/notary#412]
Based on [NSA advice](https://www.nsa.gov/ia/programs/suiteb_cryptography/index.shtml) we should be using SHA-384 at a minimum. We should add this in addition to the existing SHA-256 (generating multiple hashes for each target/meta file) so that old clients continue to operate correctly.

**Comment by HuKeping** [comment]
What should we do if we want to upgrade sha256 to sha512 but don't break the old clients?

**Comment by endophage** [comment]
@HuKeping the "hashes" entry in TUF's json files is a map so that it can contain multiple hashes. A client is actually expected to check the validity of all the hashes present. So, we should add 384/512 (probably just 512 is necessary rather than both unless somebody else disagrees), and the client should validate both the 256 and 512 hashes. Old clients will continue to just validate the Sha256 entry and ignore the Sha512.

**Comment by HuKeping** [comment]
I‘ll take a look into this if nobody is working on it

**Comment by endophage** [comment]
@HuKeping that would be great! It's not scheduled for the next release (0.2) so we're not actively looking at it.

**Comment by diogomonica** [comment]
@HuKeping how is this coming along? Adding this for notary 0.3.

**Comment by HuKeping** [comment]
@diogomonica Plan to do but not begin yet.
