### ISSUE TITLE
Consider making certificate export/import easier

### ISSUE THREAD

**Issue by mtrmac** [docker/notary#420]
Certificates can certainly be imported/exported manually, but the user has to follow a specific naming convention. It would be a bit more convenient to have `notary cert import $any_file_name` and `notary cert export $id > $any_file_name`.

**Comment by endophage** [comment]
Closing because we're deprecating cert store. Certs acquired via TOFU are redundant because they are also stored in the cached root.json. Certs that would previously have been manually loaded should instead be configured via the recently merged trust pinning.
