### ISSUE TITLE
Consider supporting passphrase change for private keys

### ISSUE THREAD

**Issue by mtrmac** [docker/notary#424]
It is probably easier for a passphrase to get compromised (by someone just watching a keyboard, or a window manager unexpectedly switching focus) than for the private key to get compromised; so it might be useful to support changing passphrases on existing keys.

**Comment by riyazdf** [comment]
This has been added for root keys, we're tracking adding this functionality (and import/export, since they are also root-only) in https://github.com/docker/notary/issues/483
