### ISSUE TITLE
ToLower on path prefix?

### ISSUE THREAD

**Issue by mtrmac** [docker/notary#444]
https://github.com/docker/notary/pull/371/files#diff-1cd41a2611da49ce63630d5a51bd82c5R271 calls `ToLower` on a role name.

AFAICS the delegation role names are path prefixes, which are typically case-sensitive (UNIX, URLs), so the `ToLower` call seems to be losing information.

What is the intent here? AFAICS the canonical role names are expected to be case-insensitive, but the delegated roles are case sensitive (looking at `data.CanonicalRole`, `utils.FindRoleIndex`, uses of `filepath.Dir`.

**Comment by mtrmac** [comment]
OK, https://github.com/docker/notary/pull/376/files#diff-a84805db69378bc67da7d4ae04da989aR120 means only lowercase is valid; still, silently converting users' input seems into a different path instead of refusing it seems curious.

**Comment by cyli** [comment]
Agree - I added this when we were still deciding on canonicalize role names (https://github.com/docker/notary/commit/d52dbde683e2caf61760d529deabd64b14bc8791#diff-a84805db69378bc67da7d4ae04da989aL102) and I have forgotten to remove it since we decided to no longer do this.
