### ISSUE TITLE
Provide a way for notary client to get more details about a repo

### ISSUE THREAD

**Issue by vikstrous** [docker/notary#446]
Notary client needs to tell us at least:
* What keys are currently allowed to sign the main targets file in a repository (what targets keys exist?)
* What key was used to sign a given tag
* What roles exist
* What key(s) can sign for which role
* What usernames are in each delegated key
* Which role a given tag is coming from
* Timestamps for everything
* What's the root key for this repository

We need to query all of this data to display information about a repository, so it would be ideal if we can make O(1) requests for this data.

**Comment by endophage** [comment]
What key was used to sign a tag requires determining what version of the repo added the tag and who signed that version. I didn't think analyzing history was in scope for dtr/1.5. 

The rest seems reasonable as it's inspection of current state.

**Comment by vikstrous** [comment]
Writing down what we talked about: "What key was used to sign a given tag" means "what role is the tag in and what key signed that role last".

**Comment by riyazdf** [comment]
These functions exist in the library but we're moving toward a static notary repository object that can serve this info.  I'll close this and keep #548 and #550 as open issues
