### ISSUE TITLE
Notary not falling back on 404 and DNS errors

### ISSUE THREAD

**Issue by diogomonica** [docker/notary#468]
If notary is pointed to a random remote server that returns a 404, it should fallback, but it doesn't:

```
➜  notary list docker.io/library/ubuntu -s https://example.com    
ERRO[0000] Client Update (Timestamp): timestamp trust data unavailable.  Has a notary repository been initialized? 
ERRO[0000] client Update (Root):root trust data unavailable.  Has a notary repository been initialized? 
* fatal: example.com does not have trust data for docker.io/library/ubuntu
```

If notary can't resolve the DNS of the remote host, it also should fallback, but it doesn't:

```
➜  notary list docker.io/library/ubuntu -s https://notary.docker.io
* fatal: Get https://notary.docker.io/v2/: dial tcp: lookup notary.docker.io on [::1]:53: read udp [::1]:39327->[::1]:53: read: connection refused
notary list docker.io/library/ubuntu -s https://notary.docker.io  0.00s user 0.00s system 102% cpu 0.006 total
```

**Comment by endophage** [comment]
In the first instance I'm wondering if this should be considered valid behaviour. A 404 means you successfully connected to the server and it didn't recognize what you were asking for. Fixing this feels like the new behaviour could only be considered correct in the case that a user mis-typed the URL (to some other valid URL), in which case falling back to local data seems like the wrong thing to do.

**Comment by endophage** [comment]
With the bugfix to #469 merged, I believe this is now fixed. There is more than can be done (i.e. return a specific JSON body or header to get a positive ID), but the update should be sufficient for the majority of cases.
