### ISSUE TITLE
/v2/ should return 204 on success

### ISSUE THREAD

**Issue by endophage** [docker/notary#470]
Given how infrequently this status code is used in services, we could use this to better determine if we're talking to an actual notary server. Small optimization to provide better messaging when the user puts in a valid URL to a server that isn't notary.

**Comment by HuKeping** [comment]
Isn't the GET /v2/ works as a `ping`? If so why should we return 204 instead of 200-OK?

**Comment by endophage** [comment]
204 indicates the request was successful but there is no body. All information on the /v2/ endpoint is carried in the headers, therefore 204 is technically a better response code than 200 on success for /v2/

Additionally we want a positive ID we are talking to a notary server. The 204 code being rarely used gives us a better marker we've reached an appropriate server, while being a very limited scope change. 

We will need to confirm that old clients continue to work. I have a suspicion they look for 200, not 2XX. In that case, we'll have to return a JSON body that identifies the notary server.

**Comment by endophage** [comment]
I'm closing this. We've realized 401 is a valid response code from the distribution auth code we're leveraging.
