### ISSUE TITLE
Allow import/export/passwd of non-root keys via notary CLI

### ISSUE THREAD

**Issue by riyazdf** [docker/notary#483]
It seems like it'd be useful to import/export keys for `targets` and potentially `snapshot` individually -- this will likely require changes to how we use our passphrase retriever as a pre-requisite since it caches the same passphrase for the two together (our concept of `tagging` key for usability).

Might also be helpful for delegation roles.

**Comment by riyazdf** [comment]
Relates to https://github.com/docker/notary/pull/485

We'll need to separate `targets` and `snapshot` keys in the passphrase retriever to get this to work properly, and change the `init` flow to make this obvious (ex: ask for a separate snapshot key)

**Comment by endophage** [comment]
Given there's no attempt limit on decrypting a file, I'm wondering if we can do something naive like we do for the yubikey (we try the default pin). If we've asked for a non-root password already (say for targets), we try that one for snapshot and ask for a different password on failure?

**Comment by riyazdf** [comment]
From some discussion IRL: it seems like it'd be nice to separate the passphrase caching from the retriever logic, and keep the cached passphrases in a map structure so we could also cache delegation passphrases.

The steps for retrieving a passphrase would then be: first check if I have this passphrase in the cached map and try if so, then ask for passphrase input on failure.
