### ISSUE TITLE
Unauthorized return code not handled by http store

### ISSUE THREAD

**Issue by dmcgowan** [docker/notary#49]
Currently any unauthorized return headers directly hit the json parser when getting meta data. The unauthorized status should be handled directly or non-OK requests handled separately.

**Comment by endophage** [comment]
What's the best way for us to do this? Should I bubble up a specific error to you? I thought the RoundTripper handled this?

**Comment by dmcgowan** [comment]
Well there are really two problems. First is the client sends all non-200 responses directly to the json parser, even if the types will not line up. Second is the server does not return JSON  errors. The distribution code base solves this by having the handlers return a specific error type and wrapping those handlers.

This problem is not limited to unauthorized. Another example is on 5000, the error will also be a JSON parse error related to an unexpected `:`

```
```

**Comment by endophage** [comment]
Yep, I've been intending to fix that. Will work on it immediately after I get the client side of atomic updates in.

**Comment by dmcgowan** [comment]
@stevvooe did a good job creating a robust handler system for distribution. I think you should import it or rip it off.

**Comment by endophage** [comment]
Will take a look. Got a link to a specific file:line?

**Comment by dmcgowan** [comment]
I like the whole dispatch system but relevant to this issue

https://github.com/docker/distribution/blob/master/registry/handlers/helpers.go#L14

**Comment by endophage** [comment]
Ah yeah, I'm familiar with that. I believe it has a bug in that the Content-Type header doesn't always get set because some of the handlers call WriteHeader before ServeJSON gets called. WriteHeader prevents any additional headers being writted. I was planning to just takes my HTTPError and give it a MarshalJSON function which could then be used to serve it out as a JSON body. Rather than serving `err.Error()` as the body we could serve `json.Marshal(err)`.

**Comment by stevvooe** [comment]
@endophage Rather than use `HTTPError`, `errcode` package no supports an http status. Would that help or is that too big of a change? I'd prefer that this doesn't invent new error types and it just uses the `errcode` format, if possible.

**Comment by endophage** [comment]
errcode is tightly coupled to the descriptors. I'd rather not tie notary in to that as it would mean having the update distribution's registry/api/v2 package when making certain updates to notary.

**Comment by stevvooe** [comment]
@endophage We've completely decoupled it. The `errcode` package will be the future of error reporting over http protocols in docker. Please use it if you have a standard http API with json errors.

**Comment by endophage** [comment]
@stevvooe I edit my last response after looking further at the code. I'm just about to submit PRs for atomic multi file updates of TUF data, then I'll be diving deeper into this.

**Comment by stevvooe** [comment]
@endophage No worries. Just being obstinately forceful :wolf:.

**Comment by endophage** [comment]
@dmcgowan is this solved?

**Comment by dmcgowan** [comment]
Error handling has been fixed, will close this and open more specific issues if we have them with authorization.
