### ISSUE TITLE
Refactor and flatten the KeyStore

### ISSUE THREAD

**Issue by diogomonica** [docker/notary#502]
Right now we:
- Need the `gun` of a key to be able to retrieve it.
- Cannot simply drop a key in a directory and have it be picked up by the keystore object

We should refactor the keystore in a way that still mantains the directory structure that we want (tuf keys, root keys, etc), but reads all the keys under `private/` into a flat keystore that can access any key by KeyID.

**Comment by riyazdf** [comment]
From testing: we can drop in a delegation key by canonical key ID name into `tuf_keys` only if one of the following is true:
 - the role is in the PEM headers for the private key (@cyli verified this)
 - the role is appended to the end of the canonical key id in the filename, ex: `canonicalKeyID_releases.key`
