### ISSUE TITLE
Use canonical IDs for all delegation commands

### ISSUE THREAD

**Issue by riyazdf** [docker/notary#506]
Since we currently need canonical IDs for the right filename to drop in delegation private keys, we should always display their IDs as canonical IDs instead of calling `key.ID()`.  The TUF metadata doesn't use the canonical ID but this is never exposed to the end user directly

**Comment by riyazdf** [comment]
Note: this will make removing keys from a delegation difficult, because there will be a mismatch from the TUF metadata's IDs (it does not use canonical IDs)

**Comment by HuKeping** [comment]
Hi @riyazdf,  what's the different between `canonical ID` and `ID`?

**Comment by riyazdf** [comment]
@HuKeping: `canonical ID` comes from `CanonicalKeyID()` in `utils.go`: essentially it's the same as calling `key.ID()` for regular TUF keys, except for keys associated with x509 certs (like in the case of delegation roles) it uses the public key part of the cert to generate the ID

**Comment by HuKeping** [comment]
Thanks @riyazdf

**Comment by riyazdf** [comment]
I'm going to try to tackle this -- my idea (credits @cyli) will be to use canonical ID for all of the notary CLI commands, and translate to the TUF ID on a `publish` for removals
