### ISSUE TITLE
Notary fail to verify signature

### ISSUE THREAD

**Issue by HuKeping** [docker/notary#521]
On host 1: docker push `notary-distribution:5678/o:latest` and signed successfully.
On host 2: docker pull `notary-distribution:5678/o:latest` but failed:
```
Pull (1 of 1): notary-distribution:5678/o:latest@sha256:9176b113ee7620cb59f5df4c8afa86e990529e3ca328fe15cbc499eeb64bedfd
Error response from daemon: missing signature key
```

On host3:docker pull `notary-distribution:5678/o:latest` but failed: 
```
Pull (1 of 1): notary-distribution:5678/o:latest@sha256:9176b113ee7620cb59f5df4c8afa86e990529e3ca328fe15cbc499eeb64bedfd
Error response from daemon: unsupported schema version 2 for tag "sha256:9176b113ee7620cb59f5df4c8afa86e990529e3ca328fe15cbc499eeb64bedfd"
```

Recheck on Host1: docker pull is succeed:
```
Pull (1 of 1): notary-distribution:5678/o:latest@sha256:9176b113ee7620cb59f5df4c8afa86e990529e3ca328fe15cbc499eeb64bedfd
sha256:9176b113ee7620cb59f5df4c8afa86e990529e3ca328fe15cbc499eeb64bedfd: Pulling from o
Digest: sha256:9176b113ee7620cb59f5df4c8afa86e990529e3ca328fe15cbc499eeb64bedfd
Status: Downloaded newer image for notary-distribution:5678/o@sha256:9176b113ee7620cb59f5df4c8afa86e990529e3ca328fe15cbc499eeb64bedfd
Tagging notary-distribution:5678/o@sha256:9176b113ee7620cb59f5df4c8afa86e990529e3ca328fe15cbc499eeb64bedfd as notary-distribution:5678/o:latest
```

The notary **git commit** is: 54667d1254f1592916f4c01aa9aa733349cef860 on master

Docker version on host1:
```
Client:
 Version:      1.10.0-dev
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   7145871
 Built:        Mon Jan 25 04:54:22 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.0-dev
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   7145871
 Built:        Mon Jan 25 04:54:22 2016
 OS/Arch:      linux/amd64
```

Docker version on host2:
```
Client:
 Version:      1.10.0-dev
 API version:  1.22
 Go version:   go1.4.2
 Git commit:   e9f7241
 Built:        Mon Dec 28 08:18:57 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.0-dev
 API version:  1.22
 Go version:   go1.4.2
 Git commit:   e9f7241
 Built:        Mon Dec 28 08:18:57 2015
 OS/Arch:      linux/amd64
```

Docker version on host3:
```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64
```

**Comment by HuKeping** [comment]
But when create a image on host2 and push it on host2, it seems fine. 
host2: docker push notary-distribution:5678/p:latest    OK
host1: docker pull notary-distribution:5678/p:latest OK
host3: docker pull notary-distribution:5678/p:latest OK

**Comment by HuKeping** [comment]
I can almost confirm that this a not an issue of Notary but docker. I reboot a new VM and install docker1.10.0-rc2. Let's call it host4.

host4: docker pull notary-distribution:5678/o:latest succeed.

**Comment by diogomonica** [comment]
@HuKeping which registry are you pushing this image to? Docker HUB or a local registry?

**Comment by riyazdf** [comment]
@HuKeping is the docker on **host1** built from master?

**Comment by HuKeping** [comment]
@diogomonica it's a local registry.

@riyazdf I'm not very sure about the docker on **host1**, but the docker on **host4** is from docker release. 
```
curl -fsSL https://test.docker.com/ | sh
```

**Comment by diogomonica** [comment]
@HuKeping what version is the registry? The latest docker 1.10 pushes new style manifests that aren't compatible with old docker clients if you're using the latest registry.

**Comment by HuKeping** [comment]
From the log, I think it is version=v2.2.1-70-ga7ae88d.m
```
time="2016-01-13T07:20:02.506281112Z" level=info msg="endpoint local-5003 disabled, skipping" environment=development go.version=go1.5.2 instance.id=94f6a929-b146-4ac9-b32c-1cdf1fb638f0 service=registry version=v2.2.1-70-ga7ae88d.m 
time="2016-01-13T07:20:02.50630185Z" level=info msg="endpoint local-8083 disabled, skipping" environment=development go.version=go1.5.2 instance.id=94f6a929-b146-4ac9-b32c-1cdf1fb638f0 service=registry version=v2.2.1-70-ga7ae88d.m 
time="2016-01-13T07:20:02.5072946Z" level=info msg="using redis blob descriptor cache" environment=development go.version=go1.5.2 instance.id=94f6a929-b146-4ac9-b32c-1cdf1fb638f0 service=registry version=v2.2.1-70-ga7ae88d.m 
time="2016-01-13T07:20:02.509165774Z" level=info msg="listening on [::]:5000, tls" environment=development go.version=go1.5.2 instance.id=94f6a929-b146-4ac9-b32c-1cdf1fb638f0 service=registry version=v2.2.1-70-ga7ae88d.m 
```

**Comment by endophage** [comment]
@HuKeping I'm seeing nobody explicitly commented on it here. The message `Error response from daemon: missing signature key` is from some old signing code that predates the notary team. That code is being removed. There are also some format changes taking place in docker 1.10 and the new registry. My understanding is the new format will get rewritten on the fly for old clients, but this will however mean it does not match the checksum found in notary.

I'm going to leave this open until docker 1.10 releases, then we will reassess and decide whether there is any work required on notary.

**Comment by diogomonica** [comment]
@HuKeping are you still seeing this with Docker 1.10? reopen if so.

**Comment by lveljovic** [comment]
Hello @HuKeping @diogomonica,

This problem happend to me on CentOS 7 and Docker version 1.11.1, build 5604cbe. Anyone still has the same problem or it's just me?

Thank you,
Lazar

**Comment by HuKeping** [comment]
@lveljovic would you mind paste some log here

**Comment by lveljovic** [comment]
Setup is like this:
From host1 I did docker push to internal docker repo -> all good
On host2 tried to execute: 
`docker pull host:port/image-name:latest`
and got error
`Error response from daemon: missing signature key`

This problem can be solved by executing command:
`docker pull host:port/image-name:latest@SHA256` - in this case SHA256 is hash of the latest docker image on that repo. The problem is that I need to know sha of the latest docker image on repo which is btw saved on the host1 and  on internal docker repo. This isn't good option for me. So @HuKeping do you have any idea how to solve this problem?

**Comment by diogomonica** [comment]
@lveljovic that is not a notary issue. That error is coming from: https://github.com/docker/libtrust/blob/master/jsonsign.go

- Do you mind pasting paste all the commands you used and the docker versions on both hosts?
- When you did the first `docker push` did you first `export DOCKER_CONTENT_TRUST=1`? 
- Are you running a `notary-server` alongside the registry at `host:port`?

**Comment by lveljovic** [comment]
@diogomonica Yes, this error isn't coming from notary, so mine question might not be related to the issue described above, just noticed same problem.  

- docker version on host1 and host2 is the same:
` docker --version
  Docker version 1.11.1, build 5604cbe`
- I just tested your proposal and used export DOCKER_CONTENT_TRUST=0 when I pushed the image, which didn't help
- I would like to mention that our docker internal repo is on Nexus3, so might be that I should post this question somewhere else.

**Comment by diogomonica** [comment]
@lveljovic I'm pretty sure that you just aren't running the notary-server side of things.

For notary to work with a self-hosted repository you need to deploy another service called notary-server alongside with it. A quick search on google for `nexus3 docker notary` or `nexus3 docker content trust`, doesn't seem to turn up any results that indicate they support image signing.

I hope this helps.

**Comment by RickMitterer** [comment]
I'm having this issue as well. We're using Nexus 3 repo and Docker 1.11.1, build 5604cbe

**Comment by lveljovic** [comment]
I contacted Nexus support. To fix it you'll need docker plugin patch: https://support.sonatype.com/hc/en-us/articles/218729178-Nexus-Repository-Manager-3-0-0-03-Docker-Rollup-Patch
