### ISSUE TITLE
 atomically updates

### ISSUE THREAD

**Issue by HuKeping** [docker/notary#527]
In my opinion, the `UpdateMany()` should either update all the record or nothing. And it do use transaction  in the database one:
https://github.com/docker/notary/blob/master/server/storage/database.go#L73-L75

But the memory one seems not:
https://github.com/docker/notary/blob/master/server/storage/memory.go#L63-L69

**Comment by endophage** [comment]
MemoryStore is only used for testing so this is non-critical. However it would be ideal to have the stores all implement the interface in a consistent manner so definitely something to be corrected.

**Comment by riyazdf** [comment]
Resolved with https://github.com/docker/notary/pull/824
