### ISSUE TITLE
An extra dangling image

### ISSUE THREAD

**Issue by HuKeping** [docker/notary#547]
When pull a image with DCT enabled, there will be an extra image, for example
```
docker pull notary-distribution:5678/hi:latest
```
and then `docker images | grep  notary-distribution:5678/hi`, there output is like:
```
notary-distribution:5678/hi                                          latest              0cb40641836c        2 weeks ago         1.114 MB
notary-distribution:5678/hi                                          <none>              0cb40641836c        2 weeks ago         1.114 MB
```

Is this intended?

**Comment by HuKeping** [comment]
Maybe it should be an issue of the daemon?

**Comment by diogomonica** [comment]
@HuKeping that should have been fixed in Docker 1.10. If it isn't, we should open an issue in docker/docker.

**Comment by HuKeping** [comment]
@diogomonica Still there in 1.11.0-dev

**Comment by HuKeping** [comment]
@diogomonica should we open an issue in docker/docker?

Still in
```
Client:
 Version:      1.11.0-dev
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   187a2fb
 Built:        Tue Mar  1 10:08:26 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.0-dev
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   187a2fb
 Built:        Tue Mar  1 10:08:26 2016
 OS/Arch:      linux/amd64
```

**Comment by riyazdf** [comment]
@diogomonica @HuKeping if I remember correctly, Docker 1.10 fixed the delete logic (https://github.com/docker/docker/pull/19170) but not the additional tag on pull?

**Comment by HuKeping** [comment]
@riyazdf Seems that pr fix the `docker rmi` but not the one on pull when enable DCT
