### ISSUE TITLE
Move all verification into setters on repo

### ISSUE THREAD

**Issue by diogomonica** [docker/notary#561]
All the verifications should be moved down to the setters on the repository. The only thing we have to do at the store level is the size verification.

**Comment by diogomonica** [comment]
Depends on #563

**Comment by cyli** [comment]
As per https://github.com/docker/notary/pull/555#discussion_r52550739, either the setters on the repo or other functions will perform per-metadata specific content verification.  After which we probably will no longer need `signed.Verify`, which verifies both metadata and signatures, and just `signed.VerifySignatures`.

**Comment by cyli** [comment]
Note: on further IRL discussion, we are going to do a walk+visitor pattern to load a TUF repo, and verification should happen on a verification visitor.

**Comment by riyazdf** [comment]
this is related to the builder, and we will have verification in the walker.  Moving to 0.3
