### ISSUE TITLE
Design of delegated signing in Docker

### ISSUE THREAD

**Issue by endophage** [docker/notary#592]
Two possibilities have been raised. In the Docker 1.11 timeframe we must decide on which design we prefer, and if necessary, write up the Google Doc describing said design to present to the Docker maintainers. The options are:

- Add a new flag to the `docker` application that on relevant commands, allows a user to pick which trust role they want to operate on.
  - Pros: High degree of power and flexibility. Fully exposes the role system to end users.
  - Cons: complicated to understand and use effectively for general end users. Changes required to docker CLI.
- Add new targets to all roles the user has signing keys for (we expect this to typically be one key that is delegated to multiple roles). When pulling, users will _only_ pull from from the `targets/releases` role, with all other roles simply serving as audit trails for who signed what. 
  - Pros: Easy for end user to understand. More complex role based options can be exposed to internal tools via library level APIs. No changes required to Docker CLI.
  - Cons: Lacks flexibility.

**Comment by programmerq** [comment]
So, if I play the part of an end user, what is the approximate workflow I could expect with each option? My two big use cases, of course, are 1) delegating to colleagues 2) delegating to robot/ci users

Without knowing much about what you have in mind, I am picturing asking my colleague to generate a private key, and I run a single command with the root key available. (similar workflow to how I'd add a colleague's gpg key to pass: "give me your public key; okay now I've put that in the system now")

**Comment by endophage** [comment]
@programmerq the admin (holder of the `targets` key), would create the delegations, and he would be free to create as many as he wants with whatever key assignments he wants. 

When a delegated user pushes, they will sign their entries into all roles they hold keys for (more specifically, probably all depth 1 delegation roles they hold keys for).

There will be some "special" delegated role (we've called it `targets/releases` so far) that is the only role users will search in when doing a pull and all users' keys should be added to this delegated role (such that it doesn't need to be "special" in code, just in concept, less fragile that way, also means an admin can actually call the role anything they want). However we will expose the full set of roles through various code level APIs, allowing integrations to do more fancy things based on who has signed what.

**Comment by endophage** [comment]
Also important to note, we would build this custom behaviour on the Docker integration side. Notary would simply expose the necessary code level API (which it largely already does) to enable the behaviour.

**Comment by endophage** [comment]
Team agreement on the second implementation (sign into all delegated roles we hold the keys for).

cc @riyazdf @cyli @NathanMcCauley @diogomonica

**Comment by endophage** [comment]
Merged in Docker 1.11
