### ISSUE TITLE
Set cache control headers

### ISSUE THREAD

**Issue by endophage** [docker/notary#597]
This will help with CDN cache management.

Anything with a checksum should be cached indefinitely, everything else should have relatively short cache times (a few minutes)

**Comment by cyli** [comment]
This probably doesn't matter, since our client doesn't use it, should we set Expires headers too?

**Comment by cyli** [comment]
Also, if we support deleting all repo metadata, does it matter that a checksum lives in the CDN indefinitely?  People probably can't get to it, so it might just be an issue with cleanup?

**Comment by endophage** [comment]
Good point about cleanup. We can start off with shorter cache settings and go from there. If we can hook into a delete notification from the registry then we could have CDN integrations to clear cache on a delete.
