### ISSUE TITLE
create a server config to require a prefix for all keys

### ISSUE THREAD

**Issue by vikstrous** [docker/notary#608]
If this config is specified, any request to get or delete a GUN without the prefix should provide a specific error that says something like "this name is invalid because it lacks the prefix X".

**Comment by endophage** [comment]
Extra context from initial discussion with Viktor:

We discussed being able to configure specific GUN prefixes into the server such that in addition to token validation, it would also require, for example, "docker.io/" as a prefix on all GUNs.

**Comment by cyli** [comment]
Working on this now.
