### ISSUE TITLE
Ensure rollback of any tuf files to a previous version isn't possible client side

### ISSUE THREAD

**Issue by NathanMcCauley** [docker/notary#61]
An attacker with a privileged network position could serve old metadata and possibly affect ntp to rollback the system clock. We should make sure the implementation of TUF does all it can to mitigate this scenario to make sure rollbacks aren't possible. It seems that freezes will be possible under this scenario, up to the validity period of the timestamping key.

**Comment by ewindisch** [comment]
Are we excluding NTP roll-forward attacks?

**Comment by endophage** [comment]
This is what the version number is for. I need to work out how to use it properly in the context of the current implementation.

**Comment by endophage** [comment]
Version numbers are being correctly used by the client.
