### ISSUE TITLE
Notary github download: release path, binary naming & packaging

### ISSUE THREAD

**Issue by RRAlex** [docker/notary#612]
Hi,

when looking at the docker-compose or docker-machine GitHub release page, it is possible to find a binary download without a .zip or tar.gz package with a standard naming convention for the past few releases.
 
GitHub lacks a "latest release" download link, but since those two pages use common naming convention and versioning, it is possible to write a small function to download the latest release of both projects, for example:

```
## Fetch latest docker-{machine,compose,...}
fetch_docker_latest() {
    local product=$1

    local DOCKER_LATEST=$(curl -sL https://github.com/docker/$product/releases/ | \
        grep -i "href=\"/docker/$product/releases/download/v\?[0-9]\.[0-9][0-9\.]*/docker-${product}-Linux-x86_64" | \
        sort -n | tail -1 | \
        sed "s/.*\/\(v\?[0-9]\.[0-9][^\/]*\)\/\(docker-${product}-Linux-x86_64\)\".*/\1\/\2/" )

    sudo curl -L https://github.com/docker/${product}/releases/download/${DOCKER_LATEST} > /usr/local/bin/docker-${product}
    sudo chmod 755 /usr/local/bin/docker-${product}
}

fetch_docker_latest compose
fetch_docker_latest machine
```

Notary has a few (very easy to fix) issues that could easily be addressed to help automate its download :

* Offer a binary only download 
* Standardize the binary only download name, following other docker projects conventions
  * ie: "docker-notary-Linux-x86_64", etc. 
* For the packaged version
  * don't put a version number in the name
  * remove the space in the command name, this is against UNIX conventions and will break bash scripts without proper escaping.
  * remove the __MACOSX folder from the zip & tar.gz archives

All in all, this should make notary easy to update in include in any kind of automation scripts : 
packer / ansible / vagrant / jenkins / etc.

Thanks! :)

**Comment by endophage** [comment]
Hi @RRAlex, thanks for the feedback. Your requests seem entirely reasonable and we're happy to take a look at further standardizing our release process.

Could you give us a bit more context around your use case? We have an issue open for building deb packages which we would then provide via Docker's existing ppa. Would providing that, or other linux packages be an even more convenient solution for you?

Regarding the naming conventions, the main docker project provides only versioned files, `docker-1.10.2` being the current Linux binary release. The `<space>2` shouldn't be there in the binary name and we're fixing that one immediately. We're not sure how it slipped in but the binaries prior to packaging were named `notary` as far as we can tell. Thank you for bringing it to our attention.

**Comment by RRAlex** [comment]
Hi @endophage,

my use case is simply automating the install of all the required docker pieces when generating VMs or updating them automatically along with releases: Be it with either Packer, Vagrant, Ansible, etc.

So, indeed, .deb files for `machine`, `compose` & `notary` would be awesome and resolve all these issues at once by simplifying install & updates (and allowing package hold, etc.)!

The rest, below, is irrelevant if **.deb** are on the way:

That said, until debs packages are available, I'm simply scraping the release pages of Github as I wasn't aware of any other source for the latest compiled binary downloads... I may not have looked hard enough and missed something? 

Also, I'm not sure what you meant by providing only versioned files?
It seems docker .deb provide `docker` and for machine the version is in the URL, not the binary?

ie: https://github.com/docker/machine/releases/download/v0.6.0/docker-machine-Linux-x86_64

cheers! :)

**Comment by endophage** [comment]
Cool, we can move up the prioritization of creating deb packages (although I can only speak for the notary project as far as that timeline).

I misunderstood/read your original post. I was looking at github.com/docker/docker which includes the version number in the binary's filename on their releases page. I'm not sure how compose and machine ended up with the same naming convention. I'll discuss with the team here but I don't see any issues with adopting the same convention on naming.

**Comment by RRAlex** [comment]
That would be awesome!
But indeed, I think compose, and maybe machine, do need .deb even faster as they come "before" in the deployment and keeping them in sync is a bit difficult right now. So, I'll let you talk to them internally and maybe the packaging team can standardize everything at once... :-)

Thanks!

**Comment by riyazdf** [comment]
Hi @RRAlex - we've tried improving the notary 0.3 release process accordingly.  There's also a separate tracking issue for debs here: https://github.com/docker/notary/issues/316

I'm closing this issue for now, but please feel free to re-open or a file a new issue if you have further packaging requests :)
