### ISSUE TITLE
Replace assert with require

### ISSUE THREAD

**Issue by endophage** [docker/notary#628]
In all the *_test.go files, replace the use of the `assert` package with the `require` package, both from the `github.com/stretchr/testify` repo. It should just be a straight string replace `s/assert/require/`. It just makes the tests run a little cleaner as assert allows the test to continue, sometimes resulting in panics (that output a lot of noise), while require fails the test immediately.

IMPORTANT: don't submit one massive PR with every single test file changed. We do actually need to review the change. Submit one PR per Go package. That'll also help avoid as many rebase/merge problems.

**Comment by HuKeping** [comment]
@endophage If you can make a list here, it would be more clear for people to pick it up.

**Comment by HuKeping** [comment]
[ ] client/client_test.go
[ ] client/changelist/changelist_test.go
[ ] client/changelist/file_changelist_test.go
[ ] client/changelist/change_test.go
[ ] client/helpers_test.go
[ ] client/backwards_compatibility_test.go
[ ] client/client_pkcs11_test.go
[ ] client/client_root_validation_test.go
[ ] client/client_update_test.go
[ ] signer/client/signer_trust_test.go
[ ] signer/keydbstore/keydbstore_test.go
[ ] signer/api/api_test.go
[ ] signer/api/rpc_api_test.go
[ ] trustmanager/keyfilestore_test.go
[ ] trustmanager/yubikey/yubikeystore_test.go
[ ] trustmanager/x509filestore_test.go
[ ] trustmanager/x509utils_test.go
[ ] trustmanager/x509store_test.go
[ ] trustmanager/filestore_test.go
[ ] trustmanager/x509memstore_test.go
[ ] certs/certs_test.go
[ ] vendor/github.com/Sirupsen/logrus/hooks/sentry/sentry_test.go
[ ] vendor/github.com/Sirupsen/logrus/hooks/papertrail/papertrail_test.go
[ ] vendor/github.com/Sirupsen/logrus/hooks/bugsnag/bugsnag_test.go
[ ] vendor/github.com/Sirupsen/logrus/hooks/airbrake/airbrake_test.go
[ ] vendor/github.com/Sirupsen/logrus/hooks/syslog/syslog_test.go
[ ] vendor/github.com/Sirupsen/logrus/formatters/logstash/logstash_test.go
[ ] vendor/github.com/Sirupsen/logrus/text_formatter_test.go
[ ] vendor/github.com/Sirupsen/logrus/logrus_test.go
[ ] vendor/github.com/Sirupsen/logrus/json_formatter_test.go
[ ] vendor/github.com/Sirupsen/logrus/hook_test.go
[ ] vendor/github.com/Sirupsen/logrus/formatter_bench_test.go
[ ] vendor/github.com/Sirupsen/logrus/entry_test.go
[ ] vendor/github.com/docker/docker/pkg/tarsum/fileinfosums_test.go
[ ] vendor/github.com/docker/docker/pkg/tarsum/versioning_test.go
[ ] vendor/github.com/docker/docker/pkg/tarsum/tarsum_test.go
[ ] vendor/github.com/docker/docker/pkg/term/winconsole/console_windows_test.go
[ ] vendor/github.com/docker/docker/pkg/term/winconsole/term_emulator_test.go
[ ] vendor/github.com/docker/distribution/context/http_test.go
[ ] vendor/github.com/docker/distribution/context/trace_test.go
[ ] vendor/github.com/docker/distribution/uuid/uuid_test.go
[ ] vendor/github.com/docker/distribution/health/checks/checks_test.go
[ ] vendor/github.com/docker/distribution/health/health_test.go
[ ] vendor/github.com/docker/distribution/health/api/api_test.go
[ ] vendor/github.com/docker/distribution/registry/client/auth/session_test.go
[ ] vendor/github.com/docker/distribution/registry/client/auth/authchallenge_test.go
[ ] vendor/github.com/docker/distribution/registry/auth/htpasswd/access_test.go
[ ] vendor/github.com/docker/distribution/registry/auth/htpasswd/htpasswd_test.go
[ ] vendor/github.com/docker/distribution/registry/auth/silly/access_test.go
[ ] vendor/github.com/docker/distribution/registry/auth/token/token_test.go
[ ] vendor/github.com/docker/distribution/registry/api/errcode/errors_test.go
[ ] vendor/github.com/docker/distribution/registry/api/v2/routes_test.go
[ ] vendor/github.com/docker/distribution/registry/api/v2/urls_test.go
[ ] vendor/github.com/docker/distribution/registry/api/v2/names_test.go
[ ] vendor/github.com/docker/distribution/digest/digester_resumable_test.go
[ ] vendor/github.com/docker/distribution/digest/digest_test.go
[ ] vendor/github.com/docker/distribution/digest/set_test.go
[ ] vendor/github.com/docker/distribution/digest/verifiers_test.go
[ ] vendor/github.com/docker/distribution/digest/tarsum_test.go
[ ] vendor/github.com/docker/libtrust/certificates_test.go
[ ] vendor/github.com/docker/libtrust/key_files_test.go
[ ] vendor/github.com/docker/libtrust/key_test.go
[ ] vendor/github.com/docker/libtrust/rsa_key_test.go
[ ] vendor/github.com/docker/libtrust/util_test.go
[ ] vendor/github.com/docker/libtrust/trustgraph/statement_test.go
[ ] vendor/github.com/docker/libtrust/trustgraph/memory_graph_test.go
[ ] vendor/github.com/docker/libtrust/filter_test.go
[ ] vendor/github.com/docker/libtrust/ec_key_test.go
[ ] vendor/github.com/docker/libtrust/jsonsign_test.go
[ ] vendor/github.com/google/gofuzz/example_test.go
[ ] vendor/github.com/google/gofuzz/fuzz_test.go
[ ] vendor/github.com/agl/ed25519/extra25519/extra25519_test.go
[ ] vendor/github.com/agl/ed25519/ed25519_test.go
[ ] vendor/github.com/mitchellh/go-homedir/homedir_test.go
[ ] vendor/github.com/mitchellh/mapstructure/mapstructure_examples_test.go
[ ] vendor/github.com/mitchellh/mapstructure/decode_hooks_test.go
[ ] vendor/github.com/mitchellh/mapstructure/mapstructure_benchmark_test.go
[ ] vendor/github.com/mitchellh/mapstructure/mapstructure_test.go
[ ] vendor/github.com/mitchellh/mapstructure/mapstructure_bugs_test.go
[ ] vendor/github.com/bugsnag/bugsnag-go/bugsnag_test.go
[ ] vendor/github.com/bugsnag/bugsnag-go/middleware_test.go
[ ] vendor/github.com/bugsnag/bugsnag-go/errors/error_test.go
[ ] vendor/github.com/bugsnag/bugsnag-go/errors/parse_panic_test.go
[ ] vendor/github.com/bugsnag/bugsnag-go/configuration_test.go
[ ] vendor/github.com/bugsnag/bugsnag-go/appengine_test.go
[ ] vendor/github.com/bugsnag/bugsnag-go/panicwrap_test.go
[ ] vendor/github.com/bugsnag/bugsnag-go/metadata_test.go
[ ] vendor/github.com/bugsnag/osext/osext_test.go
[ ] vendor/github.com/miekg/pkcs11/pkcs11_test.go
[ ] vendor/github.com/miekg/pkcs11/parallel_test.go
[ ] vendor/github.com/magiconair/properties/example_test.go
[ ] vendor/github.com/magiconair/properties/load_test.go
[ ] vendor/github.com/magiconair/properties/properties_test.go
[ ] vendor/github.com/magiconair/properties/benchmark_test.go
[ ] vendor/github.com/go-sql-driver/mysql/utils_test.go
[ ] vendor/github.com/go-sql-driver/mysql/errors_test.go
[ ] vendor/github.com/go-sql-driver/mysql/benchmark_test.go
[ ] vendor/github.com/go-sql-driver/mysql/driver_test.go
[ ] vendor/github.com/lib/pq/hstore/hstore_test.go
[ ] vendor/github.com/jinzhu/gorm/customize_column_test.go
[ ] vendor/github.com/jinzhu/gorm/search_test.go
[ ] vendor/github.com/jinzhu/gorm/delete_test.go
[ ] vendor/github.com/jinzhu/gorm/callbacks_test.go
[ ] vendor/github.com/jinzhu/gorm/slice_test.go
[ ] vendor/github.com/jinzhu/gorm/join_table_test.go
[ ] vendor/github.com/jinzhu/gorm/multi_primary_keys_test.go
[ ] vendor/github.com/jinzhu/gorm/preload_test.go
[ ] vendor/github.com/jinzhu/gorm/main_test.go
[ ] vendor/github.com/jinzhu/gorm/polymorphic_test.go
[ ] vendor/github.com/jinzhu/gorm/callback_test.go
[ ] vendor/github.com/jinzhu/gorm/embedded_struct_test.go
[ ] vendor/github.com/jinzhu/gorm/migration_test.go
[ ] vendor/github.com/jinzhu/gorm/scope_test.go
[ ] vendor/github.com/jinzhu/gorm/structs_test.go
[ ] vendor/github.com/jinzhu/gorm/query_test.go
[ ] vendor/github.com/jinzhu/gorm/create_test.go
[ ] vendor/github.com/jinzhu/gorm/association_test.go
[ ] vendor/github.com/jinzhu/gorm/update_test.go
[ ] vendor/github.com/jinzhu/gorm/pointer_test.go
[ ] vendor/github.com/kr/text/wrap_test.go
[ ] vendor/github.com/kr/text/indent_test.go
[ ] vendor/github.com/kr/text/colwriter/column_test.go
[ ] vendor/github.com/kr/pretty/example_test.go
[ ] vendor/github.com/kr/pretty/formatter_test.go
[ ] vendor/github.com/kr/pretty/diff_test.go
[ ] vendor/github.com/BurntSushi/toml/encode_test.go
[ ] vendor/github.com/BurntSushi/toml/decode_test.go
[ ] vendor/github.com/spf13/jwalterweatherman/jww_test.go
[ ] vendor/github.com/spf13/viper/viper_test.go
[ ] vendor/github.com/spf13/cast/cast_test.go
[ ] vendor/github.com/mattn/go-sqlite3/error_test.go
[ ] vendor/github.com/mattn/go-sqlite3/sqlite3_fts3_test.go
[ ] vendor/github.com/mattn/go-sqlite3/sqlite3_test.go
[ ] vendor/github.com/stretchr/testify/require/forward_requirements_test.go
[ ] vendor/github.com/stretchr/testify/require/requirements_test.go
[ ] vendor/github.com/stretchr/testify/assert/assertions_test.go
[ ] vendor/github.com/stretchr/testify/assert/http_assertions_test.go
[ ] vendor/github.com/stretchr/testify/assert/forward_assertions_test.go
[ ] vendor/github.com/gorilla/mux/old_test.go
[ ] vendor/github.com/gorilla/mux/mux_test.go
[ ] vendor/github.com/gorilla/mux/bench_test.go
[ ] vendor/github.com/gorilla/context/context_test.go
[ ] vendor/golang.org/x/crypto/poly1305/poly1305_test.go
[ ] vendor/golang.org/x/crypto/salsa20/salsa/salsa_test.go
[ ] vendor/golang.org/x/crypto/bcrypt/bcrypt_test.go
[ ] vendor/golang.org/x/crypto/pbkdf2/pbkdf2_test.go
[ ] vendor/golang.org/x/crypto/blowfish/blowfish_test.go
[ ] vendor/golang.org/x/crypto/scrypt/scrypt_test.go
[ ] vendor/golang.org/x/crypto/nacl/secretbox/secretbox_test.go
[ ] vendor/gopkg.in/yaml.v2/encode_test.go
[ ] vendor/gopkg.in/yaml.v2/suite_test.go
[ ] vendor/gopkg.in/yaml.v2/decode_test.go
[ ] cryptoservice/import_export_compatibility_test.go
[ ] cryptoservice/crypto_service_test.go
[ ] cryptoservice/import_export_test.go
[ ] cryptoservice/certificate_test.go
[ ] cmd/notary-signer/main_test.go
[ ] cmd/notary-server/main_test.go
[ ] cmd/notary/prettyprint_test.go
[ ] cmd/notary/keys_test.go
[ ] cmd/notary/main_test.go
[ ] cmd/notary/tuf_test.go
[ ] cmd/notary/delegations_test.go
[ ] cmd/notary/integration_test.go
[ ] cmd/notary/integration_nonpkcs11_test.go
[ ] cmd/notary/integration_pkcs11_test.go
[ ] tuf/client/client_test.go
[ ] tuf/data/roles_test.go
[ ] tuf/data/timestamp_test.go
[ ] tuf/data/root_test.go
[ ] tuf/data/types_test.go
[ ] tuf/data/snapshot_test.go
[ ] tuf/data/targets_test.go
[ ] tuf/signed/sign_test.go
[ ] tuf/signed/verify_test.go
[ ] tuf/signed/verifiers_test.go
[ ] tuf/signed/ed25519_test.go
[ ] tuf/store/httpstore_test.go
[ ] tuf/store/store_test.go
[ ] tuf/store/filestore_test.go
[ ] tuf/store/memorystore_test.go
[ ] tuf/store/offlinestore_test.go
[ ] tuf/tuf_test.go
[ ] tuf/validation/errors_test.go
[ ] tuf/utils/utils_test.go
[ ] tuf/utils/role_sort_test.go
[ ] tuf/utils/util_test.go
[ ] tuf/utils/stack_test.go
[ ] tuf/testutils/swizzler_test.go
[ ] tuf/encrypted/encrypted_test.go
[ ] passphrase/passphrase_test.go
[ ] utils/http_test.go
[ ] utils/configuration_test.go
[ ] server/timestamp/timestamp_test.go
[ ] server/snapshot/snapshot_test.go
[ ] server/server_test.go
[ ] server/integration_test.go
[ ] server/storage/database_test.go
[ ] server/storage/memory_test.go
[ ] server/handlers/validation_test.go
[ ] server/handlers/default_test.go
[ ] server/handlers/roles_test.go

**Comment by riyazdf** [comment]
@HuKeping we shouldn't change vendored code (any tests under `vendor/`), but thanks for making this list! :smile: 

It also might be cleaner just to make a list of the packages in this issue for tracking (ex: `client`, `trustmanager`) since we'd also prefer to review PRs for one package at a time for easier reviewing and merging

**Comment by HuKeping** [comment]
Great idea!

**Comment by riyazdf** [comment]
alright, I think all of the packages now have either an open PR or have already been converted :smile:

**Comment by HuKeping** [comment]
Thanks @riyazdf

**Comment by HuKeping** [comment]
We can close this now.

**Comment by riyazdf** [comment]
@HuKeping yup, will do - thanks for your help on this issue 😄
