### ISSUE TITLE
Convert the server and signer to use alpine images (blocked on musl bugs)

### ISSUE THREAD

**Issue by cyli** [docker/notary#635]
See https://github.com/golang/go/issues/14476

We have to build the migrate package, which requires musl libc.

This is sort of done in https://github.com/docker/notary/compare/server-signer-alpine?expand=1, but docker-compose up fails.

In that branch, the server and signer build fine, but when starting up, we see:

```
signer_1 | Segmentation fault
signer_1 | waiting for notarymysql to come up.
server_1 | Segmentation fault
server_1 | waiting for notarymysql to come up.
```

Over and over - the segfault happens when trying to run the built `migrate` binary.

As per the issue, it seems like the fix might be in 1.6.1?

Once we upgrade to 1.6.1, if the bug has been fixed, then we can merge the branch.

UPDATE:  As @dmcgowan points out, that issue is linux/386 related, and `golang:1.6-alpine` is using the amd64 version of go.  I've opened https://github.com/golang/go/issues/14851 as a result - it may not be go 1.6, could possibly be a bug in go-sqlite3's CGO, but I can't tell :(

**Comment by HuKeping** [comment]
It would be great if we can use the apline as the base image and put static binary signer/server into it. I have tried before and failed.

Happy to see there is an issue to track with

**Comment by cyli** [comment]
@HuKeping I think we do that with the official images, but since these dockerfiles are used for development, they would include the source too.
