### ISSUE TITLE
add target to notary by hash

### ISSUE THREAD

**Issue by riyazdf** [docker/notary#649]
Allow for notary to add a target solely by hash and target name (no input file needed).

We can make heavy re-use of https://github.com/riyazdf/notary/tree/conman, though we might want to make it a flag for the base add command: `notary add --hash <sha256>`

**Comment by NathanMcCauley** [comment]
What about also adding untagged hashes?

**Comment by riyazdf** [comment]
@NathanMcCauley we could, but it would definitely complicate how we handle target paths in validation without some special casing.  Did you have a specific use case in mind?
