### ISSUE TITLE
What's the relationship between notary and registry?

### ISSUE THREAD

**Issue by wemeya** [docker/notary#654]
I've been seeing docs of notary, however I still don't understand the relationship between notary and registry.  Is this right: After I run notary list example.com/scripts, then I should run docker pull with the corresponding tag? However, when I publish, I publish the data to the notary server, not the registry. 
If there is no relationship between notary and registry, then how do I pull images others published using notary?
Also, I find when I run notary at ubuntu14.04, I put notary-server in /ect/hosts, pointing to 127.0.0.1. Then I run notary init... It says can't reach notary-server:4443; When I change notary-server to localhost in config.json, it works. However, it still can't reach docker.io. But In 15.10, everything works well. Thanks!

**Comment by riyazdf** [comment]
hi @wemeya, I'd suggest taking a look at https://docs.docker.com/notary/getting_started/ for more information about naming for notary and docker content trust.  Docker tags must be prefixed with `docker.io/` for usage in notary, so for your example, you'd run `notary list docker.io/example.com/scripts` to see all of the docker tags for the the `example.com/scripts` Docker repo.

Notary and Docker's registry are integrated when docker content trust is enabled -- essentially, `docker push` with content trust enabled will publish trust data for `docker.io/example.com/scripts` to a notary server in addition to pushing the image layers to the registry.

As for your issue for connecting to notary-server, I'm unsure how to help you without more information on your setup -- which notary client config are you using, and how are you running notary-server?

**Comment by HuKeping** [comment]
Hi @wemeya, we should know that the registry can work with or without notary. Let's start from some scenarios:

- Only registry. Mr.A can push/pull Mr.B's images, so the image is not safe.
- Registry with Index(something like access control module).  Mr.A cann't push(maybe) Mr.B's image, so the image is much more safe than scenario_1. Considered that Mr.C ask Mr.B to generate a image for him, how could Mr.C know the image he pulled is from Mr.B but not from Mr.A(who has stolen Mr.B's crendential).
- Registry with Index with Notary. Mr.C ask Mr.B to generate an image for him. Mr.B did it and signed the image via Notary. What Mr.C needs to do is to enable DCT and specify the same address of Notary-Server as Mr.B, he can then be guranteed that the image is from Mr.B

Above explains the relationship between registry and notary a little.

**Comment by wemeya** [comment]
hi @riyazdf   Firstly, I have to say that I do not push an image to Docker Hub. I push an image to a private hub, also we want DCT enabled. That is to say we are building a hub like Docker Hub. 
Maybe I can't understand the doc well because of my inexperience. When I read the docs, it seems that notary server is another registry that stores the trust data, there is no relationship between registry and notary. I also referenced the content in https://github.com/docker/notary , however, when I run 
curl example.com/install.sh | notary verify example.com/scripts v1 | sh
notary seems no response.
Do you mean that when DCT enabled, I just use a command--docker push without using notary publish? 
I strongly suggest that you can give an example  of how to combine notary and registry together.

As to the config question of notary-server, since I am not in the company, I will give you the details when i go to work. Thanks!

**Comment by wemeya** [comment]
hi @HuKeping Thanks for your answer, I know notary is made for secure the registry. However, my point is how to use them at the same time, how to combine them together if i run a registry like Docker hub. Thanks!

**Comment by cyli** [comment]
@wemeya Just to validate our understanding, as we were a little confused by "hub like Docker Hub", is this what you want to do?

1.  Deploy https://github.com/docker/docker-registry
1.  Deploy notary server
1.  Have your local client push a nd pull to your deployed `https://github.com/docker/docker-registry` using DCT against your deployed notary server?

Or are you looking to integrate notary with something other than https://github.com/docker/docker-registry? 

Thanks!

**Comment by wemeya** [comment]
Hi @cyli  Sorry for the confusion, since i'm not a native english speaker.  As a intern, I was asked to study how to integrate notary with registry. The first and the second are right, the third should be using DCT with my deployed notary server, not against. I will repeat my question:
Now we are researching Docker Notary, which we want to be integrated with our registry which is already running and serving for others. What confused me is, how to integrate notary and registry together, and next how to push and pull an image to/from a registry with notary enabled? Also does notary server only store trust data rather than images, because from your example, notary server stores trust collections, which makes me feel like that notary also stores images like registry.
Am I clear? If any questions, please feel free to contact me. 
Thanks!

**Comment by cyli** [comment]
Hey @wemeya Not at all, we just weren't sure if you were trying to some other kind of service  :)  Let me try to give a rough overview of this:

As for what notary stores, you are correct in that it just stores trust data.  The images themselves are stored in the registry - notary stores signed image checksums.

So how you would configure DCT, once you have a registry running and a notary server running, is roughly this:

1.  `$ export DOCKER_CONTENT_TRUST_SERVER=<url to your notary server>`
1.  `$ export DOCKER_CONTENT_TRUST=1`
1.  `$ docker push <registry url>/<username>/<imagename>:<tag>`

What this will do is push the image to your registry.  Once it has pushed, the Docker client (which uses the Notary client as a library) will create a new repo if one hasn't been created already (including any keys needed), add the image checksum to your trusted collection, and publish that collection to your notary server.

When you run `$ docker pull <registry url>/<username>/<imagename>:<tag>` first contacts the notary server, looks to see if `<tag>` is in the trusted collection.  If not, it will error and you will not be able to pull.   If it does, it gets that tag checksum, and effectively calls `docker pull <imagename>@sha256:<checksum>` and pulls that particular image sha from the registry - it does not pull by tag from the registry, but basically uses notary to do the name resolution.

You shouldn't need to use the Notary client  to use DCT unless you were doing something advanced, such as using delegations.

Not sure if this answers your questions - this is a really rough overview of how to do it.  There are more specifics like how to configure your SSL certs if you have any, setting up auth, etc, but this is the general principle.

**Comment by wemeya** [comment]
@cyli Sure, it really helps me a lot, I am more clearly about notary now. Also, I hope you can have a doc instructs developers to deploy a registry with notary enabled. 
I will talk to my colleagues to see if they have any questions. If not, I will close the issue.
Thanks a lot!

**Comment by cyli** [comment]
@wemeya Will do, thank you for the feedback!

**Comment by wemeya** [comment]
Hi @cyli  Imagine such a situation: I have a registry that has already been running for several days. It has a few images. Now I want to run a notary service with that registry. How should I do verification for the older images that users pushed long long ago? How do you implement this in Docker Hub? 
Thanks!

**Comment by HuKeping** [comment]
@wemeya When you pull the old ones with DCT **enabled** , you will get a error to tell you that there is no trust data for what you are pulling, and the pull will be abort.

But you can sign the old images and then the pull will be all OK.

**Comment by wemeya** [comment]
Hi@HuKeping  After I signed the old images, I need to repush it or use the notary client to publish the metadata to the notary server. Is that right?

**Comment by HuKeping** [comment]
@wemeya You (or the other user) need to repush it with DCT enabled. Imaging you have an old image named  "ihub.com:1234/official/busybox:latest"

what you need to do is:
- export DOCKER_CONTENT_TRUST=1
- export DOCKER_CONTENT_TRUST_SERVER=https://notary-server:4443
- docker push ihub.com:1234/official/busybox:latest

and then follow the wizard(docker will ask you to generate some keys).

After that, the trust collection of this image was push to `Notary`, no need to use notary client to publish that again.

**Comment by wemeya** [comment]
@HuKeping  Got it! But I want to know when should I use the notary client? what does it designed for?
Thanks!

**Comment by HuKeping** [comment]
Docker only use notary as a lib, so it can not do some things advanced like `delete`, `delegation`, etc.

**Comment by wemeya** [comment]
@HuKeping Thanks very much! I will close the issue.

**Comment by HuKeping** [comment]
You're welcome and feel free to reopen it if you have further questions @wemeya :)
