### ISSUE TITLE
Re-enable ability to import key noninteractively

### ISSUE THREAD

**Issue by dnwake** [docker/notary#707]
It used to be possible to import a key noninteractively with a command like:

> notary key import KEYFILE --role user

With the more recent notary client (I'm on commit 358add60750328a5dea72c5cf43e29eacd9e6e97 ) this no longer seems to be possible:  

> **notary key import delegation.key --role user**
> Enter passphrase for new user key with ID e7b9e5e:

I've tried setting all the environment variables I could find in the sourcecode (NOTARY_ROOT_PASSPHRASE, NOTARY_DELEGATION_PASSPHRASE, NOTARY_TARGETS_PASSPHRASE, NOTARY_SNAPSHOT_PASSPHRASE), but none of them get rid of the passphrase prompt.

**Comment by riyazdf** [comment]
Hi @dnwake, could you try importing to another delegation role prefixed by `targets/` (ex: `targets/user`)?  Please let us know if that works for you and I can update the documentation to make this flow more clear.

**Comment by dnwake** [comment]
@riyazdf  I see the same issue:

> **notary key import /root/delegation.key --role targets/user**
> Enter passphrase for new targets/user key with ID 036ec53:

I've tried setting NOTARY_TARGETS_PASSPHRASE but it didn't make a difference.  Is there any way to get past this?  Thanks.

**Comment by riyazdf** [comment]
@dnwake: you'll need `NOTARY_DELEGATION_PASSPHRASE` to be set when importing `targets/user` if you don't want any interaction for setting its passphrase

Also is your private key a valid PEM with a typed header?  (Ex: `-----BEGIN RSA PRIVATE KEY-----`)

**Comment by dnwake** [comment]
@riyazdf That works, thanks!  BTW, the docs here need to be updated:  http://docs.master.dockerproject.org/engine/security/trust/trust_delegation/

**Comment by riyazdf** [comment]
thanks!  We're actually thinking it makes sense to keep the documented behavior since delegation keys can be shared across repositories, I've opened a PR to allow for this: #709

**Comment by riyazdf** [comment]
Closed with #709
