### ISSUE TITLE
Trust delegation results in error on subsequent Docker Content Trust push to same repo:  "tuf: invalid role root.2."

### ISSUE THREAD

**Issue by dnwake** [docker/notary#723]
Using Docker version 1.10.2, build c3959b1
Notary server and client both built from commit 134bdbc

To reproduce:

* Push to a repo using Content Trust
* Add trust delegation, following the instructions at http://docs.master.dockerproject.org/engine/security/trust/trust_delegation/
* Try to push again to the same repo from the same machine with Content Trust (it can be the same tag or a different tag)
* The push fails with an error: "Could not publish Repository: tuf: invalid role root.2."

In more detail:

1. Generate an SSL cert and import it into Notary:
**> openssl genrsa -out /root/delegation.key 2048**
**> openssl req -new -sha256 -key /root/delegation.key -out /root/delegation.csr -subj "/C=XX/ST=XX/L=XX/O=XX/OU=XX/CN=XX"**
**> openssl x509 -req -days 365 -in /root/delegation.csr -signkey /root/delegation.key -out /root/delegation.crt**
**> export NOTARY_DELEGATION_PASSPHRASE=notary_delegation_passphrase**
**> notary -d /root/.docker/trust key import /root/delegation.key --role targets/user**

2. Push using Content Trust:
**> export DOCKER_CONTENT_TRUST=1**
**> export DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE=targets**
**> export DOCKER_CONTENT_TRUST_ROOT_PASSPHRASE=root**
**> export DOCKER_CONTENT_TRUST_SERVER=https://notary-server:4443**
**> docker push registry-server:5000/a:v1**

3. Perform Content Trust Delegation, as specified at http://docs.master.dockerproject.org/engine/security/trust/trust_delegation/
**> export NOTARY_DELEGATION_PASSPHRASE=notary_delegation_passphrase**
**> export NOTARY_ROOT_PASSPHRASE=root**
**> export NOTARY_SNAPSHOT_PASSPHRASE=targets**
**> export NOTARY_TARGETS_PASSPHRASE=targets**
**> notary -s https://notary-server:4443 -d /root/.docker/trust key rotate registry-server:5000/a snapshot -r**
**> notary -s https://notary-server:4443 -d /root/.docker/trust delegation add registry-server:5000/a targets/releases /root/delegation.crt --all-paths**
**> notary -s https://notary-server:4443 -d /root/.docker/trust publish registry-server:5000/a**

4. Attempt to push the same ref from the same machine again, with Content Trust
**> export DOCKER_CONTENT_TRUST=1**
**> export DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE=targets**
**> export DOCKER_CONTENT_TRUST_ROOT_PASSPHRASE=root**
**> export DOCKER_CONTENT_TRUST_SERVER=https://notary-server:4443**
**> docker -D push registry-server:5000/a:v1**
> The push refers to a repository [registry-server:5000/a]
> [some output skipped]
> Signing and pushing trust metadata
> time="2016-05-06T02:40:03Z" level=debug msg="Adding cert with certID: 7ddadbf013e88b4d83562286f0b33fca2385c711f9a95fad4f6be7397a51f72e"
> time="2016-05-06T02:40:03Z" level=debug msg="Making dir path: /root/.docker/trust/tuf/registry-server:5000/a/changelist"
> time="2016-05-06T02:40:03Z" level=debug msg="Adding target \"v1\" with sha256 \"3c846030a3d1e602db048edfbeb2cf5aa3aebf290375ed0b7a934297b8e6500a\" and size 920 bytes.\n"
> time="2016-05-06T02:40:03Z" level=debug msg="entered ValidateRoot with dns: registry-server:5000/a"
> time="2016-05-06T02:40:03Z" level=debug msg="found the following root keys: [7ddadbf013e88b4d83562286f0b33fca2385c711f9a95fad4f6be7397a51f72e]"
> time="2016-05-06T02:40:03Z" level=debug msg="found 1 valid leaf certificates for registry-server:5000/a"
> time="2016-05-06T02:40:03Z" level=debug msg="found 1 valid root certificates for registry-server:5000/a"
> time="2016-05-06T02:40:03Z" level=debug msg="entering root certificate rotation for: registry-server:5000/a"
> time="2016-05-06T02:40:03Z" level=debug msg="Adding cert with certID: 7ddadbf013e88b4d83562286f0b33fca2385c711f9a95fad4f6be7397a51f72e"
> time="2016-05-06T02:40:03Z" level=debug msg="ignoring certificate addition to: registry-server:5000/a"
> time="2016-05-06T02:40:03Z" level=debug msg="Root validation succeeded for registry-server:5000/a"
> time="2016-05-06T02:40:03Z" level=debug msg="200 when retrieving metadata for root"
> time="2016-05-06T02:40:03Z" level=debug msg="Adding key 09b98bb517115cddb819fb8fcd1b86ba39424740471a20ac2a49db577b93365b"
> time="2016-05-06T02:40:03Z" level=debug msg="Adding key 1e56ba4ec24b5bf5967e175e629646b281574d1e320b126f32aae53a74e21eef"
> time="2016-05-06T02:40:03Z" level=debug msg="Adding key 5b9c472858acb0a448bcb86b857ab52aae8d4f2e909d1e3b29ed574d407ac1fb"
> time="2016-05-06T02:40:03Z" level=debug msg="Adding key 7ddadbf013e88b4d83562286f0b33fca2385c711f9a95fad4f6be7397a51f72e"
> time="2016-05-06T02:40:03Z" level=debug msg="Adding role root with keys 7ddadbf013e88b4d83562286f0b33fca2385c711f9a95fad4f6be7397a51f72e"
> time="2016-05-06T02:40:03Z" level=debug msg="Adding role root.2 with keys 7ddadbf013e88b4d83562286f0b33fca2385c711f9a95fad4f6be7397a51f72e"
> time="2016-05-06T02:40:03Z" level=error msg="Could not publish Repository: tuf: invalid role root.2."
tuf: invalid role root.2.

**Comment by cyli** [comment]
This is the problem:  https://github.com/docker/notary/issues/722

**Comment by dnwake** [comment]
@cyli Thanks:  Do you know if there is any workaround (perhaps using a different version of Notary and/or Docker?).

**Comment by cyli** [comment]
@dnwake We don't have a specific version but 6a3c5d7 is the commit right before that change was introduced, so maybe a client from that version?

Many apologies for the incompatibility!  We will fix this as soon as possible.

**Comment by dnwake** [comment]
Ok -- I'll give it a shot.
