### ISSUE TITLE
Official notary server docker image

### ISSUE THREAD

**Issue by jfrazelle** [docker/notary#73]
Would be cool if it was super minimal like https://github.com/docker/swarm-library-image

Obviously I am open to making this for you all if you approve 😇

**Comment by aaronlehmann** [comment]
PRs with a first pass at official images here:

https://github.com/docker/notary-server-image/pull/1
https://github.com/docker/notary-signer-image/pull/1

I have a docker-compose file that makes these work together properly, but I'm not sure where it should go. Also, the docker-compose file requires a MySQL server, from the notarymysql image. Should we create an official image for notarymysql too?

cc @diogomonica @NathanMcCauley

**Comment by thaJeztah** [comment]
> Also, the docker-compose file requires a MySQL server, from the notarymysql image.

Out of curiosity, what makes that MySQL image different, and would it be possible to use a vanilla MySQL image?

**Comment by endophage** [comment]
We have the repositories set up in HUB and are waiting on an update to fix a pathing problem in the autobuilds code that finds Dockerfiles. I've been promised it'll be fixed within a week then the latest tag for each of the notary_server/notary_signer official repos will track the master branch here. We'll use git tags to create official versioned releases (format of tags TBD but something like `release/*`) that can also be autobuilt.

**Comment by endophage** [comment]
@thaJeztah `notarymysql` bootstraps some database setup.

**Comment by endophage** [comment]
Repo here: https://github.com/docker/notary-official-images
PR for images: https://github.com/docker-library/official-images/pull/1423
PR for image docs: https://github.com/docker-library/docs/pull/483

**Comment by endophage** [comment]
PRs are merged. Official images are up pending hub/registry errors

**Comment by endophage** [comment]
https://hub.docker.com/r/_/notary/
