### ISSUE TITLE
Cut 0.3 notary binaries

### ISSUE THREAD

**Issue by endophage** [docker/notary#737]

**Comment by HuKeping** [comment]
what's this for?

**Comment by endophage** [comment]
@HuKeping it's just a tracking issue for us to wrap up a 0.3 release. We completed all major functionality in the 0.3 milestone, have fixed bugs we found, and are going to publish a 0.3 notary client and official images. Major features are root rotations and trust pinning.

**Comment by riyazdf** [comment]
https://github.com/docker/notary/releases/tag/v0.3.0
