### ISSUE TITLE
0.3 Release notes

### ISSUE THREAD

**Issue by endophage** [docker/notary#738]

**Comment by endophage** [comment]
Major Updates:
  - Root rotations
  - Delegation support
  - RethinkDB support as a storage backend for Server and Signer
  - A new TUF repo builder that merges server and client validation
  - Trust Pinning: configure known good key IDs and CAs to replace TOFU.

Minor Improvements:
  - Add --input, --output, and --quiet flags to notary verify command
  - Remove local certificate store. It was redundant as all certs were also stored in the cached root.json
  - Cleanup of dead code in client side key storage logic
  - Update project to Go 1.6.1
  - Reorganize vendoring to meet Go 1.6+ standard. Still using Godeps to manage vendored packages
  - Add targets by hash, no longer necessary to have the original target data available
  - Active Key ID verification during signature verification
  - Switch all testing from assert to require, reduces noise in test runs
  - Use alpine based images for smaller downloads and faster setup times
  - Clean up out of data signatures when re-signing content
  - Set cache control headers on HTTP responses from Notary Server
  - Add sha512 support for targets
  - Move SQLite dependency to tests only so it doesn't get build into official images

Bugfixes:
  - Fixed asking for password to list private repositories
  - Enable using notary client with username/password in a scripted fashion
  - Fix static compilation of client
  - Enforce TUF version to be >= 1, previously 0 was acceptable although unused
  - json.RawMessage should always be used as *json.RawMessage due to concepts of addressability in Go and effects on encoding

Thank you to HuKeping and liron-l for contributions to v0.3.0.

**Comment by riyazdf** [comment]
Closing since `CHANGELOG.md` has been updated 👍
