### ISSUE TITLE
Review docs for correctness re. 0.3 release

### ISSUE THREAD

**Issue by endophage** [docker/notary#739]

**Comment by riyazdf** [comment]
Adding for bookkeeping: also ensure that docs for notary and DCT are deployed

**Comment by riyazdf** [comment]
@SvenDowideit is helping us deploy notary docs; DCT docs have already been updated.

For now, the `v0.3.0` tag works for 0.3, though we might also want to include https://github.com/docker/notary/pull/743 if/when it's merged

**Comment by riyazdf** [comment]
closing, this has been resolved.
