### ISSUE TITLE
Handle GUN names with weird characters or path traversals

### ISSUE THREAD

**Issue by cyli** [docker/notary#742]
Maybe we want to specify a grammar or other restrictions on the GUN name.

For example, here's [distribution's reference grammar for an image reference](https://godoc.org/github.com/docker/distribution/reference) and here's [distribution's reference grammar for auth, including the resource name](https://github.com/docker/distribution/blob/master/docs/spec/auth/scope.md).

Notary has less restrictions, but:
1.  We use the image name as a REST resource, so we may want to limit non-URL-safe characters.  Although we should at least URLencode the image name, since if we wanted to support GUNs that include IPV6 URIs, the [RFC](https://tools.ietf.org/html/rfc3986) suggests that the URI look like `[ipv6 address]:port` and we'd have to urlencode the `[` and `]` (see https://stackoverflow.com/questions/40568/are-square-brackets-permitted-in-urls)
2.  Also because of URLs, we may want to avoid image names like `../../../../../../`.  Go's URL handler will probably just clean that up so you end up with the wrong URL, which will result in an unhelpful error message.  If you initialize on the client with an image name like that, it will probably write the files to the wrong place.

**Comment by cyli** [comment]
@endophage Tested this with a basic Go server that just printed out the URL when it received a request, and then used telnet to connect:

`http://localhost:8080/foo/../../bar` returned a 301 redirect to `http://localhost:8080/bar`, and `http://localhost:8080/foo//bar` returned a 301 redirect to `http://localhost:8080/foo/bar`, so it looks like our REST api cleans stuff up for those paths.

**Comment by endophage** [comment]
Closing. Go's http server cleans URLs of things like path traversals before they reach the gorilla routing.
