### ISSUE TITLE
Document libltdl7 dependency

### ISSUE THREAD

**Issue by BenHall** [docker/notary#745]
After trying the 0.3 linux build it failed to load because of a missing `libltdl.so.7`. It was fixed by installing 
`apt-get install libltdl7` but could be useful to document it somewhere.

Ideally, it would be nice if I didn't have to include the dependency :)

**Comment by HuKeping** [comment]
Isn't `apt-get install libltdl-dev` help?

**Comment by endophage** [comment]
Hi BenHall

The goal is to provide debs (and rpms), but the team has no expertise in creating them and every time I get some time to spend on it I end up making slow progress due to pretty appalling, fragmented, documentation.

We can in the meantime add documentation on the dependencies.

**Comment by riyazdf** [comment]
hi @BenHall, we have a static linux build that you can try for 0.3 and we're actively trying to improve our release process.

As @HuKeping notes, we list `apt-get install libltdl-dev` as a dependency for [building notary ](apt-get install libltdl-dev).

I'll close this issue for the time being, but feel free to open another issue or re-open this one if you have further issues or suggestions :)
