### ISSUE TITLE
Problem when delete a signed image and repush it

### ISSUE THREAD

**Issue by omauger** [docker/notary#759]
I have a Docker Trusted Registry with a configured Notary Service.

When I create an image and signed it, I don't have any problem.
But when I delete this image and repush it, the image don't appear in my Docker Trusted Registry interface.

I don't have error messages in Trusted Registry or Notary server/signer.
I use Docker Trusted Registry v2.0.0 and Notary server and signer 0.3.0.

**Comment by endophage** [comment]
Hi @omauger, could you file an issue with our support team as this doesn't sounds like a Notary issue if the image is not showing up at all in the Docker Trusted Registry interface. That team will investigate and work with us if they find anything relevant to Notary.

Support site (requires login with docker hub credentials): https://support.docker.com

**Comment by endophage** [comment]
Closing as this doesn't appear to be relevant to Notary and no additional information has been provided.
