### ISSUE TITLE
Fix error responses from server so they get logged

### ISSUE THREAD

**Issue by endophage** [docker/notary#766]
We're logging the error from serving an error. We should always log the error that was served to ensure reporting systems get triggered.

Use an appropriate log level. Anything in the 5XX range should get logged as an error. 4XX should probably be info.

**Comment by cyli** [comment]
https://github.com/docker/notary/blob/master/server/timestamp/timestamp.go#L65 is getting logged as an error, and it should probably not be an error - this can happen if someone has metadata cached locally, and then tries to pull from a server that doesn't know about that metadata.  For instance if they uploaded signed metadata to one notary server, and then switched notary servers and tried to pull.
