### ISSUE TITLE
Not detecting tampering of middle layers ? 

### ISSUE THREAD

**Issue by mkonakan** [docker/notary#774]
I tried tampering the manifest file of an image and well it gives me the error which indicates that the manifest file was tampered and could not be validated. Great! It was as expected. 

What if we tamper any of the middle layers in the image? I tampered f4e00...layer (2nd layer in the manifest file) as shown in screenshots. When I modify the manifest , it shows me that manifest is modified and could not be verified but when I modify the layer data, why does it not give me any error that layer has been tampered? 

Image downloaded:
![1](https://cloud.githubusercontent.com/assets/18063453/15916480/4459c62e-2da8-11e6-980f-288b50544852.PNG)

 Manifest file and 2nd layer which is being modified:
![2](https://cloud.githubusercontent.com/assets/18063453/15916490/63510808-2da8-11e6-8fb9-83b5614315e7.PNG)

Manifest modification:
![4](https://cloud.githubusercontent.com/assets/18063453/15916508/85703422-2da8-11e6-8728-f4f623063431.PNG)

Result of Manifest modification: 
![5](https://cloud.githubusercontent.com/assets/18063453/15916516/9dde7780-2da8-11e6-9775-7f8bf70b06b2.PNG)

Manipulating 2nd layer in manifest file:
a. 
![a](https://cloud.githubusercontent.com/assets/18063453/15916545/d47d6bf2-2da8-11e6-9b2a-0a379c794540.PNG)

b. 
![b](https://cloud.githubusercontent.com/assets/18063453/15916550/d9372be2-2da8-11e6-88f3-a7424efae248.PNG)

Result of layer modification: 

![result](https://cloud.githubusercontent.com/assets/18063453/15916574/19c3de08-2da9-11e6-9af2-138b7a81323d.PNG)

So, despite layer being modified, image is being downloaded? Also, I remember @diogomonica saying in his presentation that it works here as a hash chain i.e, Notary ensures that manifest file is sent securely and then Docker does hash chain. So, is not Docker actually checking if the value inside the sha256 folder is getting changed? Is it just extracting the hashed folder even the data inside it is changed? 

Is it a bug or am I missing something? Kindly help!

**Comment by mkonakan** [comment]
@cyli any thoughts on this?

**Comment by diogomonica** [comment]
The reason why the second command works is because the second time around the data is already cached locally, and so it isn't actually being downloaded or verified.

If you look at the output of the command, it is using that layer from cache: "Image is up to date for sandboxregistry:5000/test/youtrack@sha256:12dd344..."

To recreate my demo you have to clear the cache between every invocation of pull.

**Comment by mkonakan** [comment]
@diogomonica Thanks for the quick response. 

I did Expect this :+1:  Can you please let me know the command for clearing the cache before pull. Is there some kind of -clear-cache flag etc?

This way, are we not delaying alerting the user/enterprise about the intrusion till they clear the cache and pull it next time? Maybe something like an operation to check if everything is fine at the registry level before downloading makes more sense in terms of security (I believe)? Are you people currently not following this because of overhead or for any other reason?

**Comment by diogomonica** [comment]
you can follow these steps to remove local containers and images: https://techoverflow.net/blog/2013/10/22/docker-remove-all-images-and-containers/

@mkonakan Docker Content Trust and Notary will ensure that you never pull malicious data. So in fact we do exactly what you said: we check if everything is fine with the manifest before downloading any layers.

**Comment by mkonakan** [comment]
before "downloading" any layers is what you said and I agree with it :) but what I am concerned is about downloading the cached content despite file on registry getting tampered. This would delay enterprises in getting to know about their attack / tampering which might not be desired in many cases. 

However, seems this issue is already being discussed in - https://github.com/docker/docker/pull/16609. Will follow up there. Thanks.

**Comment by diogomonica** [comment]
mkonakan, this sentence makes no sense: `I am concerned is about downloading the cached content`.

If the content is caches *locally*, there is no download operation executed. The only way for an attacker to tamper with the data, is to have root access to the filesystem and change Docker's content-addressable store. And if an attacker has the ability to modify a root-owned filesystem on you're host, docker is the least of your worries.

**Comment by mkonakan** [comment]
Apologies. I should rephrase it as "getting the cached content". 
P.S: I am not referring to the my host where docker is hosted but maybe on a remote registry.

**Comment by diogomonica** [comment]
I just don't understand what you're trying to do.

If we agree that no docker deamon will be ever be able to be convinced to pull malicious data from a remote registry, even if the remote registry is tampered with, what are you trying to accomplish here?

**Comment by mkonakan** [comment]
Hey, 

I am really not sure whats making you to get confused in this. What I said is clear and simple - When someone tampers a image layer in remote registry ("similar" to the one you demonstrated in your presentation), I am not able to detect it immediately "unless" I remove my local cache. (P.S: I agree we are not getting any malicious data). So, I also mentioned that this issue seems to be discussed on the thread I mentioned above and hence, I am clear now. Thanks !
