### ISSUE TITLE
Please tag releases consistently (semantic versioning is good)

### ISSUE THREAD

**Issue by onlyjob** [docker/notary#782]
Notary could benefit from consistent tagging of releases.
At the moment two different versioning schemes co-exist: _vN.M_ and _docker-vA.B-C_.

It would be better to tag semantically and consistently as _vA.B.C_ (for example _0.3.1_ for new release). Please avoid non-semver _docker-_ tags.

Read more about versioning:
- http://semver.org/
- https://en.wikipedia.org/wiki/Software_versioning
- [Debian Upstream Guide](https://wiki.debian.org/UpstreamGuide#Releases_and_Versions).

Thanks.

**Comment by cyli** [comment]
Hi @onlyjob!  Thank you for your suggestions.  We try to re-vendor notary into docker on a regular basis in order to prevent the diffs from being too large, since docker reviews the code from dependency updates, and we tag these commits so that docker can track them in this repository.  However, those re-vendorings are not necessarily releases - they may contain only minor changes or a partial feature set.

Our actual releases, v0.1, v0.2, and v0.3, are the ones that include changelogs and binaries, are semantically versioned, and have a more coherent series of features or bugfixes added.

**Comment by onlyjob** [comment]
Thanks, @cyli. Please remember that vendoring is not a fix for inconsistent tags. I suggest to use tags like v0.2.2, v0.3.1 for Docker vendoring. If it is not possible then please use compatibility tags when one commit is tagged twice using different versioning schemes.

This ticket represent practical problem of building Docker in Debian against tagged release of Notary which is packages separately (not vendored).

**Comment by cyli** [comment]
@onlyjob Sorry, could you please elaborate on the problem you are having with building in debian?  Is it not possible to just ignore tags that aren't of a particular format?  

We were trying to avoid vendoring tags that are semver'd, because that'd indicate an actual upgrade for which we'd have to provide changelogs and binaries.  Basically, we don't release on as regular a schedule as we vendor into docker.

**Comment by cyli** [comment]
@onlyjob Would tagging the vendored versions with something like `v0.4.0-dev1` be ok for you, to indicate that it may not even be in alpha release stage?

**Comment by onlyjob** [comment]
It is not a problem of ignoring tags. Quite contrary it is difficulty to pick up inconsistent tags because Docker FTBFS with any released version of Notary and packaging tagged docker version of Notary breaks normal versioning...

I would not encourage releasing on schedule but Docker should not depend on unreleased snapshots between releases. It shouldn't be too hard to coordinate release if Docker needs a version bump in Notary...

**Comment by cyli** [comment]
@onlyjob Oh interesting - so you are trying to build notary source debs as well as docker source debs?  Also, would an alpha version like `0.4.0-a1` be sufficient to not break things?

**Comment by cyli** [comment]
Also to be clear, is this mainly for official releases of docker?  Or do you also need this for in-between releases of docker?

**Comment by onlyjob** [comment]
At the moment Docker is a main user of Notary but we build all components separately. Alpha versioning you suggest is not great because of dash (`-`) character (see Debian Upstream Guide). This is for official releases of Docker and for in-between releases of Notary as well. :)
It could be that Notary is uploaded first in order to prepare all dependencies before building new release of Docker. I hope it make sense. Thanks.

**Comment by cyli** [comment]
Ah ok - thank you for explaining!  We can certainly make a better effort to
accommodate this moving forward for docker releases at least.

So to summarize to ensure that I have all the details right:

You would like the versions of notary that are vendored into the final
releases of docker to be semver'ed without any RC or alpha designations.

In between docker releases, if we do intermediate vendors that are more
work in progress, the tags don't matter as much?  (Little fuzzier about
whether you required all tags to be consistent, or just the ones that
correspond to the docker releases and the official notary releases).

And you mainly need this moving forward, and as opposed to needing
everything retroactively tagged?

Thanks!

**Comment by onlyjob** [comment]
Thank you @cyli.
As usual, non production ready releases can be tagged with "rc", "alpha", "beta" or whatever mark is appropriate.
I'm not asking for any retrospective re-tagging. 

At the moment the major difficulty of building Docker is grpc version mismatch (#778) that cause FTBFS in Notary... :(

**Comment by endophage** [comment]
Hi @onlyjob, just want to make sure I understand your problem and request completely clearly. 

You're asking that when we vendor into the docker/docker repository, we always vendor a semantically tagged version?

Are you trying to package the Notary CLI as its own package and match versions between Docker and the Notary package?

**Comment by onlyjob** [comment]
Exactly. :)
Thank you for understanding, @endophage.

**Comment by endophage** [comment]
@onlyjob so we're already using semantic versioning (as of v0.2.0) and we can certainly tag each time we vendor into docker. However as the release cycles are not syncronized, it's typically not appropriate to release the version of notary that was vendored into Docker. The version vendored into docker represents library level updates. If you release that version as the standalone CLI, it will often be missing functionality.

**Comment by onlyjob** [comment]
We have no intention to release docker-vendored Notary as standalone package. It is the other way round: we can't reuse Notary to build Docker because of tagging mess in Notary and because vendoring of Notary do not stick to semantic releases.

**Comment by endophage** [comment]
I understand what you're saying. I'm trying to explain if we vendor say v0.4.0 into a docker release, the actual version of Notary that you'll want to distribute is likely to be v0.4.1, but that won't be vendored into docker until the _next_ docker release.

**Comment by onlyjob** [comment]
Fair enough. That should work. Thank you.

**Comment by endophage** [comment]
We're only using semantic versions now and vendoring them into docker. Closing.
