### ISSUE TITLE
notary-Linux-static-amd64 reports different git commit to v0.3.0 tag

### ISSUE THREAD

**Issue by djs55** [docker/notary#788]
Maybe this is my misunderstanding but the github release has tag `v0.3.0` and reports git sha `658a25c4efe1cd5e7151bd9bd4dcb99bc698a4b8` but the Linux static binary attached to the release reports
```
$ sha256sum notary-Linux-static-amd64
7664d845f4d2422749aedf9eecbdaaf066effbbab5bc77512b5b0b8c58f2d5ba  notary-Linux-static-amd64

$ ./notary-Linux-static-amd64 version
notary
 Version:    0.3
 Git commit: 205666e
```
I'd like to recompile a `notary` binary from source that's as similar as possible to 0.3, but I don't know whether I should start with 205666e or the v0.3.0 tag. I notice that the `NOTARY_VERSION` in the v0.3.0 tree still has `0.2` which I think means binaries built from that will still report version 0.2.

**Comment by riyazdf** [comment]
Thanks for finding this, I've standardized the release to use the same commit `658a25c` - unfortunately the 0.3 release missed the `NOTARY_VERSION` file upgrade so we may release a 0.3.1 in the near future to account for this.
