### ISSUE TITLE
log / error interpretation

### ISSUE THREAD

**Issue by bgrissin** [docker/notary#790]
Can I get some interpretation for what the errors means (i.e. the 200 messages) and why it is failing?  thnx

The push refers to a repository [fqdn/rhel/rhel7]
abab321ee7e0: Layer already exists
7.1: digest: sha256:xxxxxxxxx size: 1543
Signing and pushing trust metadata
DEBU[0000] reading certificate directory: /home/user/.docker/tls/fqdn
DEBU[0000] crt: /home/user/.docker/tls/fqdn/ca.crt
DEBU[0000] crt: /home/user/.docker/tls/fqdn/dockerca.crt
DEBU[0000] Failed to initialize PKCS11 environment: no library found.
DEBU[0000] Adding cert with certID: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
DEBU[0000] Adding cert with certID: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
DEBU[0000] entered ValidateRoot with dns: fqdn/rhel/rhel7
DEBU[0000] found the following root keys: [xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx]
DEBU[0000] found 1 valid leaf certificates for fqdn/rhel/rhel7
DEBU[0000] found 1 valid root certificates for fqdn/rhel/rhel7
DEBU[0000] entering root certificate rotation for: fqdn/rhel/rhel7
DEBU[0000] Adding cert with certID: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
DEBU[0000] ignoring certificate addition to: fqdn/rhel/rhel7
DEBU[0000] Root validation succeeded for fqdn/rhel/rhel7
DEBU[0000] updating TUF client
DEBU[0000] Downloading Timestamp...
DEBU[0000] 200 when retrieving metadata for timestamp
DEBU[0000] timestamp role has key IDs: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
DEBU[0000] verifying signature for key ID: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
DEBU[0000] successfully verified downloaded timestamp
DEBU[0000] Downloading Snapshot...
DEBU[0000] hash of snapshot in cache did not match expected hash, must download
DEBU[0000] Could not parse snapshot, must download
DEBU[0000] received HTTP status 404 when requesting snapshot.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.
DEBU[0000] Client Update (Snapshot): snapshot.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx trust data unavailable. Has a notary repository been initialized?
DEBU[0000] Error occurred. Root will be downloaded and another update attempted
DEBU[0000] Downloading Root...
DEBU[0000] didn't find a cached root, must download
DEBU[0000] 200 when retrieving metadata for root
DEBU[0000] verifying root with existing keys
DEBU[0000] root role has key IDs: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
DEBU[0000] verifying signature for key ID: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
DEBU[0000] continuing b/c keyid lookup was nil: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
DEBU[0000] root did not verify with existing keys
DEBU[0000] Client Update (Root):valid signatures did not meet threshold
Warning: potential malicious behavior - trust data has insufficient signatures for remote repository fqdn/rhel/rhel7: valid signatures did not meet threshold

**Comment by riyazdf** [comment]
Hi @bgrissin, could we please get some additional context about how you got into this state?  It would be very helpful.

To explain some of this output:

`DEBU[0000] Failed to initialize PKCS11 environment: no library found.` - not a real error to worry about, just means you didn't use a yubikey

```
DEBU[0000] hash of snapshot in cache did not match expected hash, must download
DEBU[0000] Could not parse snapshot, must download
DEBU[0000] received HTTP status 404 when requesting snapshot.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.
DEBU[0000] Client Update (Snapshot): snapshot.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx trust data unavailable. Has a notary repository been initialized?
DEBU[0000] Error occurred. Root will be downloaded and another update attempted
```
Snapshot data failed to verify, so your notary client is re-downloading root data.

```
DEBU[0000] root role has key IDs: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
DEBU[0000] verifying signature for key ID: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
DEBU[0000] continuing b/c keyid lookup was nil: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
DEBU[0000] root did not verify with existing keys
DEBU[0000] Client Update (Root):valid signatures did not meet threshold
Warning: potential malicious behavior - trust data has insufficient signatures for remote repository fqdn/rhel/rhel7: valid signatures did not meet threshold
```
Your root metadata didn't verify -- did you rotate trust keys or pull from an untrusted source?

**Comment by riyazdf** [comment]
Closing this for now since we haven't gotten more detail, but please feel free to re-open or file a new issue if something comes up
