### ISSUE TITLE
Increase/decrease logging level on notary-signer

### ISSUE THREAD

**Issue by HuKeping** [docker/notary#791]
For people who would like to try some contribute to Notary :)

For now we have already supported increasing/decreasing logging level on notary server side #748 , and it would be nice to have that functionality also on notary signer side.

Tips: 
What you need to do would like to be:
- Embed  a `setupSignalTrap()` into the notary-signer booting process.
- Add a handler to deal with those captured signals.
- Add some test for your handler
- Add some docs about it  

The infra you might want to use for this feature are:
- `NotarySupportedSignals ` in `const.go`
- `AdjustLogLevel()` to increase/decrease logging in `utils/configuration.go`

**Comment by cyli** [comment]
Fixed by #970
