### ISSUE TITLE
Refactor server/signer tests to be able to test multiple DBs (like rethink)

### ISSUE THREAD

**Issue by cyli** [docker/notary#797]
It'd be nice to be able to run our storage tests against actual DBs - while we use an ORM for sql-like DBs and test against a sqlite database, our ORM may not support some of the functionality we use.

And there is no fake rethink DB right now to test, so we'd have to test our rethink code against a real DB.

**Comment by riyazdf** [comment]
Closing after @cyli's awesome work in https://github.com/docker/notary/pull/824, https://github.com/docker/notary/pull/854, and https://github.com/docker/notary/pull/863
