### ISSUE TITLE
Client is always in offline state

### ISSUE THREAD

**Issue by ashishjain14** [docker/notary#803]
I am seeing the following issue every time I query the notary server. Here is a complete debug log

notary -s https://localhost:4443 -d ~/.docker/trust list localhost:5000/ubuntu -D
DEBU[0000] Configuration file not found, using defaults 
DEBU[0000] Using the following trust directory: /root/.docker/trust 
**ERRO[0000] could not reach https://localhost:4443: Get https://localhost:4443/v2/: x509: certificate signed by unknown authority** 
INFO[0000] continuing in offline mode                   
DEBU[0000] Failed to initialize PKCS11 environment: no library found 
DEBU[0000] entered ValidateRoot with dns: localhost:5000/ubuntu 
DEBU[0000] found the following root keys: [fa5bb50c062408fd23353a4b63047ae1017468ff0273a03c2cbf3180c2507ac0] 
DEBU[0000] found 1 valid leaf certificates for localhost:5000/ubuntu: fa5bb50c062408fd23353a4b63047ae1017468ff0273a03c2cbf3180c2507ac0 
DEBU[0000] found no currently valid root certificates for localhost:5000/ubuntu, using trust_pinning config to bootstrap trust 
DEBU[0000]  role has key IDs: fa5bb50c062408fd23353a4b63047ae1017468ff0273a03c2cbf3180c2507ac0 
DEBU[0000] verifying signature for key ID: fa5bb50c062408fd23353a4b63047ae1017468ff0273a03c2cbf3180c2507ac0 
DEBU[0000] Root validation succeeded for localhost:5000/ubuntu 
DEBU[0000] entered ValidateRoot with dns: localhost:5000/ubuntu 
DEBU[0000] found the following root keys: [fa5bb50c062408fd23353a4b63047ae1017468ff0273a03c2cbf3180c2507ac0] 
DEBU[0000] found 1 valid leaf certificates for localhost:5000/ubuntu: fa5bb50c062408fd23353a4b63047ae1017468ff0273a03c2cbf3180c2507ac0 
DEBU[0000] found no currently valid root certificates for localhost:5000/ubuntu, using trust_pinning config to bootstrap trust 
DEBU[0000]  role has key IDs: fa5bb50c062408fd23353a4b63047ae1017468ff0273a03c2cbf3180c2507ac0 
DEBU[0000] verifying signature for key ID: fa5bb50c062408fd23353a4b63047ae1017468ff0273a03c2cbf3180c2507ac0 
DEBU[0000] Root validation succeeded for localhost:5000/ubuntu 
DEBU[0000] updating TUF client                          
DEBU[0000] Loading timestamp...                         
DEBU[0000] error downloading timestamp: client is offline 
DEBU[0000] client is offline                            
WARN[0000] Error while downloading remote metadata, using cached timestamp - this might not be the latest version available remotely 
DEBU[0000] timestamp role has key IDs: 8a7186ae76bf6b5c832414f739e9c17ca9a50bd2d1bb132cd41864a69eae9d88 
DEBU[0000] verifying signature for key ID: 8a7186ae76bf6b5c832414f739e9c17ca9a50bd2d1bb132cd41864a69eae9d88 
DEBU[0000] successfully verified cached timestamp       
DEBU[0000] Loading snapshot...                          
DEBU[0000] snapshot role has key IDs: 3677ff923e9d3c3292908a8ff4a8dd8060bb23913f8f1b45b7aad2ce2a88458e 
DEBU[0000] verifying signature for key ID: 3677ff923e9d3c3292908a8ff4a8dd8060bb23913f8f1b45b7aad2ce2a88458e 
DEBU[0000] successfully verified cached snapshot        
DEBU[0000] Loading targets...                           
DEBU[0000] targets role has key IDs: be2603670b6256e3fdd706f3181ca340673f20d4fd520bcb9a00b07dea5a2d47 
DEBU[0000] verifying signature for key ID: be2603670b6256e3fdd706f3181ca340673f20d4fd520bcb9a00b07dea5a2d47 
DEBU[0000] successfully verified cached targets         
  NAME                                DIGEST                                SIZE (BYTES)    ROLE    
----------------------------------------------------------------------------------------------------
  15     15e2ba0b5e9d02f62a16332bf714732202d14b5930be31ec84421ee90ecff822   1334           targets  

Since the notary server is unreachable I see few errors. Notary server is very well running and is reachable on port 4443.

**Comment by riyazdf** [comment]
hi @ashishjain14 - how are you running notary server?  The reason I ask is that it looks like notary server is indeed running, but that your notary CLI does not trust its certificate and is therefore refusing to connect.

If you're running notary server using the compose files we've provided, you'll need to specify the `root-ca.crt` file that we've included in the repo in the client's config file -- see step 2 in this section of the [README](https://github.com/docker/notary#getting-started-with-the-notary-cli) to ensure you're specifying this CA cert.

**Comment by ashishjain14** [comment]
Thank you that indeed was the issue. There are couple of warnings still I see in the debug logs one related to failed PKCS11 environment & another one on no valid root certificates.

notary -s https://localhost:4443 -d ~/.docker/trust list localhost:5000/ubuntu -D
DEBU[0000] Using the following trust directory: /root/.docker/trust 
DEBU[0000] Trusting 1 certs                             
**DEBU[0000] Failed to initialize PKCS11 environment: no library found** 
DEBU[0000] entered ValidateRoot with dns: localhost:5000/ubuntu 
DEBU[0000] found the following root keys: [fa5bb50c062408fd23353a4b63047ae1017468ff0273a03c2cbf3180c2507ac0] 
DEBU[0000] found 1 valid leaf certificates for localhost:5000/ubuntu: fa5bb50c062408fd23353a4b63047ae1017468ff0273a03c2cbf3180c2507ac0 
**DEBU[0000] found no currently valid root certificates for localhost:5000/ubuntu, using trust_pinning config to bootstrap trust** 
DEBU[0000]  role has key IDs: fa5bb50c062408fd23353a4b63047ae1017468ff0273a03c2cbf3180c2507ac0 
DEBU[0000] verifying signature for key ID: fa5bb50c062408fd23353a4b63047ae1017468ff0273a03c2cbf3180c2507ac0 
DEBU[0000] Root validation succeeded for localhost:5000/ubuntu 
DEBU[0000] entered ValidateRoot with dns: localhost:5000/ubuntu 
DEBU[0000] found the following root keys: [fa5bb50c062408fd23353a4b63047ae1017468ff0273a03c2cbf3180c2507ac0] 
DEBU[0000] found 1 valid leaf certificates for localhost:5000/ubuntu: fa5bb50c062408fd23353a4b63047ae1017468ff0273a03c2cbf3180c2507ac0 
DEBU[0000] found no currently valid root certificates for localhost:5000/ubuntu, using trust_pinning config to bootstrap trust 
DEBU[0000]  role has key IDs: fa5bb50c062408fd23353a4b63047ae1017468ff0273a03c2cbf3180c2507ac0 
DEBU[0000] verifying signature for key ID: fa5bb50c062408fd23353a4b63047ae1017468ff0273a03c2cbf3180c2507ac0 
DEBU[0000] Root validation succeeded for localhost:5000/ubuntu 
DEBU[0000] updating TUF client                          
DEBU[0000] Loading timestamp...                         
DEBU[0000] 200 when retrieving metadata for timestamp   
DEBU[0000] timestamp role has key IDs: 8a7186ae76bf6b5c832414f739e9c17ca9a50bd2d1bb132cd41864a69eae9d88 
DEBU[0000] verifying signature for key ID: 8a7186ae76bf6b5c832414f739e9c17ca9a50bd2d1bb132cd41864a69eae9d88 
DEBU[0000] timestamp role has key IDs: 8a7186ae76bf6b5c832414f739e9c17ca9a50bd2d1bb132cd41864a69eae9d88 
DEBU[0000] verifying signature for key ID: 8a7186ae76bf6b5c832414f739e9c17ca9a50bd2d1bb132cd41864a69eae9d88 
DEBU[0000] successfully verified downloaded timestamp   
DEBU[0000] Loading snapshot...                          
DEBU[0000] snapshot role has key IDs: 3677ff923e9d3c3292908a8ff4a8dd8060bb23913f8f1b45b7aad2ce2a88458e 
DEBU[0000] verifying signature for key ID: 3677ff923e9d3c3292908a8ff4a8dd8060bb23913f8f1b45b7aad2ce2a88458e 
DEBU[0000] successfully verified cached snapshot        
DEBU[0000] Loading targets...                           
DEBU[0000] targets role has key IDs: be2603670b6256e3fdd706f3181ca340673f20d4fd520bcb9a00b07dea5a2d47 
DEBU[0000] verifying signature for key ID: be2603670b6256e3fdd706f3181ca340673f20d4fd520bcb9a00b07dea5a2d47 
DEBU[0000] successfully verified cached targets         
  NAME                                DIGEST                                SIZE (BYTES)    ROLE    
----------------------------------------------------------------------------------------------------
  15     15e2ba0b5e9d02f62a16332bf714732202d14b5930be31ec84421ee90ecff822   1334           targets

**Comment by riyazdf** [comment]
Those debug statements are expected, the notary client is still validating the trust  metadata successfully.  I'll explain each a little further:

`DEBU[0000] Failed to initialize PKCS11 environment: no library found` - this is because the notary client is built with the pkcs11 tag, so it will try to initialize a `YubiStore` such that it can use a yubikey for root key operations.  This debug is just saying that notary couldn't find a yubikey and so it will just operate on keys in its filesystem instead.

`DEBU[0000] found no currently valid root certificates for localhost:5000/ubuntu, using trust_pinning config to bootstrap trust ` - this is indicating that there are no previous versions of the root file on disk to validate against, so notary will verify the signatures and certificate information on this root as usual and also optionally do any additional verification as indicated by the `trust_pinning` section of the client config if any options were given.

Please let us know if you have more questions!  I'll close this issue for now but feel free to re-open it or file a new issue if something else comes up
