### ISSUE TITLE
Discussion: Can we fully flatten the keystore?

### ISSUE THREAD

**Issue by endophage** [docker/notary#838]
We've discussed it internally on a number of occasions, I'd like to have the discussion with a larger group. 

## Current State

Keys are stored in a directory called `private` within you configured `trust_dir`. Root keys are stored in `private/root_keys/*.key`, delegation keys are stored in the top level of `private/tuf_keys/*.key`, and all other keys (targets, snapshot), are stored in `private/tuf_keys/<gun>/*.key`.

## Proposal

I'd like to flatten the entire key storage. All keys would be stored at `private/<CanonicalKeyID>.key`. The only interesting piece of information, the GUN of targets and snapshot keys, would be moved to the PEM headers, where we already store the role.

## Results

This will greatly simplify a lot of key management code. I would implement migration code that would run when filestorage for keys is initialized to move any existing keys to the new location, allowing us to fully remove all other code that has to be aware of the current pathing.

However, it would mean the scope of some keys becomes more opaque to a user digging around in the `private` directory. I have some big PRs open right now to do a lot of cleanup around key storage and import/export so my desire would be to ensure we have sufficient CLI functionality that nobody ever has to dig into `private`. We should not become beholden to, and unable to change, notary internal data structure decisions.

cc (a bunch of possibly interested parties) @HuKeping @andrewhsu @dnwake @ecordell @diogomonica @NathanMcCauley @riyazdf @cyli @avaid96

**Comment by diogomonica** [comment]
If the same key is being used for multiple repositories, would we add multiple headers?

This LGTM, even though I actually like the fact that right now a simple `tree .` tells me what keys are being used for what.

**Comment by HuKeping** [comment]
Yep, I also use `tree` to list those keys,  but it's non-blocking.

**Comment by ecordell** [comment]
👍 from me. I think in general the storage mechanism for keys (and metadata) should be decoupled on the client like it is in the server component. 

Is this also a feature request for `notary key tree`?

**Comment by endophage** [comment]
@diogomonica the directory layout does not provide a good mechanism to use a key across multiple guns, this change would enable that if we wanted it to and if we did, I think yes, we would want to store all GUNs in the headers.

@ecordell it seems like that might solve the use case @diogomonica and @HuKeping have described but I'd probably file a separate issue for that if this proposal is accepted.

**Comment by riyazdf** [comment]
👍  on proposal.

@ecordell @HuKeping: could we improve `notary key list` to be more clear for the `tree` use case?

**Comment by andrewhsu** [comment]
👍  from me as well. I like the simplified directory structure.

**Comment by HuKeping** [comment]
@riyazdf It's not in a hurry.
