### ISSUE TITLE
notary-server certificate expired at midnight

### ISSUE THREAD

**Issue by lewiada** [docker/notary#840]
the notary-server.crt included with the git clone just expired. hopefully a new one will be added soon?

**Comment by jsoler** [comment]
+1

**Comment by riyazdf** [comment]
@lewiada: new testing certs are on the way!

**Comment by lewiada** [comment]
awesome, thank you!  was just getting familiar with notary when they expired :-)

**Comment by riyazdf** [comment]
@lewiada just opened #842, so should be fixed soon!  You can check out that branch for now if you'd like to continue playing with the notary docker-compose setup :)

**Comment by lewiada** [comment]
pulled the branch and back in business!  Thanks for the quick turn around :-)
