### ISSUE TITLE
delegation roles doesn't publish successfully

### ISSUE THREAD

**Issue by HuKeping** [docker/notary#852]
There is a `targets` role which has three delegations roles `targets/distribution`, `targets/docker`, `targets/notary` under the GUN `huawei.com`:
```
$ notary delegation list huawei.com

          ROLE                    PATHS                                        KEY IDS                                THRESHOLD  
---------------------------------------------------------------------------------------------------------------------------------
  targets/distribution   huawei.com/distribution   bcfe06daf6db5916baa4f1389e32ebf282c17593f0b67e996fb46b4714fe99cd   1          
  targets/docker         huawei.com/docker         fff2024979a5282ca697b3b231f87499fbe8082cc2be7555329aa5d1bead5007   1          
  targets/notary         huawei.com/notary         6f5c271304f639c25df19b2da725d876ab04e62525cece6a01050c8cee15e4ff   1 
``` 

After I publish content(the README.MD of each repo) with delegation roles respectively , I get:
```
$ notary list huawei.com

               NAME                                             DIGEST                                SIZE (BYTES)           ROLE          
-------------------------------------------------------------------------------------------------------------------------------------------
  huawei.com/distribution/readme   d28f42179340667755eb8ae29101437ce5c60cec099d8d4820e4f4dd67b663f1   4984           targets/distribution  
  huawei.com/docker/readme         495cefcebf8b2ed4de71a4e54f2b11c2533114fe9e884dc1be4502ac2ba6d7de   13755          targets/docker        
  huawei.com/notary/readme         9d9e890af64dd0f44b8a1538ff5fa0511cc31bf1ab89f3a3522a9a581a70fad8   6563           targets/notary 
```

Then I publish the `huawei.com/docker/readme` with the `targets` role, which I get:
```
$ notary list huawei.com

               NAME                                             DIGEST                                SIZE (BYTES)           ROLE          
-------------------------------------------------------------------------------------------------------------------------------------------
  huawei.com/distribution/readme   d28f42179340667755eb8ae29101437ce5c60cec099d8d4820e4f4dd67b663f1   4984           targets/distribution  
  huawei.com/docker/readme         495cefcebf8b2ed4de71a4e54f2b11c2533114fe9e884dc1be4502ac2ba6d7de   13755          targets               
  huawei.com/notary/readme         9d9e890af64dd0f44b8a1538ff5fa0511cc31bf1ab89f3a3522a9a581a70fad8   6563           targets/notary 
```

Notice that the **ROLE** has changed from `targets/docker` to `targets` which I suppose is as expected since it was published by the `targets` role.

And here comes the problem, when I re-published it with the `targets/docker` role, the publishing process seems successfully(at least no error shown out), but the result was not expected.
```
$ notary list huawei.com

               NAME                                             DIGEST                                SIZE (BYTES)           ROLE          
-------------------------------------------------------------------------------------------------------------------------------------------
  huawei.com/distribution/readme   d28f42179340667755eb8ae29101437ce5c60cec099d8d4820e4f4dd67b663f1   4984           targets/distribution  
  huawei.com/docker/readme         495cefcebf8b2ed4de71a4e54f2b11c2533114fe9e884dc1be4502ac2ba6d7de   13755          targets               
  huawei.com/notary/readme         9d9e890af64dd0f44b8a1538ff5fa0511cc31bf1ab89f3a3522a9a581a70fad8   6563           targets/notary 
```

The **ROLE** is still `targets` not `targets/docker` and of course the `DIGEST` remains the same as well.

Is this intended or something wrong happened?

**Comment by riyazdf** [comment]
When we list targets, we perform a pre-order traversal of the delegation roles tree, which has targets at the root.  Once we've found a match for a particular target name, we don't override it if we find it in a later role in the tree.  This means if you run a `notary list` without any flags, we'll prioritize the `targets` role over other delegation roles.

However, `notary list` takes an optional `--roles` flag which can override this traversal to prioritize other roles - you can try running `notary list huawei.com -r targets/docker`

**Comment by endophage** [comment]
For some extra context, we implemented preorder because it was the simplest mechanism and was also suggested in the TUF spec. Structurally though, regardless of preorder or otherwise, there seems to be an expectation that a target that exists in 2 role that have a direct ancestor-descendant relationship, will always result in the ancestor (i.e. the role higher in the delegation tree) being the accepted version. 

This is because the ancestor at some point delegated control to the descendent, and should always be allowed to rescind that control in whole or part, by either removing the delegation, or publishing individual targets that shadow those of the delegation.

**Comment by HuKeping** [comment]
Thanks @riyazdf , the flag `--roles` does work, but what about the `notary verify` if the result with the flag and without the flag are ***different***.

Without the flag
```
$ notary list huawei.com -r targets/docker
                 NAME                                                DIGEST                                SIZE (BYTES)           ROLE           
-------------------------------------------------------------------------------------------------------------------------------------------------
  huawei.com/distribution/readme        495cefcebf8b2ed4de71a4e54f2b11c2533114fe9e884dc1be4502ac2ba6d7de   13755          targets                
  huawei.com/docker/readme              9d9e890af64dd0f44b8a1538ff5fa0511cc31bf1ab89f3a3522a9a581a70fad8   6563           targets/docker         
  huawei.com/notary/readme              9d9e890af64dd0f44b8a1538ff5fa0511cc31bf1ab89f3a3522a9a581a70fad8   6563           targets/notary 
```

With the flag

```
$ notary list huawei.com -r targets/docker
                 NAME                                                DIGEST                                SIZE (BYTES)           ROLE           
-------------------------------------------------------------------------------------------------------------------------------------------------
  huawei.com/distribution/readme        495cefcebf8b2ed4de71a4e54f2b11c2533114fe9e884dc1be4502ac2ba6d7de   13755          targets                
  huawei.com/docker/readme              9d9e890af64dd0f44b8a1538ff5fa0511cc31bf1ab89f3a3522a9a581a70fad8   6563           targets/docker         
  huawei.com/notary/readme              9d9e890af64dd0f44b8a1538ff5fa0511cc31bf1ab89f3a3522a9a581a70fad8   6563           targets/notary 
```

Notice that the DIGEST is different and when do the `notary verify` the `flagged` one will fail because the `notary verify` doesn't take a flag like `notary list` does.

**Comment by HuKeping** [comment]
@endophage does this make sense:
userA keeps signing and publishing  `ImageA` he was asked to. 
One day userA compromised and the master which of the same tenant as userA signed and published `ImageA` and then rotate the keys for userA and distribute those keys to userA and userA keeps doing his work.

**Comment by riyazdf** [comment]
@HuKeping you're correct that `notary verify` (and also `notary lookup`) does not currently take a roles flag, and that could be helpful to distinguish which hash to verify against.  Both CLI commands currently will default against checking against the metadata in the `targets` role first since they perform the same pre-order traversal -- I'll file a tracking issue.

That said, while this functionality isn't exposed in the CLI you could import the `client` package into existing golang code and call `ListTargets` with the role you wish to check for, along with `data.CheckHashes`

**Comment by HuKeping** [comment]
Do we must use the `preorder` or could it be possible that  list all of them, and use the latest version to show out.

And also, if I have secondary delegation roles, the `notary delegation list GUN` seems wouldn't list them.
```
$ notary delegation list huawei.com 

          ROLE                    PATHS                                        KEY IDS                                THRESHOLD  
---------------------------------------------------------------------------------------------------------------------------------
  targets/distribution   huawei.com/distribution   bcfe06daf6db5916baa4f1389e32ebf282c17593f0b67e996fb46b4714fe99cd   1          
  targets/docker         huawei.com/docker         fff2024979a5282ca697b3b231f87499fbe8082cc2be7555329aa5d1bead5007   1          
  targets/notary         huawei.com/notary         6f5c271304f639c25df19b2da725d876ab04e62525cece6a01050c8cee15e4ff   1   
```

Actually there are also `targets/notary/server` and `targets/notary/signer`

**Comment by riyazdf** [comment]
@HuKeping can you give #864 a try?  Thanks for pointing this issue out, and hopefully that fixes it (and adds a test so it doesn't fail again).  Most of our tests focus on delegation roles only one-level below targets, so unfortunately this seemed to have slipped past :(

**Comment by HuKeping** [comment]
@riyazdf seems works as expected, thanks @riyazdf 

So here remains the `notary list` one.

**Comment by riyazdf** [comment]
@HuKeping: so I understand what remains on this issue -- are you satisfied with just continuing this conversation on `notary verify` & `notary list` on this linked issue https://github.com/docker/notary/issues/857, or are there additional behaviors with `notary list` that you're curious about?  `notary list` will only list each target name once, and uses the `--roles` flag to perform different traversals - at the client library level, you might want to look at the [`GetAllTargetMetadataByName`](https://github.com/docker/notary/blob/master/client/client.go#L475) method, which gathers all signed content for a given target name

More than happy to address feedback on both topics :)

**Comment by HuKeping** [comment]
Hi @riyazdf , I was thinking why we should shadow those delegation targets while on traverse , what's the design purpose about that.

If one wants to get the trust content list from a service provider, let's say http://10.0.10.1:4443, what he need to do would like be `notary list xxx` other than `notary list xxx -r yyy` because he may not know the exactly targets roles as he is just a customer.

Besides, as @endophage mentioned up there, the expectation seems like  ancestor has a higher priority to descendant. But once the ancestor  touched the descendant's content, the ancestor has to keep maintain that content forever since the descendant's  publish will be shadowed by ancestor's.

**Comment by riyazdf** [comment]
@HuKeping we decided to only list each target name once, and this has worked well for downstream consumers like docker/docker which prioritizes the `targets/releases` role.  Maybe `notary lookup <GUN> <target>` could give information about all roles that the specific target name has been published to?

**Comment by cyli** [comment]
@HuKeping Also, if the ancestor no longer wants to maintain that content, they could explicitly remove that target, thus no longer shadowing the descendant.

**Comment by HuKeping** [comment]
> we decided to only list each target name once

Agree, one target should only has one copy of metadata to show up and to used to do the verification.
The problem is one target may have several metadata because both of the ancestor and descendant can publish and sign it, and there is not a overriding.
If there is some principle for example:
- the latest publishing is the right one
- ancestor's publishing is the right one
- descendant's publishing is the right one

In my opinion, neither or the last two make sense, the first one seems reasonable.

Why we need to keep several copy of metadata for one target, isn't using the latest more simpler?

**Comment by riyazdf** [comment]
@HuKeping I think that in the case of target name conflict, the ancestor's should be shown when listing targets unless the operator has another walking order they would like to prioritize (which they can do by passing roles).

This is because the ancestor can control the role data for its descendants (including valid keys), and so the ancestor is essentially an admin for its descendant roles.  The ancestor role can decide to promote its descendants targets if they wish with `notary addhash` (or `notary add` if they have the original file on-hand), or by deleting their shadowing target as @cyli mentions (assuming that the pre-order or other defined walking order will pick up the desired target).

It's possible to do more fine-grained checking of targets on a per-role basis with `GetTargets` and `GetAllTargetMetadataByName`, if you're using the notary client library like docker/docker does as well.  You may also want to keep several hashes of the same target name across delegation roles for auditing purposes.

All this said, if you're only interested in having the latest target be published, using delegations may not be necessary - the `targets` role could simply maintain all targets and ensure that only one copy is kept at any given time.

**Comment by HuKeping** [comment]
Thanks for the detail @riyazdf

**Comment by riyazdf** [comment]
@HuKeping - currently the signed delegations data you could use for auditing is viewable from the `notary list` command with the  `--role` flag values or from directly viewing the metadata files on-disk.

I think it might be nice to extend `notary lookup <GUN> <target>` to list all roles a given target is signed into, or to show this and more repo information in something like a `notary info <GUN>` command (see https://github.com/docker/notary/issues/550).  What do you think of these ideas, and is there another way to present this information that you think would be more useful?

**Comment by HuKeping** [comment]
I'm interested with both and going to extend `verify` with flag `--role` first.

**Comment by riyazdf** [comment]
@HuKeping sounds good - closing this issue in favor of https://github.com/docker/notary/issues/857
