### ISSUE TITLE
Consider purge of changelists

### ISSUE THREAD

**Issue by NathanMcCauley** [docker/notary#866]
If a changelist fails to upload, Docker currently holds on to it forever. The only recourse a user has is manual deletion.

Consider two changes:
1. Add a `changelist purge` mechanism to notary.
2. Have docker not use local changelist files, instead preferring to dynamically generate changelists upon `push`.

**Comment by HuKeping** [comment]
Not only Docker holds the failing changelist, Notary CLI holds that too.

**Comment by endophage** [comment]
That PR needs tests before merge but can be reviewed for behaviour

**Comment by riyazdf** [comment]
Closing after merging #856 with the `--reset` flag
