### ISSUE TITLE
fail uploads if tuf metadata set would not be considered valid by a client

### ISSUE THREAD

**Issue by NathanMcCauley** [docker/notary#88]
We should fail any tuf file uploads that would cause clients to fail to parse, verify, or otherwise consume the content on the server.

**Comment by endophage** [comment]
Only way to do this with any guarantee is to attempt parsing on the server. That has the potential to greatly increase memory usage.

Will add but just want everyone to be aware of the trade off.

**Comment by NathanMcCauley** [comment]
It is worth it. Memory consumption on the server doesn't matter nearly as much as making sure bad data never gets pushed.

**Comment by dmp42** [comment]
see #134
