### ISSUE TITLE
-p flag for auto-publish on staged commands

### ISSUE THREAD

**Issue by riyazdf** [docker/notary#885]
It'd be nice to have a `-p` flag (or similar) to automatically attempt to publish after staging a change in a notary CLI command.  For example: `notary init -p`, `notary add -p`, `notary remove -p`, `notary delegation add -p`, `notary delegation remove -p`, and `notary addhash -p`

**Comment by HuKeping** [comment]
Add command list:
- [X] notary init -p
- [X] notary add -p
- [X] notary remove -p
- [ ] notary delegation add -p
- [ ] notary delegation remove -p
- [ ] notary addhash -p
