### ISSUE TITLE
when I  use "docker-compose build " command to build notary, it comes some problems，how could I solve it 

### ISSUE THREAD

**Issue by rusirenye** [docker/notary#892]
Step 4 : RUN go get github.com/mattes/migrate
 ---> Running in 2d9d1c9a378e
package golang.org/x/net/context: unrecognized import path "golang.org/x/net/context" (https fetch: Get https://golang.org/x/net/context?go-get=1: dial tcp 216.58.221.241:443: i/o timeout)
package gopkg.in/inf.v0: unrecognized import path "gopkg.in/inf.v0" (https fetch: Get https://gopkg.in/inf.v0?go-get=1: dial tcp: lookup gopkg.in on 8.8.4.4:53: read udp 172.17.0.2:49441->8.8.4.4:53: i/o timeout)

**Comment by riyazdf** [comment]
Hi @rusirenye - I have not been able to reproduce this myself, but after searching around it seems like this might be related to the proxy network configuration issues described on https://github.com/golang/go/issues/12810?

**Comment by rusirenye** [comment]
@riyazdf  thank you very much.  I try to set network proxy environment variable  in docker file ,then go get github.com/mattes/migrate command works all right. It seems  that golang:1.6.3-alpine images container can't use host network proxy.

**Comment by riyazdf** [comment]
@rusirenye great to hear that we've diagnosed the issue!  As you mention, it seems like an issue with golang:1.6.3-alpine and proxy configuration -- I'm inclined to close the issue on notary but if you think that we could somehow mitigate the issue on our side feel free to re-open this issue or file another one.
