### ISSUE TITLE
notary list command show client off-line

### ISSUE THREAD

**Issue by rusirenye** [docker/notary#897]
when use notary list command 
```
root@dgp:~/notary#  notary -s https://notary.docker.io -d ~/.docker/trust list docker.io/library/alpine
* fatal: client is offline
```
and  My notary server is ok
```
root@dgp:~/notary# ping notary-server
PING notary-server (127.0.0.1) 56(84) bytes of data.
64 bytes from notary-server (127.0.0.1): icmp_seq=1 ttl=64 time=0.040 ms
64 bytes from notary-server (127.0.0.1): icmp_seq=2 ttl=64 time=0.043 ms
```
docker.io ping failed as fellow:
```
root@dgp:~/notary# ping docker.io
PING docker.io (52.203.138.237) 56(84) bytes of data.
^C
--- docker.io ping statistics ---
8 packets transmitted, 0 received, 100% packet loss, time 6999ms

```
So, I wonder that it'something wrong with my configure or installment. and can you give some advice to fix it.

**Comment by riyazdf** [comment]
hi @rusirenye, in the command you posted the `-s https://notary.docker.io` flag means that your notary client will try to connect to a notary server at that URL (which corresponds to the notary server that is deployed for Docker Hub).  If you instead want to connect to your local notary server, you can change the `-s` flag to point to that host.

Could you please try running your `notary list` command with the `-D` flag so we can see debug logs?

**Comment by HuKeping** [comment]
I'm agree with @riyazdf , it seems like the connection problem between notary-client and notary-server

**Comment by rusirenye** [comment]
Thank you @riyazdf . the notary list command with -D:
```
root@ubuntu14:~# notary -D  -s https://notary-server:4443  -d ~/.docker/trust list localhost:4443/collect
DEBU[0000] Using the following trust directory: /root/.docker/trust
DEBU[0000] Trusting certs with subjects: [0_1
                                             0  UUS1
                                                    0   U
CA10U
Uan Francisco10
Docker10U
Notary Testing CA]
ERRO[0000] could not reach https://notary-server:4443: Get https://notary-server:4443/v2/: Service Unavailable
INFO[0000] continuing in offline mode
DEBU[0000] Failed to initialize PKCS11 environment: no library found.
DEBU[0000] Adding cert with certID: c6b86f21ae272f3ae27b8da8a5762df97f09d6d0604ab49dd1d9920c6e25b65b
DEBU[0000] Adding cert with certID: 98b97af634d37a4a53f2e2a4c582e14316bb5a558af8da3ab93f94674619155a
DEBU[0000] entered ValidateRoot with dns: localhost:4443/collect
DEBU[0000] found the following root keys: [98b97af634d37a4a53f2e2a4c582e14316bb5a558af8da3ab93f94674619155a]
DEBU[0000] found 1 valid leaf certificates for localhost:4443/collect
DEBU[0000] found 1 valid root certificates for localhost:4443/collect
DEBU[0000] entering root certificate rotation for: localhost:4443/collect
DEBU[0000] Adding cert with certID: 98b97af634d37a4a53f2e2a4c582e14316bb5a558af8da3ab93f94674619155a
DEBU[0000] ignoring certificate addition to: localhost:4443/collect
DEBU[0000] Root validation succeeded for localhost:4443/collect
DEBU[0000] updating TUF client
DEBU[0000] Downloading Timestamp...
DEBU[0000] no cached timestamp available
DEBU[0000] Client Update (Timestamp): client is offline
DEBU[0000] Error occurred. Root will be downloaded and another update attempted
DEBU[0000] Downloading Root...
DEBU[0000] didn't find a cached root, must download
DEBU[0000] Client Update (Root):client is offline

* fatal: client is offline
```
and  docker ps information an follow:

```
root@ubuntu14:~# docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                                             NAMES
bf5638ae7735        notary_server       "/usr/bin/env sh -c '"   2 days ago          Up 2 days           0.0.0.0:4443->4443/tcp, 0.0.0.0:32770->8080/tcp   notary_server_1
f71febd56ed7        notary_signer       "/usr/bin/env sh -c '"   2 days ago          Up 2 days                                                             notary_signer_1
a41e0acfdc41        mariadb:10.1.10     "/docker-entrypoint.s"   2 days ago          Up 2 days           3306/tcp                                          notary_mysql_1

```

**Comment by HuKeping** [comment]
`could not reach https://notary-server:4443`

Could you please `ping notary-server` to see if it was accessible

**Comment by rusirenye** [comment]
`root@dgp:~/notary# ping notary-server
PING notary-server (127.0.0.1) 56(84) bytes of data.
64 bytes from notary-server (127.0.0.1): icmp_seq=1 ttl=64 time=0.045 ms
64 bytes from notary-server (127.0.0.1): icmp_seq=2 ttl=64 time=0.043 ms
64 bytes from notary-server (127.0.0.1): icmp_seq=3 ttl=64 time=0.049 ms
64 bytes from notary-server (127.0.0.1): icmp_seq=4 ttl=64 time=0.046 ms
`

**Comment by rusirenye** [comment]
`
root@dgp:~/notary# ping notary-server
PING notary-server (127.0.0.1) 56(84) bytes of data.
64 bytes from notary-server (127.0.0.1): icmp_seq=1 ttl=64 time=0.045 ms
64 bytes from notary-server (127.0.0.1): icmp_seq=2 ttl=64 time=0.043 ms
64 bytes from notary-server (127.0.0.1): icmp_seq=3 ttl=64 time=0.049 ms
64 bytes from notary-server (127.0.0.1): icmp_seq=4 ttl=64 time=0.046 ms

`

**Comment by cyli** [comment]
Could you have a look at your notary-server logs?  `docker-compose logs server` or `docker-compose logs` for all the server and signer and DB logs?  

I ask because I'm wondering if, in `ERRO[0000] could not reach https://notary-server:4443: Get https://notary-server:4443/v2/: Service Unavailable`, "Service Unavailable" means that the server is 500'ing.

**Comment by rusirenye** [comment]
thank you very much @cyli @HuKeping @riyazdf 
I solved this problem by deleting network proxy. When I "wget  https://notary-server:4443" , the error shows that proxy tls  can't connect. so I  try do it , it works .

**Comment by HuKeping** [comment]
Thanks for the checking @rusirenye !

Maybe we could also add this tips somewhere in the docs? ping @cyli @riyazdf

**Comment by riyazdf** [comment]
@rusirenye glad that worked!

@HuKeping sorry I didn't get to this earlier. I'm a little hesitant to include documentation about network proxies since they can be quite custom and removing them might not always be the best advice.  Maybe let's hold off for now and add tips if we find similar issues from more users?  I'll close this for now, feel free to re-open :)
