### ISSUE TITLE
When running in CI system (no TTY) give up on passphrase

### ISSUE THREAD

**Issue by dhiltgen** [docker/notary#899]
When running in a CI system where no TTY is attached, if something goes wrong, notary winds up asking for a root pass phrase over and over without end.  We recently had our CI system run out of disk space due to gig's of logs with the repeating pattern:

```
Enter passphrase for new root key with ID fdd4003: 
Enter passphrase for new root key with ID fdd4003: 
Enter passphrase for new root key with ID fdd4003: 
```

Notary should be smarter and give up asking for a passphrase when there's no tty instead of looping.

**Comment by endophage** [comment]
It should give up after 10(?) retries. But if enabled, the password should be in the environment anyway.

i.e. Either there should be a password, or it shouldn't be enabled. If you're running in some other configuration it would be useful to us to understand what the use case is.

**Comment by endophage** [comment]
Ok, there's a bug with the 10 retries that I thought had been fixed so we've moved this issue into scope https://github.com/docker/notary/issues/812

We'll also take a look at detecting if there's no terminal attached.

**Comment by dhiltgen** [comment]
The scenario where I hit this was using delegation and I forgot to add the delegation key to a new repository that was created.
