### ISSUE TITLE
Look at replacing the docker term package with crypto/terminal

### ISSUE THREAD

**Issue by endophage** [docker/notary#907]
Go includes the crypto/terminal package in the core libraries and docker's term package pulls in other dependencies. I think crypto/terminal supports all the functionality we need (read a password without local echo and check if descriptor is a terminal) and would unwind one of our more painful dependencies.

**Comment by HuKeping** [comment]
I'd like to pick it up:)

**Comment by endophage** [comment]
Awesome!
