### ISSUE TITLE
Use correct regexes for image and tag names

### ISSUE THREAD

**Issue by diogomonica** [docker/notary#92]
`server.go` currently does:

```go
	r.Methods("POST").Path("/v2/{imageName:.*}/_trust/tuf/").Handler(hand(handlers.AtomicUpdateHandler, "push", "pull"))
```

We need to change the regular expression to support only valid characters for tags and image names.

**Comment by thaJeztah** [comment]
iirc, the distribution repo had a package to provide the correct regexes (but I may be mistaken)

/cc @stevvooe

**Comment by thaJeztah** [comment]
In case it's useful; Actually, it wasn't merged yet, but work on the registry validation rules can be found here: https://github.com/docker/distribution/pull/690
