### ISSUE TITLE
Upgrade to Go 1.7

### ISSUE THREAD

**Issue by endophage** [docker/notary#928]
Upgrade circle CI to use Go 1.7, fix any breakage that causes (none expected based on release notes).

This should give us faster, smaller binaries. Among other specifically interesting improvements, sha256 has been sped up by 10% or more, and we do a lot of sha256 hashing.

**Comment by cyli** [comment]
We may have some lint fixes I think for go 1.7.  On RC5 I see:

```
server/handlers/default_test.go:419: literal copies lock value from *metaStore: github.com/docker/notary/server/storage.MemStorage contains sync.Mutex
server/handlers/default_test.go:461: literal copies lock value from *metaStore: github.com/docker/notary/server/storage.MemStorage contains sync.Mutex
```

**Comment by riyazdf** [comment]
@cyli: If I remember correctly, I think that vet issue was handled by https://github.com/docker/notary/pull/793?

**Comment by cyli** [comment]
I still seem to be seeing it :|

**Comment by riyazdf** [comment]
ah, yes, you're right.  We can make a similar change 👍

**Comment by HuKeping** [comment]
Hola Go 1.7!
