### ISSUE TITLE
* fatal: Get https://localhost:4443/v2/: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by LenutaToderean** [docker/notary#935]
When I want to list the trusted data for busybox image from my private registry I receive "* fatal: Get https://localhost:4443/v2/: x509: certificate signed by unknown authority".  I sign using docker notary:signer-0.3.0 and notary:server-0.3.0 images and my own certificates and keys.

**Comment by riyazdf** [comment]
Hi @LenutaToderean, could you try taking a look at the `root-ca` field in notary client config file?

If you followed the instructions on the README for notary, it's in `~/.notary/config.json`, and only trusting the fixture certificates that we provided with notary, which might be the problem you're running into.

To fix this, you will want to set `root-ca` to point to your CA certificate (the config value should be the path relative to where the configuration file lives).

This [docs page](https://docs.docker.com/notary/reference/client-config/#/remote-server-section-optional) also has more information about configuring the notary client.

**Comment by LenutaToderean** [comment]
@riyazdf : Thank you very much! This was the problem.

**Comment by LenutaToderean** [comment]
Hi, @riyazdf!
I played with a new machine, fresh environment and I tried to sign images with Notary again. I followed the instructions from github: cloned the project, copied root-ca and config files from cmd/notary into ~/notary;  added 127.0.0.1 notary-server to my /etc/hosts file; docker-compose build and then docker-compose up. Notary server, signer and mariadb are up and running.  I can sign images no problem with that. But I receive " * fatal: Get https://localhost:4443/v2/: x509: certificate signed by unknown authority " to  """notary -s https://localhost:4443 -d ~/.docker/trust list localhost:5005/hello-world""" command. This time I don't have my own keys. I am sure it's something small but I cannot figure it out whats the issue. Any small advice it will me. Thank again!

**Comment by HuKeping** [comment]
Hi @LenutaToderean , 

> copied root-ca and config files from cmd/notary into ~/notary;

Did you put the config file into `~/notary` or `~/.notary`, because the Notary CLI use `~/.notary` as the default directory.

**Comment by LenutaToderean** [comment]
Hi, @HuKeping !
Thank you! I am having the config file into ~/notary and used your indications ... but I am getting the same error.

**Comment by leeadh** [comment]
HI @LenutaToderean , can i know how you resolved this? I followed the exact steps as in the readme and I got a certificate error still. 

1) git clone https://github.com/theupdateframework/notary.git
2) cd to notary
3)in notary directory:
 docker-compose build
$ docker-compose up -d
$ mkdir -p ~/.notary && cp cmd/notary/config.json cmd/notary/root-ca.crt ~/.notary

I went to the website 127.0.0.1:4443 and I got a "your metadata not found: your metadata does not exists"

I am using an ubuntu env.

Please help
