### ISSUE TITLE
Q: What hashes : sha256 from target.json (~/.docker/trust) means?

### ISSUE THREAD

**Issue by LenutaToderean** [docker/notary#940]
I don't understand what hashes (sha256) from target.json mean. What is the connection between it and the digest of the image or between it and anything else.

**Comment by riyazdf** [comment]
Hi @LenutaToderean, when pushing with Docker Content Trust, the `targets.json` contains mappings from image tag names to [digests](https://docs.docker.com/registry/spec/api/#/content-digests) of image manifests.  This is the same digest you see when you push an image by tag, at the end of the console output.

The manifest that is specified by hash in the `targets.json` specifies the content-addressable digests of the image layers, which forms a merkle tree for verifying all contents of an image on pull.

There's more detail about about how content trust works in the [docs](https://docs.docker.com/engine/security/trust/content_trust/). Please let us know if something isn't clear from the documentation and we'd be more than happy to explain further (and improve the docs)

**Comment by LenutaToderean** [comment]
@riyazdf Thank you!

**Comment by riyazdf** [comment]
@LenutaToderean no problem!  I'll close this issue, please re-open or open a new issue if you have more questions about this topic or would like to see some material added to the docs

**Comment by LenutaToderean** [comment]
@riyazdf Thanks a lot!

**Comment by LenutaToderean** [comment]
@riyazdf : Hi! 
I would like to read more about docker pull using DOCKER_CONTENT_TRUST set up to 1. Thanks again!

**Comment by riyazdf** [comment]
@LenutaToderean we have docs that are geared toward Docker Content Trust here: https://docs.docker.com/engine/security/trust/content_trust/

Essentially, Docker Content Trust uses notary as a library to lookup image digests for a tag, so that a `docker pull img:latest` is converted to `docker pull image@sha256:<hash>` by verifying and consuming notary's signed metadata.  Please feel free to let us know if you have any specific questions that aren't answered in the docs

**Comment by LenutaToderean** [comment]
Hi!
I wanna read more about keys in notary if it's possible please. I don't wanna open an issue just this. Thank you again!

**Comment by cyli** [comment]
Hi Lenuta!

We have some information about key management here:  https://github.com/docker/notary/blob/master/docs/best_practices.md#key-management and https://docs.docker.com/engine/security/trust/trust_key_mng/.

For more specific information about how key IDs are calculated and what's in the TUF metadata itself, please see https://github.com/theupdateframework/tuf/blob/develop/docs/tuf-spec.txt#L473.
