### ISSUE TITLE
will not build with Go 1.7

### ISSUE THREAD

**Issue by justincormack** [docker/notary#944]
Attempting to build with Go 1.7 I get

```
trustmanager/keyfilestore.go:100: literal copies lock value from *memStore: trustmanager.MemoryFileStore
```

**Comment by HuKeping** [comment]
Hi @justincormack  could you please make sure you build with the `master` because I don't see there is such a file under `$notary_dir/trustmanager`

**Comment by justincormack** [comment]
Oh, sorry my fork was out of date.
