### ISSUE TITLE
Update license

### ISSUE THREAD

**Issue by HuKeping** [docker/notary#947]
Shall we sync the license with docker/docker?

https://github.com/docker/docker/blob/master/LICENSE

**Comment by riyazdf** [comment]
@HuKeping could you elaborate further please?

I'm not sure I understand your proposal -- it's perfectly fine (and usually expected) for different open source projects in different repositories to have individual licenses.  Even though notary and docker share the same license type (Apache 2.0), I'm not sure I see the need to duplicate the license between them.

**Comment by HuKeping** [comment]
Ah OK, I just thought the licenses should be exactly the same if under the same project.

Closing.
