### ISSUE TITLE
notary key import delegation.key --gun being ignored

### ISSUE THREAD

**Issue by lewiada** [docker/notary#950]
When using Notary to import a delegated key, it seems to always import to ~/.docker/trust/private/tuf_keys, rather than to the registry/account/repo (i.e. gun) directory under tuf_keys.  I have tried using the -g / --gun flags to indicate where the imported key should go:

`notary key import delegation.key --gun docker.io/<account>/<imagename> --role user`

but they key always ends up in ~/.docker/trust/private/tuf_keys.  

Has anybody else experienced this?

**Comment by riyazdf** [comment]
Hi @lewiada, thanks for your report but this is expected -- notary keeps delegation keys in the top-level `tuf_keys` directory to better facilitate delegation keys being shared across GUNs

We're also working toward flattening the key store entirely for versions following notary 0.4, such that all keys are kept in a single directory https://github.com/docker/notary/pull/872

**Comment by lewiada** [comment]
@riyazdf thanks ... so if this is the expected behavior, what is the intended usage of the --gun flag?

**Comment by riyazdf** [comment]
@lewiada: Sorry if that was confusing, I'll try to make this clearer in the docs :)

The `--gun` flag is used for specifying roles for targets/snapshot keys if one is not given in the PEM header, since these keys are tightly coupled to a GUN.  Root and delegation keys do not retain any GUN information in their PEM headers or file locations

**Comment by lewiada** [comment]
@riyazdf okay so if I understand correctly I will be able to use a single delegated targets key to sign targets belonging to multiple repositories?  Can a basic target key also be used to sign across GUNs / repos?

**Comment by riyazdf** [comment]
@lewiada: yes, you can add a single delegation key to multiple delegation roles across different repositories.

Notary doesn't support reusing a targets key across repos since the targets, snapshot, and timestamp keys are auto-generated per repository at initialization time

**Comment by lewiada** [comment]
Okay this is actually very cool because the ability to use a single delegated targets key across repos actually simplifies some use cases for me.  It's a bit strange though, since target keys are generated for specific repo, yet that same target key can delegate a key that can be used across multiple repos.
