### ISSUE TITLE
Proposal: add output for successful commands

### ISSUE THREAD

**Issue by riyazdf** [docker/notary#973]
Especially on `publish`, it might be helpful to print an extra line stating that the publish was successful.  Maybe something like `Successfully published changes to <GUN>`?

```
🐳 $ notary publish repo
Pushing changes to repo
Enter passphrase for targets key with ID 1f4b045:
Enter passphrase for snapshot key with ID 760cfec:
Successfully published changes to repo
🐳 $ 
```

Same thing for `notary delete`, and commands that use `-p` could use a wrapped `Publish()` function to standardize printing to CLI

**Comment by HuKeping** [comment]
👍 I was add a similar on docker/docker side after a successfully DCT publishing 
https://github.com/docker/docker/pull/20307/commits/1a6866273697361f33ec908f51cf0e071a36b69d
