### ISSUE TITLE
Create types for GUN and role names, use them everywhere

### ISSUE THREAD

**Issue by endophage** [docker/notary#997]
Create two new types, should probably be located in `tuf/data/?`

```
type GUN string
type RoleName string
```

Use these types everywhere!

We have GUNs and roles being used beside eachother in lots of locations and it would be beneficial  to have stronger differentiation, especially when a function return signature has something like `..., string, string, ...`. We've been relatively (completely?) consistent so far in putting gun first, role second, but it's non-obvious which is which to a newcomer.

**Comment by HuKeping** [comment]
:+1:

**Comment by grantleehoffman** [comment]
@endophage i've started tackling this issue. Realized there were more changes to be made than I originally perceived. I have replaced most of the String types with GUN and RoleName types. Having a few issues with a couple of tests. Hoping someone more familiar with the code base could help me finish this off. https://github.com/grantleehoffman/notary/tree/type_updates

**Comment by endophage** [comment]
@grantleehoffman hello and thank you for picking this up. Can you submit your branch in as a PR with a "WIP: " (Work In Progress) prefix on the title. That'll help us collectively see which tests are having problems and coordinate feedback rather than multiple maintainers individually digging in to it.

**Comment by ecordell** [comment]
Addressed by #1087
