### ISSUE TITLE
Update vendoring for docker/distribution for token leeway

### ISSUE THREAD

**Issue by riyazdf** [docker/notary#999]
It would be nice to include the auth token leeway included in https://github.com/docker/distribution/pull/1686, which is slated for a `2.6` release (but is already on master branch)

**Comment by endophage** [comment]
Given that we are occasionally seeing related errors, marking this as a requirement for a 1.0 release.

**Comment by HuKeping** [comment]
This remind me of this pr #463 
Oh, I'm agree with closing that, it just jump out of my mind :)

**Comment by endophage** [comment]
@HuKeping It's a similar idea but in a different part of the code.

We've had a small number of errors (5 in 2 weeks) coming out of distribution's auth package that appear to be related to clock skew in the order of 1 second (i.e. `token not to be used before 1476140678 or after 1476140978 - currently 1476140677`). In a separate discussion I advised another team in Docker that the [JWT spec](https://tools.ietf.org/html/rfc7519#section-4.1.4) explicitly allows for leeway of "a few minutes" for both the `nbf` (not before) and `exp` (expiry) fields. We believe but haven't investigated, that the distribution auth package is taking a strict approach.
